### ISSUE TITLE
How do you manage your sleep?

### ISSUE THREAD

**Issue by clementgalidie** [sindresorhus/ama#101]
Hello!
Long nights? short nights? polyphasic sleep? Something else?

**Comment by clementgalidie** [comment]
Found answer in [#52](https://github.com/sindresorhus/ama/issues/52).

**Comment by sindresorhus** [comment]
I used to have a really bad sleeping rhythm, but I realized I lost a lot of productivity and generally felt more tired. Sleep is super important and definitely not something worth skimping on.
