### ISSUE TITLE
Opinions on legalizing gay marriage or changing prohibition laws on marijuana?

### ISSUE THREAD

**Issue by timothybone** [sindresorhus/ama#102]
legalizing gay marriage or changing prohibition laws on marijuana either on a country level or a global level? For or opposed are both good answers here imo. 

if you have an opinion/answer it goes without saying you can include it or not at your discretion.

**Comment by sindresorhus** [comment]
I don't have strong political opinions, but I'm all for equal rights no matter who you are, including legalizing gay marriage. Don't really have an opinion on legalizing marijuana as I've never thought about it before, but I guess I would be in favor of legalizing if I had to take a stand.
