### ISSUE TITLE
What do you think about Rust?

### ISSUE THREAD

**Issue by robbbz** [sindresorhus/ama#106]
Heard you was into it. I'm wondering what you think. Will it be your future language? Will you have many cargo modules too? Are you planning to be active in its open source community? Where are you using it for practically? Are you going to use it standalone or write libs to use in node/ruby/python/...?

:beer:

**Comment by robbbz** [comment]
closing because I asked some more questions in a new issue.

**Comment by sindresorhus** [comment]
No need to open a new issue though. You could have just edited this one ;)

For posterity, new one here: https://github.com/sindresorhus/ama/issues/127

**Comment by robbbz** [comment]
Oh. I thought if I edit the issue you won't get a notification. Thanks for spending all your time answering questions.

**Comment by sindresorhus** [comment]
I wouldn't, but that doesn't matter as I haven't answered it yet :)
