### ISSUE TITLE
What were you doing in the military?

### ISSUE THREAD

**Issue by robbbz** [sindresorhus/ama#107]
I'm wondering what programming skills are useful for there. Did they use node.js?

**Comment by sindresorhus** [comment]
I worked there as web-developer & photographer. I mostly did front-end JS for the [website](https://forsvaret.no)/intranet, some internal apps with Django (Python), and [some mobile apps](https://itunes.apple.com/no/app/milit-re-forkortelser/id581203024). No Node.js though... I also went on various training missions as a [photographer](https://instagram.com/p/aGMRlQF4LN/?taken-by=cyberforsvaret).
