### ISSUE TITLE
What if you die?

### ISSUE THREAD

**Issue by robbbz** [sindresorhus/ama#109]
Hypothetical question. 

The whole node community indirectly depends on you. Your modules are in Gulp, Grunt, Hapi, Express, you're everywhere.

I'm wondering, did you every think about the fact that if you ever die you break pretty much the whole world? All of your modules will have to be forked and replaced, you'll be the only one with access to GitHub/npm.

Just wondering how you go about the whole world depending on you.

:beer:

**Comment by sindresorhus** [comment]
Not to worry. My clones will take over in such a scenario :p

First of all. Nothing will change. My modules will not suddenly disappear. Most of them are finished anyways and will never change. That's the beauty of small focused modules.

I do have some friends that have access to all my repos. As for npm, they can be contacted to have them transfer the modules. And to be sure:

> I, Sindre Sorhus, allow the follow npm usernames to be made owner of all my modules in the case of my death; `addyosmani`, `passy`, `kevva`.

**Comment by passy** [comment]
For reference: https://en.wikipedia.org/wiki/Bus_factor

**Comment by robbbz** [comment]
Thanks :+1:

**Comment by addyosmani** [comment]
You know.. it just occurred to me that the rest of us may not have done this. So, in the interest of OSS

> I, Addy Osmani, allow the following npm (and GitHub) usernames to be made owners of all of my modules and repositories in the case of my death: `sindresorhus`, `passy`, `stephenplusplus`, `kevva`, `arthurvr`

That said, I've done significantly less of importance than Sindre so this may just be in vain :P.

**Comment by robbbz** [comment]
> sindresorhus, passy, stephenplusplus, kevva, arthurvr

@addyosmani You all really seem to have a romantic relationship. Doing pretty much everything together. Wow. Don't take me wrong that's super beautiful.

**Comment by passy** [comment]
Aww! :)

**Comment by sindresorhus** [comment]
:heart_eyes_cat:
