### ISSUE TITLE
Have you done any talks at conferences for the work you do? If so, which one has been your favorite and why?

### ISSUE THREAD

**Issue by Stephn-R** [sindresorhus/ama#11]

**Comment by sindresorhus** [comment]
I have not. [I'm not really into conferences.](https://github.com/sindresorhus/ama/issues/6#issuecomment-117659978)

**Comment by bfred-it** [comment]
404 already? :(

**Comment by callumlocke** [comment]
@sindresorhus could you update the link? I'm curious

**Comment by sindresorhus** [comment]
@callumlocke GitHub took down a bunch of issues on this repo, 22 to be exact, because the users posting them were flagged... Without even notifying me. I only discovered it by accident. Not cool GitHub. Still waiting on them to resolve it.

**Comment by icyflame** [comment]
@sindresorhus Finally, I get the answer! I received an email saying that issue #47 was `What code style guide do you use?` and, now, I couldn't find it anywhere. I had to re-post the issue as #83 ! Removing issues is really weird! :unamused: with GitHub!

**Comment by sindresorhus** [comment]
Some of the issues should be back now, including the one referenced in my first answer. Though still some missing...
