### ISSUE TITLE
Do you like living in Norway?

### ISSUE THREAD

**Issue by robbbz** [sindresorhus/ama#110]

**Comment by sindresorhus** [comment]
Not particularly. Luckily I don't live there anymore. It's cold almost all year. In Lillehammer, where I used to live, it got down to -38℃ in the winter. It's one of the most expensive countries in the world. Very little innovation happens here other than in oil and energy, especially compared to Sweden. The traditional food is bland. Most Norwegians like it here though, so I'm probably the outlier.

However, some places in Norway are beautiful **in the summer**: http://www.huffingtonpost.com/2014/12/31/norway-greatest-place-on-earth_n_4550413.html

**Comment by lborgav** [comment]
Where are you living now?

**Comment by sindresorhus** [comment]
I'm homeless at the moment. In Norway for the summer visiting my parents. Then travelling to Bangkok in the fall.

**Comment by nickedes** [comment]
So @sindresorhus you enjoying being homeless?

**Comment by sindresorhus** [comment]
Definitely. It's nice being free to travel anywhere at any time. I don't really care much about material stuff either, so I have everything I need and care about in a small backpack.

**Comment by nickedes** [comment]
Sounds Good :smile: :+1:

**Comment by lborgav** [comment]
Minimalism way of life!
BTW, this article is very amazing: [leostartsup.com/2014/12/living-with-one-bag/](leostartsup.com/2014/12/living-with-one-bag/)

**Comment by najela** [comment]
@lborgav  That link gives 404 when clicked on. It should be http://leostartsup.com/2014/12/living-with-one-bag/

**Comment by lborgav** [comment]
@najela Thanks! You're right. This is a good article about minimalism :smile:
