### ISSUE TITLE
How do you keep track of all the modules you create?

### ISSUE THREAD

**Issue by erbridge** [sindresorhus/ama#113]
You make lots of really small modules, and I wonder how you keep track of what you've made, and find things when you need them for future projects.

**Comment by pacMakaveli** [comment]
That's a good one! My feed looks like this: 

<img width="474" alt="screen shot 2015-07-09 at 3 26 15 pm" src="https://cloud.githubusercontent.com/assets/894272/8597715/e9b058a2-264e-11e5-9abf-e2eac9f929cf.png">

I too would like to know you secret! :)

**Comment by sindresorhus** [comment]
I'm usually not that good at remembering things, but I do remember most of my modules and how to use them. I think it's similar to being able to more easily remember text you've written yourself. The rest I just use GitHub search for. This is also one of the benefits of [small focused modules](https://github.com/sindresorhus/ama/issues/10); Most of them are only input→output.
