### ISSUE TITLE
What's with adding a bunch of people to your repos in big chunks all at the same time?

### ISSUE THREAD

**Issue by stephenplusplus** [sindresorhus/ama#114]
<img width="524" alt="screen shot 2015-07-07 at 9 37 52 am" src="https://cloud.githubusercontent.com/assets/723048/8547277/dc57f7c4-248b-11e5-9c56-36cde690e9c1.png">

**Comment by sindresorhus** [comment]
They help me out triaging issues/PRs and generally improve those projects. I just add them once in a while, using https://github.com/kevva/github-add-collab.

Also useful for: https://github.com/sindresorhus/ama/issues/109

**Comment by robbbz** [comment]
@sindresorhus Why don't you just dump all your modules in an org so it's easier to manage that? Also that would clearly attribute the work others are doing. Also in case of #109 somebody else could have *owner* access.

**Comment by stephenplusplus** [comment]
Related: https://github.com/orgs/taptapship/people :)
