### ISSUE TITLE
How many lines is the longest function you've written？

### ISSUE THREAD

**Issue by moonye6** [sindresorhus/ama#117]

**Comment by sindresorhus** [comment]
[50 lines](https://github.com/sindresorhus/strip-json-comments/blob/480c072c2595f92e7655b9f27a8dc0350f45e314/strip-json-comments.js#L11-L60), I think. Usually when a function gets above 20-25 lines I try to split it up.

**Comment by goforgold** [comment]
I had read it don't remember where that functions should not exceed 7-10 lines. It's really hard to break a program in that small pieces. Isn't it?

**Comment by goforgold** [comment]
May I know one more thing in line with this question?

What design principles you follow? Any ref article, book? I want to write highly efficient and maintainable codes.

**Comment by sindresorhus** [comment]
> It's really hard to break a program in that small pieces. Isn't it?

At first, yes. Getting that kind of mindset takes time. Just do it over and over and you'll improve.

> What design principles you follow? Any ref article, book? I want to write highly efficient and maintainable codes.

My own? I don't really know. My way of coding is just from experience doing it wrong over and over until it got less and less wrong. And I read a lot of code. I enjoy browsing random repos and reading its code. I don't really read programming books, so can't help you there.

**Comment by jacor84** [comment]
@sindresorhus I think you should update answer to this question. There is a ~1000 line function here:
https://github.com/sindresorhus/file-type/blob/master/index.js#L8 :-)

**Comment by SwiftWinds** [comment]
> @sindresorhus I think you should update answer to this question. There is a ~1000 line function here:
https://github.com/sindresorhus/file-type/blob/master/index.js#L8 :-)

As an update, the long function has been moved to core.js: https://github.com/sindresorhus/file-type/blob/master/core.js#L59 ;P
