### ISSUE TITLE
Did you ever consider moving your modules to an organisation? 

### ISSUE THREAD

**Issue by robbbz** [sindresorhus/ama#118]
So you don't have to add people to repos individually to all of your repos. Would also make team management easier and would help with #109.

**Comment by sindresorhus** [comment]
I could, but I don't think I'm going to, at least not for now. I already have a lot of modules in various orgs, but most of the modules I'm the only one that touch anyways, and I prefer to be the [BDFL](https://en.wikipedia.org/wiki/Benevolent_dictator_for_life) on them as I have very strong opinions on how modules should be made. With an org I somewhat lose that. All it takes for me to add people to all my repos is one command: `github-add-collab kevva -s`, so I guess I don't really see the benefit.
