### ISSUE TITLE
More issues were deleted

### ISSUE THREAD

**Issue by Whoaa512** [sindresorhus/ama#122]
In particular #109, #108, #107, #106, not sure what else. Come on Github!

**Comment by sindresorhus** [comment]
Yeah, I noticed. This is far from the first time. GitHub keeps blocking non-spam users...

Those issues seems to be back now though.

Poor @robbbz.

**Comment by robbbz** [comment]
I just noticed today that my issues were all removed together with my account. Strange is that logged in I can do what I want, but it just doesn't become public.

I contacted GitHub support this afternoon without any response.

**Comment by sindresorhus** [comment]
@robbbz They've flagged you 3 times now. I've complained to GitHub, and they've fixed it, but it still keeps happening. Not just you. It happened to @meeeesz too. And the worst part is that they don't even notify me. I just noticed by coincidence that some issues were gone... I'm so annoyed by GitHub right now.

**Comment by jmeas** [comment]
> I'm so annoyed by GitHub right now.

Hah. I noticed their strict new account policies awhile ago. If you make a new account and create two or three gists, the account gets immediately locked. Or, at least, that was the case a few months ago. It really messed up a class I was teaching where I was introducing the students to Github.

These new account algorithms they've set in place are pretty bad...

**Comment by robbbz** [comment]
This is so annoying. I don't even get notified when it happens, it's not noticeable from my side. What could be the reason of their spambots blocking me?

**Comment by arthurvr** [comment]
And then @robbbz comments here and his issues disappeared, again. Ugh GitHub.

**Comment by sindresorhus** [comment]
And now back again.
