### ISSUE TITLE
How do you relax from coding?

### ISSUE THREAD

**Issue by loginwashere** [sindresorhus/ama#124]

**Comment by sindresorhus** [comment]
![tumblr_mndj28lzs21qdlh1io1_250](https://cloud.githubusercontent.com/assets/170270/8580483/34e95e70-25bb-11e5-86d3-229770325d5e.gif)

When not coding, on the computer I like to do some designing, [watch TV-series](https://github.com/sindresorhus/ama/issues/46#issuecomment-117842723), other activities on GitHub like responding to issues, plan my next projects, write blog post drafts I know I'll never finish, edit photos, chat with friends.

In real life, I exercise, it's a great way to clear your head after coding. Read books on my Kindle. Hangout with friends and family. Photography. Walk the [dog](https://github.com/sindresorhus/ama/issues/2). And when traveling, explore new places and get lost.
