### ISSUE TITLE
How fast do you type?

### ISSUE THREAD

**Issue by robbbz** [sindresorhus/ama#128]
http://play.typeracer.com/ :wink: 

If you don't want to share, no problem, I'm not really interested in your personal score. This is more the question: do you think it makes sense as programmer to be able to type fast?

**Comment by najela** [comment]
I actually like that game.

**Comment by sindresorhus** [comment]
73 wpm. I'm not a fast typist, but that doesn't matter. What you type is what matters. You should want to type as little as possible. The more you type, the more bugs you introduce. I use most of my time thinking. The typing part is easy and don't take very long.

**Comment by nickedes** [comment]
:trophy:

**Comment by goforgold** [comment]
🐶

**Comment by thenyel** [comment]
on point!!!

**Comment by stefek99** [comment]
73 is actually quite a stunt... I just tried: 53, my friend: 50...

50% improvement at these type of speeds is huge!
