### ISSUE TITLE
How do you get so much done? 👏

### ISSUE THREAD

**Issue by wesbos** [sindresorhus/ama#13]
It seems like every other package, plugin or library I use is done by you. 

How do you get so much done? Are you paid to work on these open source projects? _What is in that secret sindresorhus sauce?_

**Comment by bhaveshgohel** [comment]
+1 to the Question. :)

**Comment by addyosmani** [comment]
Sindre never sleeps. He's basically made of unicorns, cats and black magic :tophat:

**Comment by phoenixnebula** [comment]
waiting for his answer

**Comment by icyflame** [comment]
+1 to the OP!

**Comment by hackerkid** [comment]
@addyosmani @feross You guys should start an AMA too.

**Comment by maxogden** [comment]
Most software exists in the `lib/` folder. Most programmers work on one repo and put all their hard work into `lib/`. The appearance of productivity that you see amongst people like @sindresorhus is achieved simply through taking the small extra effort up front to document modular components, create repos for them, and publish them to npm. In the long term this strategy saves time as it deduplicates work across projects.

**Comment by sindresorhus** [comment]
I think my assumed super-productivity is an illusion of producing many repos. I wholeheartedly agree with @maxogden's sentiment. You could rather say I'm an efficient repo and package.json maker. I do work hard however, but by taking something that could be 10 files in a `lib/` folder or 10 functions in a `util.js` file and making them separate modules my productivity seems tenfold.

I think making [small focused reusable modules](https://github.com/sindresorhus/ama/issues/10#issuecomment-117766328) has had the biggest impact on my productivity. Being able to reuse a lot of code easily means I can glue things together faster, hence producing more things. I've done a lot of Node.js so my proficiency is pretty high, which results in better efficiency.

Other than that it's all about discipline. I'm highly passionate about making things on the computer and spend a lot of time doing so. I prioritize coding over other stuff like TV, surfing, reading, etc. Sometimes too much so...

-

> Are you paid to work on these open source projects?

[No](https://github.com/sindresorhus/ama/issues/14#issuecomment-117747234)

**Comment by prakhar1989** [comment]
> Other than that it's all about discipline. I'm highly passionate about making things on the computer and spend a lot of time doing so. I prioritize coding over other stuff like TV, surfing, reading, etc. Sometimes too much so...

I'm generally not a +1 kind of guy but I couldn't help it.

:+1:
