### ISSUE TITLE
Would you rather fight 100 duck-sized horses, or 1 horse-sized duck?

### ISSUE THREAD

**Issue by devatrox** [sindresorhus/ama#130]

**Comment by sindresorhus** [comment]
One horse-sized duck:

![main-qimg-487f4d4f382d3fb56cc073b01542eb81](https://cloud.githubusercontent.com/assets/170270/8658960/9d5567ca-29a7-11e5-889c-9f4b881ff6e6.jpeg)

I could never fight duck-sized horses. They would look so cute. I would just end up cuddling them.

**Comment by sindresorhus** [comment]
https://twitter.com/sindresorhus/status/687394946651942913
