### ISSUE TITLE
What are your favourite keyboard shortcuts?

### ISSUE THREAD

**Issue by s10wen** [sindresorhus/ama#131]

**Comment by sindresorhus** [comment]
- <kbd>Ctrl</kbd> <kbd>`</kbd> to toggle [TotalTerminal](http://totalterminal.binaryage.com).
- <kbd>Alt</kbd> <kbd>`</kbd> to toggle [TotalFinder](http://totalfinder.binaryage.com).
- <kbd>Alt</kbd> <kbd>Space</kbd> to toggle [Dash](https://kapeli.com/dash).
- <kbd>Cmd</kbd> <kbd>Space</kbd> to toggle [Alfred](http://www.alfredapp.com).
- <kbd>Cmd</kbd> <kbd>Tab</kbd> to switch between apps.
- <kbd>Ctrl</kbd> <kbd>Tab</kbd> to switch between Chrome/TotalFinder/Sublime tabs.

**Comment by huei90** [comment]
How do you type that Ctrl + `

**Comment by SamVerschueren** [comment]
@huei90 Depends on keyboard layout but on my qwerty keyboard the ` (backtick) is right under the escape button.

**Comment by huei90** [comment]
no, i mean the symbol like ![screen shot 2015-07-10 at 3 00 54 pm](https://cloud.githubusercontent.com/assets/2560096/8613716/98b57cf4-2714-11e5-89f1-0d7eeaf5ae69.png)

**Comment by SamVerschueren** [comment]
Oh, my bad. You just have to wrap it between `kbd` html tags.

<kbd>Ctrl</kbd>

**Comment by huei90** [comment]
<kbd>Got it! Thanks @SamVerschueren </kbd>

**Comment by s10wen** [comment]
@sindresorhus some good ones there thanks! Here are some of mine:

* <kbd>Cmd</kbd> <kbd>`</kbd> to toggle [Sublime Text](http://www.sublimetext.com/).
* <kbd>Cmd</kbd> <kbd>T</kbd> new tab in Chrome.
* <kbd>Cmd</kbd> <kbd>Shift</kbd> <kbd>T</kbd> open the last closed tab in Chrome.
* <kbd>Cmd</kbd> <kbd>Alt</kbd> <kbd>I</kbd> toggle dev tools in Chrome.
* <kbd>Shift</kbd> <kbd>?</kbd> when in dev tools, open up settings in Chrome.
* <kbd>Cmd</kbd> <kbd>Shift</kbd> <kbd>D</kbd> toggle dev tools docking in Chrome (thanks @addyosmani).
* <kbd>Cmd</kbd> <kbd>L</kbd> highlight content in the web address area in Chrome.

Ha, guess I spend a lot of time in Chrome :wink:

Double win with this answer as I also learned about `kbd` :thumbsup:

**Comment by mattdrose** [comment]
@sindresorhus You should consider remapping your <kbd>Caps Lock</kbd> to <kbd>F19</kbd>. It works beautifully with Alfred and Sublime for mapping custom shortcuts. [Tut here.](http://brettterpstra.com/2012/12/08/a-useful-caps-lock-key/)
