### ISSUE TITLE
Do you have a day job?

### ISSUE THREAD

**Issue by daryl** [sindresorhus/ama#14]
Where/what do you do for work and how many hours do you do a week?

**Comment by es128** [comment]
![image](https://cloud.githubusercontent.com/assets/1740641/8459443/4210efe4-1feb-11e5-86c3-dcf5a3e09038.png)

**Comment by sindresorhus** [comment]
I had a full-time job, 8 hours a day, 5 days a week, as a web developer for the Norwegian Armed Forces until August last year when I quit my job to go traveling. I'll have to work again next year. My Open Source stuff is done in my free time. The only time I've gotten paid for doing Open Source was a 3-month contract with Google working on Yeoman.

**Comment by lborgav** [comment]
So, have you used to be a military from Norwegian Armed Forces? For how many years?

**Comment by sindresorhus** [comment]
I worked for the military as a soldier (in uniform) for 5 years.

**Comment by wynlim** [comment]
I wish there's a way for me to like github issues. ;)

**Comment by stefek99** [comment]
5 years in military! (wow)

**Comment by RoyLING** [comment]
@wynlim I want that too!

**Comment by dd1994** [comment]
5 years in military :scream:

**Comment by dandv** [comment]
> I worked for the military as a soldier (in uniform) for 5 years.

You said [in a different issue](https://github.com/sindresorhus/ama/issues/411) that you worked in the military "as a photographer and programmer". How long were you a soldier in uniform, and how long a photographer and programmer?

**Comment by sindresorhus** [comment]
@dandv I was both.
