### ISSUE TITLE
Why do you make logos for small modules?

### ISSUE THREAD

**Issue by ahmadnassri** [sindresorhus/ama#140]
I've noticed you've done this a couple of times, putting a logo on a library, I'm not sure where I stand on this yet ... why do you do it? do think there's value in doing it?

P.S. I know bigger projects like say, Angular, Express, etc ... *(anything on npmjs.com home page really)* have logos, but I would argue those are more "application scale", than "library scale" projects

**Comment by sindresorhus** [comment]
Sometimes when I need a break from coding I like to design things. These project strictly don't need a logo, but it does make them look more enticing.

Some projects I've made logos for:

- [pageres](https://github.com/sindresorhus/pageres)
- [got](https://github.com/sindresorhus/got)
- [hasha](https://github.com/sindresorhus/hasha)
- [awesome](https://github.com/sindresorhus/awesome)
- [chalk](https://github.com/chalk/chalk)
- [fkill](https://github.com/sindresorhus/fkill)
- [brightness](https://github.com/kevva/brightness)
- [build-time-tracker-plugin](https://github.com/passy/build-time-tracker-plugin)
- [imagemin](https://github.com/imagemin/logo/blob/master/images/logo.png)
- [node-sass](https://github.com/sass/node-sass/blob/888ea82f7869b955b4d1a41b4ccecf8bc10f6df1/media/logo.png)

**Comment by lborgav** [comment]
"but it does make them look more enticing" :+1:
