### ISSUE TITLE
Housing during travels?

### ISSUE THREAD

**Issue by Whoaa512** [sindresorhus/ama#143]
What sort of housing accommodations do you use when traveling? Airbnb, hostels, hotels?

If Airbnb, do you perfer entire homes/apts or rooms in shared spaces?

**Comment by sindresorhus** [comment]
I mostly stay in hotels as they're cheap in Asia. AirBnB was usually the same price or more. I'm allergic to snoring so I usually stay away from hostels. I've also used [Couchsurfing](https://www.couchsurfing.com/). Haven't tried AirBnB, but I guess shared spaces, as I usually travel alone and it's nice to meet people.
