### ISSUE TITLE
What does your RSS feed list look like?

### ISSUE THREAD

**Issue by DIYgod** [sindresorhus/ama#145]

**Comment by skippednote** [comment]
Like this https://github.com/sindresorhus/stuff/blob/master/feeds.xml

**Comment by sindresorhus** [comment]
Answered this in https://github.com/sindresorhus/ama/issues/45.

RSS feeds I subscribe to: http://opmlviewer.com/Viewer/?https://github.com/sindresorhus/stuff/raw/master/feeds.xml
