### ISSUE TITLE
Will you switch your projects to ESLint eventually?

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/ama#146]
I know it's no trivial task to switch your numerous projects to a new linter, but I wonder if you plan on it eventually, as I saw you contributing to eslint.

(Reason I'm asking is https://github.com/SublimeLinter/SublimeLinter3/issues/266 which prevents me from automatically using the correct in-editor linter on your projects)

**Comment by kevva** [comment]
I'm pretty sure he is.

**Comment by arthurvr** [comment]
Ref https://github.com/sindresorhus/generator-nm/issues/14

Though if we plan to switch all modules over to ESLint we should really find an automated way. Did you do all those `update .travis.yml` commits by hand or automated?

**Comment by sindresorhus** [comment]
Yes. I'm working on it. Will most likely have something ready next weekend.

> Though if we plan to switch all modules over to ESLint we should really find an automated way.

:+1: 

> Did you do all those update .travis.yml commits by hand or automated?

By hand :/

**Comment by silverwind** [comment]
Note that eslint will default to `--reset` in 1.0 (https://github.com/eslint/eslint/commit/1445ded049402d3b2f7a60da7aa3550623482b38).

I personally use explicit rule lists in all my projects, but it's a special kind of a pain once you need to add/update rules in all projects. Let me know if you find a automated solution to that.

**Comment by silverwind** [comment]
Thanks for your time!

**Comment by hzoo** [comment]
@silverwind ESLint has shared configs (like jscs presets) that you could make yourself as a npm module http://eslint.org/docs/developer-guide/shareable-configs

**Comment by sindresorhus** [comment]
I am now → https://github.com/sindresorhus/xo

**Comment by silverwind** [comment]
Nice one. Surely beats managing thousands of `.eslintrc` ;)
