### ISSUE TITLE
what programming language would you suggest?

### ISSUE THREAD

**Issue by robbbz** [sindresorhus/ama#148]
I do some JavaScript and Ruby but I wonder what you think is the future. I do some haskell and functional programming already, but in practical that doesn't help much. I wonder what you think is the future?

**Comment by robbbz** [comment]
Closing as I got an answer on https://github.com/sindresorhus/ama/issues/7 and  I feel like it's enough; have fun answering the other 70 questions :beers:

**Comment by sindresorhus** [comment]
JavaScript. Hate it or love it, doesn't matter. It's here to stay. If there's one language I think I'll still be using in 30 years, it's JS. JS is best with Node.js though. Try making some node modules and you'll quickly get hooked ;)
