### ISSUE TITLE
What do you think about TypeScript and Flow?

### ISSUE THREAD

**Issue by vlkosinov** [sindresorhus/ama#15]

**Comment by sindresorhus** [comment]
I think they're both interesting experiments. I strongly believe, now more than ever, that JavaScript needs some kind of optional type semantics. I welcome anything that wants to prototype that. I've only briefly experimented with TypeScript and Flow, but my preference tended more towards Flow. If you haven't already, try them both out and make up your own mind ;)

Good reading: http://www.2ality.com/2014/10/typed-javascript.html

**Comment by vlkosinov** [comment]
Thank you!
