### ISSUE TITLE
What is the most critical bug you want to see fixed in npm?

### ISSUE THREAD

**Issue by addyosmani** [sindresorhus/ama#154]
You just get to name one :P.

**Comment by kevva** [comment]
Hah, `scripts`! More of a security hole than a bug though.

**Comment by sindresorhus** [comment]
Only one? :/ There are so many...

If I had to pick just one though, it would be the permission issues. `npm ERR! code EACCES` sounds familiar? :p I've probably closed 1000+ issues (not even over-exaggerating a bit...) like that in my repos in the past year.

-

You didn't ask this, but needs saying, the most ciritical bug in the Node.js ecosystem is people not upgrading. Doesn't help that npm (and Node.js) keeps squashing bugs if people just stay on ancient versions. I have a similar amount of closed issues where I tell people to upgrade.

**Comment by Qix-** [comment]
@kevva `npm install unicorns` - scripts are a wonderful thing, dontcha know.

**Comment by addyosmani** [comment]
:+1: Thanks!
