### ISSUE TITLE
Favorite testing framework and why?

### ISSUE THREAD

**Issue by robbbz** [sindresorhus/ama#155]
Related:

* What's up with ava?
* How do you test browser-side modules built for use with browserify?
* What framework do you use to test webapps?
* Any experience with Intern?

**Comment by sindresorhus** [comment]
None. Testing could be so much better! I'm a big fan of [tape](https://github.com/substack/tape) for its simple syntax and lack of implicit globals, but I really [dread the default TAP output](https://github.com/sindresorhus/ava#why-not-mocha-tape-node-tap). It's also a bit buggy and the code is very coupled to being a TAP stream, so it's hard to reason about. My newly released test runner [AVA](http://ava.li) is the closest you can get to being my favorite, but it still has a long way to go until I'm completely happy about it.

The few times I've had to test browser-side modules I used a combination of Mocha and PhantomJS. It was a horrific experience. We're [currently looking](https://github.com/sindresorhus/ava/issues/24) into browser testing with AVA using [Browserify](http://browserify.org) and [hihat](https://github.com/Jam3/hihat).

Haven't tried Intern. I looked at it far back when it was first released and it felt a bit heavy for my taste. Looks like it could maybe work with AVA through an adapter.
