### ISSUE TITLE
What if you were not a web developer?

### ISSUE THREAD

**Issue by HugoGiraudel** [sindresorhus/ama#156]
Tomorrow, you can start over. What would you choose and why? :)

**Comment by sindresorhus** [comment]
If I could start over, I would pick exactly what I'm doing. I can't imagine doing anything else.

But for sake of argument, I had to pick something different. I think I would have liked to be a travel photographer. I both enjoy [photography](https://github.com/sindresorhus/ama/issues/149) and travel. Exploring new places. Observing the culture. Hunting for the perfect picture. Learning from people. Documenting life.
