### ISSUE TITLE
Will goats be more popular on the internet than cats at some point?

### ISSUE THREAD

**Issue by passy** [sindresorhus/ama#158]

**Comment by sindresorhus** [comment]
According to Google Trends it's highly unlikely to happen in the near term, but I'm confident that at some point in the future humanity will realize goats are superior. In the meantime enjoy this [sound simulation of a bad goats brain.](https://soundcloud.com/gstfs/goat-storm-nyan-goat-mix)

[<img width="863" alt="screen shot 2015-08-05 at 04 06 32" src="https://cloud.githubusercontent.com/assets/170270/9076823/81cec852-3b27-11e5-8ef0-990cafe3ca63.png">](https://www.google.com/trends/explore#q=%2Fm%2F01yrx%2C%20%2Fm%2F03fwl&cmpt=q&tz=Etc%2FGMT-2)
