### ISSUE TITLE
will you give me a unicorn?

### ISSUE THREAD

**Issue by shama** [sindresorhus/ama#16]

**Comment by arthurvr** [comment]
Duplicate of https://github.com/sindresorhus/ama/issues/8?

**Comment by shama** [comment]
Fixed

**Comment by es128** [comment]
![image](https://cloud.githubusercontent.com/assets/1740641/8459979/da574a84-1fee-11e5-819e-64955b3b77be.png)
(I actually own a pair of these and wear them to work regularly)

**Comment by es128** [comment]
Here's some more unicorns for you @shama: www.cornify.com

**Comment by shama** [comment]
Haha rad shoes @es128! Thank you!
