### ISSUE TITLE
How do you make a living if you don't have a job and don't take donations? 

### ISSUE THREAD

**Issue by kosz** [sindresorhus/ama#160]

**Comment by sindresorhus** [comment]
I don't make a living, currently. I have some [money saved up](https://github.com/sindresorhus/ama/issues/89). I don't really care much about money or material things, don't use much money, and don't have a lot of monthly expenses.

**Comment by passy** [comment]
I have massive respect for you actually pulling this off. I hear a lot of people saying this, but almost none of them doing it.

**Comment by kosz** [comment]
+1 indeed

**Comment by disrupticons** [comment]
```javascript
var sindre = require('respect')
```

**Comment by andineck** [comment]
yup, respect!

**Comment by letsila** [comment]
respect

**Comment by Prakti** [comment]
+1

**Comment by iamabid** [comment]
respect

**Comment by rajzshkr** [comment]
+1

**Comment by kuldeepkeshwar** [comment]
only a few people do this 
respect !!!

**Comment by blairanderson** [comment]
@sindresorhus do you still live of savings 4 years in?

**Comment by JCMais** [comment]
@blairanderson he has a patreon page, the community is supporting him: https://www.patreon.com/sindresorhus

Which is even more awesome

**Comment by stefek99** [comment]
https://www.patreon.com/sindresorhus

![image](https://user-images.githubusercontent.com/249703/44838144-512ccc00-ac33-11e8-9aa6-5bdb763e84f0.png)
