### ISSUE TITLE
What is your favorite quote?

### ISSUE THREAD

**Issue by oscarmcm** [sindresorhus/ama#162]

**Comment by sindresorhus** [comment]
> **The people who are crazy enough to think they can change the world are the ones who do.**
> — Apple’s ["Think Different" commercial](https://www.youtube.com/watch?v=8rwsuXHA7RA&list=PLjtHM8-Cc17N9FGfZY95uXfUiX0V9o1DP), 1997

It inspires me to work harder. Be a rebel. [Do what other people say I can't.](https://twitter.com/sindresorhus/status/504655843879813120) See the possibilities, not the limits. Nothing is impossible, just hard. Challenge myself. Break out of my comfort-zone. Do > Talk.

**Comment by HoBi** [comment]
:+1:
