### ISSUE TITLE
A day in life

### ISSUE THREAD

**Issue by iakshay** [sindresorhus/ama#167]
What is your daily routine like? How much time do you spend on coding and non-coding things (cooking, travelling, workout etc.)?

**Comment by diessica** [comment]
I guess my question is kinda related:
**How do you start your work day?**

**Comment by sindresorhus** [comment]
Normal weekday:

- Wake up around 9 to 11 AM and shower.
- Walk to a coffee shop.
- Sit in coffee shops and hack until around 5 PM. "Hack" being coding, emails, Twitter, GitHub issues, AMA answering, etc. I usually start by reading some emails, triaging GitHub issues. look through todo-list. After a while my brain has woken up and I'm ready for some coding.
- Meet up with girlfriend for dinner somewhere. (Nobody cooks at home in Bangkok.)
- Then some gf activities; shopping, cinema, drinks, pancakes, movie at home, or etc.
- 0 to 2 hours of hacking after girlfriend sleeps.

In the weekend there's usually not much hacking time as we're usually busy with other activities.

**Comment by t-lock** [comment]
@sindresorhus Did I read that correctly, that you have a wife and a girlfriend?

**Comment by sp90** [comment]
Okay, this might just be me, but did you say you meet up with your GF and later your wife - not the same person?? 🦄  @sindresorhus

**Comment by sindresorhus** [comment]
Same person
