### ISSUE TITLE
Why did you start splitting out the CLIs from your modules?

### ISSUE THREAD

**Issue by matiassingers** [sindresorhus/ama#17]
Just wondering what your thought process was behind the sudden change in style.

[`opn`](https://github.com/sindresorhus/opn) and [`opn-cli`](https://github.com/sindresorhus/opn-cli) etc.

----

Also let me know if you get by this part of the world again!

**Comment by sindresorhus** [comment]
I've mostly been doing all-in-one modules for convenience, but one day I realized they're actually different concepts. Some users found it confusing that a module has different behaviour when installed globally than when installed locally. Having CLI and API in one module also adds a lot of extra dependencies which bloats the package. And the readme get's kinda messy with both API and CLI docs.

I haven't really decided if I'm going to do this for every CLI+API module, but I've done it for my most dependent-upon ones. The [pageres](https://github.com/sindresorhus/pageres) readme before the CLI+API split was huge.

Happy to hear some thoughts on this.

**Comment by kentcdodds** [comment]
I suppose that now you can rely on npm@3 to do this for you (right?), but previously how did you manage an issue where the CLI might use a different version of the module than someone using it in code?

Not sure of a good example of one of your projects, but let's take Jade as an example. If I run it at the command line I would expect it to output the same as if I used Jade programatically, but if for some reason I had a version of the CLI installed that used a different version of Jade than the module I had installed in the project, then I might see different results.

You wouldn't have that problem by having them in the same module. Would you just recommend a dedupe in that case?

**Comment by sindresorhus** [comment]
Dedupe would work, though, your problem sounds more theoretical than anything. I've never used both CLI and API at once.

**Comment by kentcdodds** [comment]
Yeah, definitely theoretical :-)
