### ISSUE TITLE
What's your favorite t-shirt (that you own)? Selfie!

### ISSUE THREAD

**Issue by silvenon** [sindresorhus/ama#170]

**Comment by sindresorhus** [comment]
[![fullsizerender](https://cloud.githubusercontent.com/assets/170270/10847160/2ed3407e-7f47-11e5-9be0-f4ced74865a4.jpg)](https://instagram.com/p/9dr8-eoUDg/)

https://instagram.com/p/9dr8-eoUDg/

**Comment by silvenon** [comment]
:sparkles: :+1: :sparkles:
