### ISSUE TITLE
Who's face would you most rather throw cold spaghetti in?

### ISSUE THREAD

**Issue by silvenon** [sindresorhus/ama#174]
Cold spaghetti doesn't hurt, but sends a message. It really makes a person evaluate their life choices, "Why has this happened to me? What life decisions did I make which led me to having cold spaghetti thrown in my face?"

**Comment by sindresorhus** [comment]
[Donald Trump](http://images.latintimes.com/sites/latintimes.com/files/styles/pulse_embed_breakpoints_theme_lt_desktop_1x/public/2015/09/16/donald-trump-presidential-campaign-photos_20.jpg), but he would narcissistically find a way to benefit from it, so maybe not.
