### ISSUE TITLE
How do you get 8000 GH contributions

### ISSUE THREAD

**Issue by robbbz** [sindresorhus/ama#180]
:o::o::o:

**Comment by sindresorhus** [comment]
Work hard.

-

Though the GitHub contribution graph thing is pretty useless. Number of contributions are meaningless. It's like measuring lines of code. Quality > quantity, every time.

And it can be easily cheaten:

[<img width="723" alt="screen shot 2015-07-21 at 19 53 23" src="https://cloud.githubusercontent.com/assets/170270/8810971/33340f9a-2fe2-11e5-9e3a-c9a280bf3929.png">](https://github.com/addyosmani)

**Comment by bhaveshgohel** [comment]
Complete Picture. :)
https://twitter.com/ibhaveshgohel/status/601961421040029696

![addyosmani](https://cloud.githubusercontent.com/assets/5253753/8868525/1d21172c-31f7-11e5-9d05-49c79ce82f07.png)
