### ISSUE TITLE
What do you do with your pets when you travel?

### ISSUE THREAD

**Issue by jrolfs** [sindresorhus/ama#181]

**Comment by sindresorhus** [comment]
"My pets" (#2) are really the family pets which lives at my parents. My parents usually get me to watch them when they're away and on a few occacions they've brought the dog.

**Comment by jrolfs** [comment]
I figured that was probably the case, usually it's not too hard to find someone to watch Taco for shorter periods of time but I do aspire to do some more long-term travel at some point in my life and I wish I had that option! (My dad is allergic to cats)
![Taco](http://i.imgur.com/xNZqBiQ.jpg)

**Comment by sindresorhus** [comment]
Cute!
