### ISSUE TITLE
What is your favorite tool for remembering things?

### ISSUE THREAD

**Issue by LoicMahieu** [sindresorhus/ama#183]
Like bookmarks, discussions, tips...

**Comment by sindresorhus** [comment]
My brain, but it fails me a lot... I used to use Pinboard, but it ended up as a personal link wasteland. Now I mostly use Chrome bookmarks for stuff I want to keep, and email myself stuff I want to look at later. [MailToSelf](http://www.mailtoself.com/) is a useful iOS share extension for that kind of "workflow". I also use Evernote and Notes on OS X and iOS for braindumps and planning → #65 .

**Comment by dandv** [comment]
I've also been using Pinboard, and with a bit of effort to tag links as I bookmark them, it's proven *extremely* effective, [~8500 bookmarks](https://pinboard.in/u:dandv) later (despite the rather rudimentary search ranking).
