### ISSUE TITLE
Where would you live if you could live anywhere?

### ISSUE THREAD

**Issue by passy** [sindresorhus/ama#187]
Not very original, sorry, but genuinely curious because I'm sure you had something in mind when asking me this. :)

**Comment by sindresorhus** [comment]
Some earth-like planet in the [Andromeda Galaxy](https://en.wikipedia.org/wiki/Andromeda_Galaxy).

**Comment by icyflame** [comment]
Why? Why not another planet in the Milky Way galaxy itself?

**Comment by sindresorhus** [comment]
Same reason as why you would travel to another country when you could just travel around in your own country.
