### ISSUE TITLE
Was it really you who invented the term “ponyfill”?

### ISSUE THREAD

**Issue by tomekwi** [sindresorhus/ama#196]
I keep saying so, but I’m not 100% sure :)

https://github.com/studio-b12/array-from/pull/3#issuecomment-125665150
https://github.com/ljharb/array-includes/pull/1
https://github.com/medikoo/es6-symbol/pull/8
http://kikobeats.com/polyfill-ponyfill-and-prollyfill/
…and so on.

Good idea by the way :)

**Comment by sindresorhus** [comment]
Yes, I think I coined it when I made the [`object-assign`](https://github.com/sindresorhus/object-assign) ponyfill.

https://github.com/sindresorhus/slang-haven#ponyfill

I btw own http://ponyfill.com. Gonna do something with it at some point.

**Comment by dthree** [comment]
Set in stone:

http://svdictionary.com/words/ponyfill

:)

**Comment by Boycce** [comment]
:horse:

**Comment by sindresorhus** [comment]
https://ponyfill.com is now pointing at something :)
