### ISSUE TITLE
How many cats do you have?

### ISSUE THREAD

**Issue by passy** [sindresorhus/ama#2]

**Comment by sindresorhus** [comment]
I have two cats and one dog.

## Dofle

![image](https://cloud.githubusercontent.com/assets/170270/8454104/13c97c4a-1ffb-11e5-99e2-79884eebb5db.png)

## Tussi

![image](https://cloud.githubusercontent.com/assets/170270/8454143/680e2936-1ffb-11e5-93cd-780355ab00e2.png)


## Kira

![image](https://cloud.githubusercontent.com/assets/170270/8454173/b4a789d6-1ffb-11e5-8922-709288684e6f.png)



-

## Bonus - Feeding time

![image](https://cloud.githubusercontent.com/assets/170270/8454131/51b97cbc-1ffb-11e5-8458-4ab8fb0c58ac.png)

**Comment by arthurvr** [comment]
I'm gonna love this repo.

**Comment by passy** [comment]
I'm very pleased with this answer. Thanks.

**Comment by passy** [comment]
Oh, and you obviously can't pick favorites, but I can. Dofle is a winner.
