### ISSUE TITLE
Not really a question, but this is how I always read your username, how does this image make you feel?

### ISSUE THREAD

**Issue by thejameskyle** [sindresorhus/ama#205]
![sindresaurus](https://cloud.githubusercontent.com/assets/952783/9118183/973f02f4-3c23-11e5-94a7-f9f65a69e0d4.png)

**Comment by RichardLitt** [comment]
+1

**Comment by stoeffel** [comment]
:laughing: this is awesome. I don't even care what the answer will be, I have to add this to [awesome-ama-answers](https://github.com/stoeffel/awesome-ama-answers).

**Comment by thejameskyle** [comment]
I suspense of waiting for a response is killing me.

**Comment by sindresorhus** [comment]
Marvelous.

New twitter header pic: https://twitter.com/sindresorhus

![sindersaurus](https://cloud.githubusercontent.com/assets/170270/9132202/f7345f08-3d1b-11e5-8fd0-878d0f290d58.jpg)

-

There actually is a dinosaur pretty close: https://en.wikipedia.org/wiki/Chindesaurus

**Comment by sindresorhus** [comment]
@thejameskyle Do you have the dinosaur with transparent background?

**Comment by thejameskyle** [comment]
Kinda, not very well

![sindresaurus-transparent](https://cloud.githubusercontent.com/assets/952783/9141924/33528e04-3cf1-11e5-925a-d3c690f1d76e.png)

**Comment by patik** [comment]
This is precisely why I asked #51 but I was afraid to mention it.

**Comment by diessica** [comment]
ROFL. Loved it.

**Comment by harshasrinivas** [comment]
Haha. Even I felt the same way :sweat_smile:

**Comment by ali** [comment]
:+1:

**Comment by HugoGiraudel** [comment]
Best issue on this whole repo. Gold.

**Comment by mzmousa** [comment]
:joy:
