### ISSUE TITLE
How often do you check email?

### ISSUE THREAD

**Issue by icyflame** [sindresorhus/ama#207]
- Do you check email right after waking up?
- If not, when is the first time of the day when you check email?
- After that, how frequently do you check email when you are not travelling?
- In the other case, how frequently do you check email when you are travelling?

**Comment by sindresorhus** [comment]
Usually when I wake up and then once in a while throughout the day when I have some dead time. Maybe 5-20 times a day. I try not to check it when working though, as I prefer to focus on one task at the time. When traveling it's a lot more sporadic. It can be none or 10 times.

-

Relevant: https://github.com/sindresorhus/ama/issues/201.
