### ISSUE TITLE
Have you ever participated in a CTF contest?

### ISSUE THREAD

**Issue by aspyatkin** [sindresorhus/ama#21]
Hey Sindre!
Have you ever participated in CTF (Capture The Flag) contest?

**Comment by sindresorhus** [comment]
Once. I did the [Stripe CTF 2.0](https://stripe.com/blog/capture-the-flag-20). It was fun and really well made.

Lots of good resources for doing a CTF contest here:
https://github.com/apsdehal/awesome-ctf

The following write-ups are always a fun read:
https://github.com/apsdehal/awesome-ctf#writeups-collections
