### ISSUE TITLE
Do you use any tool to find whoever is using your modules?

### ISSUE THREAD

**Issue by stevemao** [sindresorhus/ama#214]
Or just link to your module.

**Comment by stevemao** [comment]
Or just link to your module

**Comment by sindresorhus** [comment]
I don't care if anyone are using my modules. I make them for my own needs.
Though if I did, I would look a `dependents` on npm: https://www.npmjs.com/browse/depended/chalk

**Comment by stevemao** [comment]
Reason I ask is I see you always comment or star on the project that just references your module without pinging you.
