### ISSUE TITLE
Where do you host your private Git repos?

### ISSUE THREAD

**Issue by robbbz** [sindresorhus/ama#219]

**Comment by sindresorhus** [comment]
I only have one hosted private repo and it's on GitHub. Unfinished open source projects are only on my computer, but backed up with Time Machine and [BackBlaze](https://www.backblaze.com/). If I ever need to host more than 5 private repos (which is what the GitHub Micro plan includes), I would probably use BitBucket, but I wouldn't enjoy it, as I find its interface highly unintutive and cluttered.
