### ISSUE TITLE
Which photographers do you admire

### ISSUE THREAD

**Issue by steverydz** [sindresorhus/ama#224]
I see from reading this that you have an interest in photography. I was curious if there were any photographers you admire? Mine would be Henri Cartier-Bresson, Robert Frank, Garry Winogrand, Elliott Erwitt and Joel Meyerowitz.

**Comment by sindresorhus** [comment]
None, really... I wish I had a good answer for this, but I'm more into the technical aspects of photography than the cultural ones. I do like the style of [Joey L.](http://www.joeyl.com/overview/category/quick-portfolio) photographs, though.
