### ISSUE TITLE
What software license do you prefer and why?

### ISSUE THREAD

**Issue by eush77** [sindresorhus/ama#226]

**Comment by sindresorhus** [comment]
I prefer the [MIT License](https://en.wikipedia.org/wiki/MIT_License) as it's simple to understand, the most common one, so most people know how it works, and it's very permissive.

**Comment by es128** [comment]
Have you looked at [ISC](https://en.m.wikipedia.org/wiki/ISC_license)? I've only known of it since it became the default for `npm init`, and apparently it is like the refactored smaller MIT (text removed that was found to be not legally necessary)

**Comment by sindresorhus** [comment]
Yes, but I prefer MIT since it's more well known, hence easier for users. I might switch at some point in the future though.
