### ISSUE TITLE
What is your preferred editor?

### ISSUE THREAD

**Issue by kdelmonte** [sindresorhus/ama#227]
I think I know the answer is Sublime but I would still like your opinion on the following:

- Atom
- Brackets
- Visual Studio Code

Why Sublime?

**Comment by sindresorhus** [comment]
I use [Sublime](http://www.sublimetext.com). It's fast, lightweight, and extendable, but more importantly, I'm extremely efficient with it, after having used it for years and set it up exactly how I want it. An editor is a big investment and not something I would change lightly.

[Atom](https://atom.io) will probably be better than Sublime in a few years. Atom still struggles with performance, but the benefits of running in a browser should not be overlooked. So much potential there for innovating what an editor is. The [merge-conflict](https://github.com/smashwilson/merge-conflicts) plugin is a good example of that. The Sublime plugin API in constrast is rather limited. There's also the unfortunate reality that Sublime is closed-source and the development is between sporadic and none. I'm not switching over to Atom in the short-term, but if nothing improves with Sublime, I'll do it at some point.

I really liked Brackets when it was released. It had great potential, but it never got polished enough for me to switch. Now it seems the focus is too much towards designing websites and Atom is a much better fit for me.

I haven't really looked into Visual Studio Code. It's probably ok, but I would never use it personally as it's a Microsoft product.

**Comment by tkrotoff** [comment]
> I would never use it as it's a Microsoft product

Such a childish/stupid reason

**Comment by serapath** [comment]
I like the reason :-)
Visual Studio is awesome, but I think basic tools should be open source
http://blog.atom.io/2014/05/06/atom-is-now-open-source.html

**Comment by sindresorhus** [comment]
@tkrotoff The only childishness here is your trolling. Not wanting to use a product because it comes from a company I think consistency produces junk is a personal choice I'm free to make.

**Comment by svipben** [comment]
Hi, @sindresorhus I saw you’re using TypeScript in several projects. Still developing with Sublime or moved to VS Code? You may wonder why I’m asking, I’m very curious how you develop without proper autocomplete and all stuff VS Code gives you to make your life easier, or maybe I’m wrong.

Thanks for the info!

**Comment by sindresorhus** [comment]
I'm still using Sublime. I have been trying out VS Code with some TypeScript projects, and it's a good experience in general, but I'm not ready to switch. While VS Code is reasonable fast and has a lot of nice conveniences, I still experience slowdowns at times, and I also feel that it's not very well polished and the UX could use more work. Thanks to the [language server protocol](https://github.com/Microsoft/language-server-protocol), TypeScript development with Sublime is actually a pretty good experience when you install [the official TypeScript plugin](https://github.com/Microsoft/TypeScript-Sublime-Plugin). Then you get autocompletion, inline docs, refactoring, etc.
