### ISSUE TITLE
Do you ever unstar repositories on GitHub?

### ISSUE THREAD

**Issue by eush77** [sindresorhus/ama#228]
And if you do, in what circumstances?

**Comment by sindresorhus** [comment]
I used to go through my list of starred repos once in a while and unstar the ones that didn't interest me anymore, but the list is so big now I've given up doing that.

**Comment by lakshay313** [comment]
https://github.com/lakshay313/github-unstar-repo

Ruby script to remove starred repos from your profile using Personal Access Token
