### ISSUE TITLE
Do you think it's a good time to become a front-end developer?

### ISSUE THREAD

**Issue by vkuri** [sindresorhus/ama#23]

**Comment by sindresorhus** [comment]
There's never been a better time to be a front-end developer! Demands are huge. Don't fall for the constant framework hype. Find your niche, eg. layout/DOM/etc performance tuning (which IMHO an undervalued skill). Pick a framework, learn it inside-out and build an actual product with it.

My current favorite is React. It's a good blend of great performance while still being non-magic enough. I've heard the [Flux architecture](https://github.com/facebook/flux) is great, but I haven't tried it.

**Comment by ccnokes** [comment]
What would you say your niche is? 

Or are unicorns simultaneously in all niches??!?

**Comment by sindresorhus** [comment]
My current niche is making useful modules and creating developer tools. Unfortunately that isn't very monetizable...

**Comment by iamstarkov** [comment]
> My current niche is making useful modules and creating developer tools. Unfortunately that isn't very monetizable...

have you seen @gaearon [crowdfunding campaign to fund redux and redux devtools](https://www.patreon.com/reactdx?ty=h) development?

**Comment by sindresorhus** [comment]
@iamstarkov Yup. I know there's a few, but they are the extreme outliers. Mostly it doesn't work. I want to try that at some point though, but it requires a focused product with a clearly defined goal.
