### ISSUE TITLE
Feed reader recommendations?

### ISSUE THREAD

**Issue by corvannoorloos** [sindresorhus/ama#231]
Could you recommend any RSS feed readers similar in design to your [GitHub Notifier](https://github.com/sindresorhus/github-notifier-chrome) Chrome extension? (an extension I simply use more than often, and is very much appreciated!)

**Comment by sindresorhus** [comment]
I'm happy with [Digg Reader](https://digg.com/reader/). I've also heard good things about [Feedbin](https://feedbin.com).
