### ISSUE TITLE
Do you believe in extraterrestrial life?

### ISSUE THREAD

**Issue by robbbz** [sindresorhus/ama#235]

**Comment by sindresorhus** [comment]
Yes. The universe is singularly gargantuan I'm certain there's some kind of extraterrestrial life out there. However, it's definitely not the Hollywood kind of aliens.

Extraterrestrial life might even be around us and we're just too primitive to comprehend their existence:

> There’s a worm in the street, you walk by it. Does the worm know that you think you’re smart? The worm has no concept of your smarts. Because you’re that much smarter than the worm. So the worm has no idea that something smart is walking by it. Which makes me wonder whether we have any concept—if a super species walked by us. Maybe they’re uninterested in us because we’re too stupid for them to even imagine having a conversation. You don’t walk by worms and go “Gee I wonder what the worm is thinking.” This is just not a thought that you have! So one of the best pieces of evidence for why we haven’t been visited by aliens is that they have actually observed us, and concluded there is no intelligent sign of life on earth. — Neil deGrasse Tyson

-

[10 Exoplanets That Could Host Alien Life.](http://www.space.com/18790-habitable-exoplanets-catalog-photos.html)

**Comment by tomekwi** [comment]
:+1: :+1: :+1: Thanks for the mind-opening citation!

**Comment by robbbz** [comment]
Thanks for your answer!

**Comment by CWSpear** [comment]
One of the must intriguing reads I've ever had on the subject that I think is *very* relevant here: http://waitbutwhy.com/2014/05/fermi-paradox.html

**Comment by Qix-** [comment]
@CWSpear that article is the ultimatum and will be for the next decade I'm sure. Great find, thanks.
