### ISSUE TITLE
How do you pronounce AVA?

### ISSUE THREAD

**Issue by kentcdodds** [sindresorhus/ama#237]
As in https://github.com/sindresorhus/ava

**Comment by kevva** [comment]
`æ-va`

**Comment by towry** [comment]
a.v.a

**Comment by kentcdodds** [comment]
That's good enough for me. Thanks!

**Comment by kevva** [comment]
Should probably let @sindresorhus answer his own ama though :)!

**Comment by kentcdodds** [comment]
Makes sense. I just thought I'd save @sindresorhus some time :-)

**Comment by sindresorhus** [comment]
Pronounced `/ˈeɪvə/` ay-və. [Audio](https://github.com/sindresorhus/ava/blob/master/media/pronunciation.m4a?raw=true).

**Comment by kentcdodds** [comment]
Nice. Couldn't have asked for a better answer!

**Comment by kentcdodds** [comment]
Was going to add a PR to add that to the README [but](https://github.com/sindresorhus/ava#how-is-the-name-written-and-pronounced)... :+1:
