### ISSUE TITLE
How do you set up new projects?

### ISSUE THREAD

**Issue by kentcdodds** [sindresorhus/ama#238]
There's quite a bit of boilerplate when creating a new library (`README.md` with badges etc., `CONTRIBUTING.md`, `CODE_OF_CONDUCT.md`, `LICENSE`, `.gitignore`, `.npmignore`, `.editorconfig` etc., etc., etc.). Do you have any tool that helps getting passed this boilerplate?

**Comment by es128** [comment]
Dupe of #86 and #194

**Comment by kentcdodds** [comment]
Sorry, I searched for the wrong terms I guess.
