### ISSUE TITLE
What are you doing this weekend?

### ISSUE THREAD

**Issue by passy** [sindresorhus/ama#240]
:sunny:

**Comment by sindresorhus** [comment]
Just tranquilizing in coffee shops hacking on stuff. Gf is abroad, which means I have a lot of free time. Next week I'm traveling to Cambodia.

**Comment by sindresorhus** [comment]
And you?

**Comment by passy** [comment]
Totally didn't have to check on a map where Cambodia is ... :eyes: Sounds awesome, enjoy!

I'm going to a Halloween party, meet some friends over coffee and will do some hacking, too. I will use the Sunday to refuel my introversion by not speaking to anyone. Two days of conference have burnt through all my social energy.

**Comment by sindresorhus** [comment]
> I'm going to a Halloween party

Oh, I didn't even realize it's Halloween now. Have fun! I hope this is your costume http://bfy.tw/2YpI.

> I will use the Sunday to refuel my introversion by not speaking to anyone.

That *is* important!

**Comment by dthree** [comment]
:+1: on the costume.
