### ISSUE TITLE
Old screenshot of your GitHub profile

### ISSUE THREAD

**Issue by harshasrinivas** [sindresorhus/ama#241]
Do you have an old screenshot of your Github [profile page](https://github.com/sindresorhus) (probably a couple of years back or so)?

**Comment by sindresorhus** [comment]
From 2012-07-13. I had just started contributing to open source, mainly on [TodoMVC](http://todomvc.com) and [Yeoman](http://yeoman.io).

![sindresorhus-github-profile-2012-07-13](https://cloud.githubusercontent.com/assets/170270/10126368/f4dde2c0-65ba-11e5-85a0-0c17e7162264.png)

**Comment by harshasrinivas** [comment]
:+1:
