### ISSUE TITLE
Your best project?

### ISSUE THREAD

**Issue by harshasrinivas** [sindresorhus/ama#242]
Which one of your projects do you consider to be the best? Why?
Considering factors like, time taken to complete it, your level of experience, etc.?

**Comment by gion** [comment]
I'm also interested in your answer to this question! :+1:

**Comment by iBcker** [comment]
@kelby look look

**Comment by sindresorhus** [comment]
[AVA](https://github.com/sindresorhus/ava) is the best and most ambitious project I've started. Creating a test runner is surprisingly hard. Not to mention an innovative and concurrent one. Very much an arduous journey. Luckily I have some awesome team members, @vdemedes & @jamestalmage. When something suddenly grows really fast, it's hard to manage issues/PRs, support, keep a clean codebase, prevent feature creep, ensure stability (extra important for a test runner), balancing readable code vs. performance, and not burn out. Making the project welcoming to anyone has been a big focus. We've worked hard on making the docs good, [translations](https://github.com/sindresorhus/ava-docs) (huge thanks to our incredible translators!), added a [code of conduct](https://github.com/sindresorhus/ava/blob/master/code-of-conduct.md), a comprehensive [contribution guide](https://github.com/sindresorhus/ava/blob/master/contributing.md), and ["beginner friendly"](https://github.com/sindresorhus/ava/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+for+beginner%22) labeled issues, and mentoring beginners. We're also strict about being nice to anyone, regardless of how dumb a question might seem or how trollish a user might be (the utter niceness part actually annoys them, which is a bonus 😝).

Happy to answer more specific follow-up questions if any.

**Comment by kentcdodds** [comment]
I can say you're doing an awesome job!
