### ISSUE TITLE
What was your longest coding streak?

### ISSUE THREAD

**Issue by harshasrinivas** [sindresorhus/ama#243]
And when was it?

**Comment by SamVerschueren** [comment]
You can see it on his Github page https://github.com/sindresorhus. But he doesn't care https://github.com/sindresorhus/ama/issues/208.

**Comment by harshasrinivas** [comment]
Yeah, I saw that already. But I didn't mean the number of days. :smile: 
I wanted to know the maximum number of hours for which he has been coding, at a single stretch.

**Comment by es128** [comment]
The gh heatmap also doesn't show prior years. Sindre's daily streak has been higher than that before.

**Comment by sindresorhus** [comment]
43 hours. Some years back I was working on my first iPhone app and had never touched Objective-C before (or even C), so I learned while doing, failing a lot. I remember it being super exciting, though, and I just couldn't close the lid on my laptop. It's interesting how you lose the sense of sleepiness when listening to dubstep and concentrating intensely in front of a bright screen. I slept for more than 16 hours afterwards.

**Comment by harshasrinivas** [comment]
Cool. Thanks!

**Comment by kevva** [comment]
43 hours though...

**Comment by harshasrinivas** [comment]
Lol. That was insane.
