### ISSUE TITLE
What's in your private repository?

### ISSUE THREAD

**Issue by RichardLitt** [sindresorhus/ama#244]
Logistics? Notes? A super-cool project?

**Comment by sindresorhus** [comment]
It was [AVA](https://github.com/sindresorhus/ava), which I recently open sourced. I have some super-cool projects in mind, but only brain dumps in Notes.app for now.

**Comment by RichardLitt** [comment]
:+1: Cool! How do you like Notes.app? Why do you use that?

**Comment by sindresorhus** [comment]
Notes.app I good for short notes / braindumps as it's quick to add a note and have it synced to all my devices. It was not very good at organization of notes, however, that changed recently with OS X 10.11 and iOS 9. The Notes.app is much more powerful now. I wish it had Markdown support and implicit tags through `#tag`, but it works well enough for my simple needs. I used to use Evernote for larger notes, but it's always been crappy, and is just getting more so these days.

**Comment by steverydz** [comment]
Have you tried [Simplenote](http://simplenote.com/)? I was using Notes.app, but when I briefly switched to Android it wasn't much use. 

Simplenote is cross platform and a bit more powerful than Notes.app, but not quite Evernote. It's tagging is really good, it's fast to open, has a web interface and syncs really well.

**Comment by sindresorhus** [comment]
> Have you tried Simplenote?

Yes, tried it a year ago. Was meh. Syncing was unreliable and it didn't really have any enticing features. From what I can remember I also couldn't find a good OS X app for it.

**Comment by steverydz** [comment]
I think it was around then it was taken over by Automattic and they've put
a lot of work into it. There's a good app for all platforms now. You're
right, there's nothing super exciting about it, just a bit better (IMO)
than Notes.app. I've found the syncing in Notes.app a lot less reliable
personally, which is another reason I started using it.

**Comment by sindresorhus** [comment]
Notes.app got a lot better with iOS 9 and OS X 10.11, though, so I'm not switching to anything new at this point. Syncing now uses iCloud and is almost instant.

**Comment by hoodsy** [comment]
It would be awesome to have a Markdown driven notes app that synced across devices 😍

**Comment by sapegin** [comment]
@hoodsy You mean [Bear](http://www.bear-writer.com/)? ;-)
