### ISSUE TITLE
In hindsight, what advice do you wish someone had given you at age 20?

### ISSUE THREAD

**Issue by Widdershin** [sindresorhus/ama#246]

**Comment by sindresorhus** [comment]
Be spontaneous. Be crazy. Do what other people say you can’t. Grow up, not dull. Money is just paper. Question all the things. Optimize for happiness. Don't be afraid of asking people for stuff. Travel. Experience. Simplify everything, including your life. Love.

**Comment by sindresorhus** [comment]
...and buy lots of Apple stock and invest in Facebook 😝

**Comment by es128** [comment]
> ...and buy lots of Apple stock and invest in Facebook 😝

Despite money being just paper?

**Comment by sindresorhus** [comment]
Notice the 😝

**Comment by es128** [comment]
So you would not invest based on tips delivered from the future? 

Or are you just saying it's unimportant/irrelevant to your answer - a joke based on a clichè?

Just curious.

**Comment by sindresorhus** [comment]
> Or are you just saying it's unimportant/irrelevant to your answer - a joke based on a clichè?

Yes
