### ISSUE TITLE
How was your weekend?

### ISSUE THREAD

**Issue by robbbz** [sindresorhus/ama#249]

**Comment by sindresorhus** [comment]
Excellent. Quiet weekend as gf was working. I finally had some *me* time, which I wisely spent in a front of a screen. Cleaned up my computer and notes. Answered a bunch of emails. Did a lot of coding. Planned some new projects. Got my browser tab count down quite a bit. Read some saved Instapaper articles. GitHub stuff. Walked around in the rain. Visited some coffee shops. Watched [Tomorrowland](http://www.imdb.com/title/tt1964418/) and some episodes of [Rick and Morty](http://www.imdb.com/title/tt2861424/). Ordered in some indian butter chicken and mango lassi.
