### ISSUE TITLE
Why don't you have a website?

### ISSUE THREAD

**Issue by icyflame** [sindresorhus/ama#25]

**Comment by sindresorhus** [comment]
I'm too lazy. Most of my things are on GitHub anyways, so I just redirect http://sindresorhus.com there.

I did make a super simple one at some point: http://sindresorhus.com/hi/ ([on GitHub of course](https://github.com/sindresorhus/hi)).

What I *do* want is a blog. Just waiting on https://medium.com to support custom domains.

**Comment by danieldunderfelt** [comment]
Setting up a github-pages site with Jekyll and your own domain is like 5 minutes though. Give it a try!

**Comment by sindresorhus** [comment]
It's not a technical laziness. I'm just too lazy to decide on what to put there and make the content.

**Comment by ruffle1986** [comment]
> I'm too lazy.

:D

**Comment by hackerkid** [comment]
@sindresorhus  Looks like the wait is over. https://medium.com/the-story/move-your-domain-to-medium-21fd74abbbe6

**Comment by sindresorhus** [comment]
I now have a blog → https://blog.sindresorhus.com

**Comment by icyflame** [comment]
At long last! Thanks, @sindresorhus !

**Comment by sindresorhus** [comment]
Ah yes, only 8 years late.
