### ISSUE TITLE
How do you organize repos/projects on your machine?

### ISSUE THREAD

**Issue by johnotander** [sindresorhus/ama#251]
I'd be interested to hear how your organize your numerous repos/projects on your machine. I.e., do you keep a flat directory structure with everything under `dev/` or do you maintain categories like?:

```
code/
  yo/
  util/
  gulp-plugins/
  broccoli-plugins/
  etc...
```

Or, perhaps some other type of organization entirely?

Thanks : )

**Comment by sindresorhus** [comment]
Everything goes flat into `~/dev` and `~/dev/forks`. I use ZSH auto-complete and globbing, so organizing into categories wouldn't be of much use.

**Comment by serapath** [comment]
+1 very interesting.
Maybe the broader question would be, how do you namespace your life and manage your focus on what's important next? :-)

**Comment by arnellebalane** [comment]
Hmmm interesting, I guess I'll have to try that kind of directory structure :) Thanks for sharing!

**Comment by sindresorhus** [comment]
@serapath Can you open a new question for that?
