### ISSUE TITLE
What's your ES2015 Module Loader?

### ISSUE THREAD

**Issue by backspaces** [sindresorhus/ama#252]

**Comment by sindresorhus** [comment]
[Babel](https://babeljs.io/) transpilation to CommonJS `require`.

**Comment by backspaces** [comment]
But, but, but ... how!? JSPM? es6-module-loader? The plot thickens!

Looking at Babel: https://babeljs.io/docs/learn-es2015/ & https://babeljs.io/docs/usage/modules/
.. it points to: https://github.com/ModuleLoader/es6-module-loader
.. which suggests you use:
  <script src="browser.js"></script>
  <script src="es6-module-loader-dev.js"></script>
.. and then either
<script>
  System.import('mymodule')...etc
</script>
.. or
<script type="module">
  import { q } from 'mymodule' .. etc
</script>

**Comment by sindresorhus** [comment]
Whatever you already do with ES5 CommonJS `require` style code. In Node.js, just run it directly. In the browser, use Browserify or Webpack to bundle it. Haven't tried JSPM, but it's probably a good choice too, especially in favor of AMD for dynamic module loading.
