### ISSUE TITLE
How do you discover new interesting open source projects?

### ISSUE THREAD

**Issue by es128** [sindresorhus/ama#254]
I learn about a lot of stuff just by taking notice in my GitHub feed of what you're starring. For instance, that's how I learned about [6to5](https://github.com/babel/babel) when it was only a day or two old, and just now about [volkswagen](https://github.com/auchenberg/volkswagen), which is hilarious, but in a pre-viral level of popularity. 

How do you find out these things exist?

**Comment by sindresorhus** [comment]
People I [follow on Twitter](https://twitter.com/sindresorhus/following), GitHub newsfeed, [Changelog Nightly](https://changelog.com/nightly/), [Node Weekly](http://nodeweekly.com), [npm addict](https://npmaddict.com), and [browsing package.json dependencies](https://github.com/octo-linker/chrome-extension) of projects.
