### ISSUE TITLE
What is your opinion on the AMP project?

### ISSUE THREAD

**Issue by claudiopro** [sindresorhus/ama#262]

**Comment by hallas** [comment]
:+1:

**Comment by sindresorhus** [comment]
I'm pretty amped up about it! Mostly towards reading on the web. The sad reality is that most news sites today are heavy, slow, badly coded, using intrusive ads, and generally just a frustrating experience. I always use the Safari Reader for those reasons. I just want clean, readable articles, immediately. I truly hope AMP succeeds in making a faster and better reading experience on the web.

**Comment by claudiopro** [comment]
@sindresorhus cool, thank you :smile:
