### ISSUE TITLE
What do you think of creating a script to post a question in all existing AMA repos?

### ISSUE THREAD

**Issue by HugoGiraudel** [sindresorhus/ama#265]
I was thinking of building something like this as a fun side project. What do you think of the idea?

**Comment by iamstarkov** [comment]
I was also thinking about the same script

**Comment by sindresorhus** [comment]
Not a big fan. That's very impersonal. I ask questions because I'm genuinly curious, not just for the sake of asking a question.

**Comment by dthree** [comment]
:+1: - doing that would sort of ruin the whole point of an AMA, IMHO.
