### ISSUE TITLE
What are your favourite Sublime Text plugins?

### ISSUE THREAD

**Issue by steverydz** [sindresorhus/ama#267]
Sorry if you've already answered this but I couldn't find it by searching the questions. What are your favourite Sublime Text plugins? Are there any you couldn't live without?

**Comment by sindresorhus** [comment]
- [Theme - Spacegray](https://github.com/kkga/spacegray)
- [Oceanic Next Color Scheme](https://github.com/voronianski/oceanic-next-color-scheme)
- [JavaScriptNext - ES6 Syntax](https://github.com/Benvie/JavaScriptNext.tmLanguage)
- [Local History](https://github.com/vishr/local-history) *(Has saved me many times!)*
- [Modific](https://github.com/gornostal/Modific)
- [SublimeLinter-contrib-xo](https://github.com/sindresorhus/SublimeLinter-contrib-xo)
- [Markdown Preview](https://github.com/revolunet/sublimetext-markdown-preview)
- [EditorConfig](https://github.com/sindresorhus/editorconfig-sublime)
- [Focus](https://github.com/sindresorhus/focus)
- [Dotfiles Syntax Highlighting](https://github.com/mattbanks/dotfiles-syntax-highlighting-st2)
- [Missing Palette Commands](https://github.com/fjl/Sublime-Missing-Palette-Commands)
