### ISSUE TITLE
What is your GitHub password?

### ISSUE THREAD

**Issue by mahanmarwat** [sindresorhus/ama#268]
Your GitHub, Gmail etc...

**Comment by sindresorhus** [comment]
A few years ago I used the same password `tussidoflekira##3456` (which are the names of my pets) for all of those services. Not going to share my current passwords of course, which are unique, 40 characters, and kept safely in 1Password.

**Comment by ruffle1986** [comment]
Why not 50 characters? :)

**Comment by sindresorhus** [comment]
Some websites didn't accept longer than 40, so I just went with that. 40 is more than long enough anyways.

**Comment by ruffle1986** [comment]
Ye I hear you, I was just trolling, sorry :) The best when sites accept
only 4 numbers, for example my mobile provider. :D

**Comment by icyflame** [comment]
@sindresorhus does it ver bother you that without The 1Password app / browser extension you wouldn't be able to login to any service at all?

**Comment by sindresorhus** [comment]
Not really. I've memorized my Google and Apple password.
