### ISSUE TITLE
Do you write release notes by hand or use a tool?

### ISSUE THREAD

**Issue by dylang** [sindresorhus/ama#269]
It seems like it would take a long time to write release notes [this nice](https://github.com/sindresorhus/got/releases/tag/v5.0.0) for every one of your projects, even if you limit to major bumps. How do you do it quickly?

**Comment by sindresorhus** [comment]
For popular or larger projects, I write the release notes by hand, as there's no replacement for the human touch. For the rest, I simply don't. I keep a clean commit history, so it's easy enough to just skim the few commits. The beauty of small focused modules is that most of them never change, and if they do, it's one or two commits between releases.
