### ISSUE TITLE
Promise, Q or Bluebird

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/ama#273]
What is your opinion on libraries like Q or Bluebird? When would you decide to use one instead of a ponyfill?

**Comment by TrySound** [comment]
@SamVerschueren Ponyfill [pinkie-promise](https://github.com/floatdrop/pinkie-promise). See [del](https://github.com/sindresorhus/del) and other modules

**Comment by SamVerschueren** [comment]
I know, but he also has modules that use a library. I think AVA is one of them? I want his opinion on those.

**Comment by sindresorhus** [comment]
Between Q and Bluebird, I prefer Bluebird, as it's faster and I think it has a much better API. The native Promise (with a ponyfill for older Node.js versions) is good enough for me in most cases, though. I would use Bluebird for larger projects, like apps, [AVA](https://github.com/sindresorhus/ava), etc, where the extra functionality becomes useful.

**Comment by SamVerschueren** [comment]
Thanks!
