### ISSUE TITLE
How do you avoid burnout?

### ISSUE THREAD

**Issue by RichardLitt** [sindresorhus/ama#274]
I'm curious!

_For some reason, the title came up in Autocorrect, so I may have asked this before somewhere. I have no idea when I did. Interesting._

**Comment by sindresorhus** [comment]
I don't. I embrace it. Burnout is unavoidable when you're active in open source. Knowing how to handle it is key. Once in a while I get burned out by all the issues, negativity, demanding user, drama, workload, etc, and I take a couple of weeks break from GitHub. Being away for a little while helps me process it all and refill my batteries.
