### ISSUE TITLE
Do you like chicken?

### ISSUE THREAD

**Issue by sotojuan** [sindresorhus/ama#277]
If so, what kind is your favorite? 🐥

**Comment by sindresorhus** [comment]
Yes! My favorites dishes with chicken are [Gai Pad Med Ma Muang Him Ma Paan](http://www.thaifoodmaster.com/thai_food_recipes/thai_main_dish_recipes/460) (Stir-Fried Chicken with Cashew Nuts) and [Tom Kha Gai](http://www.bonappetit.com/recipe/tom-kha-gai-chicken-coconut-soup) (Chicken Coconut Soup).
