### ISSUE TITLE
How do you feel when rejecting a PR?

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/ama#278]
When someone does the effort to do a PR, I really feel sorry when it's no good and I have to tell the person I am not merging the PR because of some reasons.

**Comment by sindresorhus** [comment]
I feel really bad, but in the end, I'm the one having to maintain that code, so it's the best outcome. I feel even worse when I have to reject a good PR. Sometimes it just doesn't fit into the purpose of the module. That's also why, as a contributor, you should open an issue discussing it beforehand if it's non-trivial.

**Comment by SamVerschueren** [comment]
Absolutely agree with you. Thanks for the answer :+1: !
