### ISSUE TITLE
When would you travel back to Chiang Mai?

### ISSUE THREAD

**Issue by armno** [sindresorhus/ama#279]
it's starting cold season and i'm pretty sure you'll love it here! :sweat_smile:

**Comment by sindresorhus** [comment]
I really enjoyed Chiang Mai, so will definitely come back. Won't be until sometime next year, though. I'm in Cambodia now, then going to Bangkok, and then to Norway for Christmas. Will let you know whenever I travel there again.

**Comment by armno** [comment]
awesome! happy traveling :santa: !
