### ISSUE TITLE
What is your dev enviroment?

### ISSUE THREAD

**Issue by AbeEstrada** [sindresorhus/ama#28]
What's your hardware and software that you use for coding?

**Comment by sindresorhus** [comment]
I use a 15" MacBook Pro. It's the best computer I've ever had.

My most used apps are Terminal (with [TotalTerminal](http://totalterminal.binaryage.com/)), Chrome, [Sublime Text](http://www.sublimetext.com/), [Dash](https://kapeli.com/dash), and [Alfred](http://www.alfredapp.com/).

In Terminal, I use [ZSH](https://en.wikipedia.org/wiki/Z_shell) with my own terminal prompt [Pure](https://github.com/sindresorhus/pure), the [Tomorrow Night Eighties](https://github.com/chriskempson/tomorrow-theme) theme with the [Droid Sans Mono](http://www.google.com/webfonts/specimen/Droid+Sans+Mono) font (15pt).

In Sublime Text, I use the [Spacegray](http://kkga.github.io/spacegray/) theme, the [Oceanic Next](https://github.com/voronianski/oceanic-next-color-scheme) color scheme, with the above font.

-

Anything I'm missing?

**Comment by jaan** [comment]
:+1

**Comment by jontron** [comment]
What do you use for developing locally on your machine? Mamp or something like Docker + Vagrant?

**Comment by sindresorhus** [comment]
I just use my local system, [`n`](https://github.com/tj/n) for Node.js version management and the app in git, and usually deploy to Heroku.

**Comment by iamstarkov** [comment]
would you mind to show your `zsh_stats` log? 🐱

**Comment by sindresorhus** [comment]
```
149  14.9149%   c
97   9.70971%   nv
70   7.00701%   nh
42   4.2042%    xo
39   3.9039%    npm
39   3.9039%    nis
30   3.003%     nid
30   3.003%     ags
29   2.9029%    nl
27   2.7027%    gc
25   2.5025%    node
24   2.4024%    g
19   1.9019%    s
16   1.6016%    nig
16   1.6016%    ni
15   1.5015%    echo
12   1.2012%    pageres
12   1.2012%    gcl
```

Not very useful though as most of those are ZSH alias shortcuts.

**Comment by shuvalov-anton** [comment]
@sindresorhus can you expand your aliases? I just wrote cute bash one-lining for you :D
`zsh_stats | awk '{gsub(/ +|\t+/," ")}1' | cut -d ' ' -f 5 | while read -r i; do alias "$i" || echo "$i"; done`

**Comment by sindresorhus** [comment]
```
c=cd
nv=latest-version
nh='npm docs'
xo
npm
nis='npm install --save'
nid='npm install --save-dev'
ags='ag --ignore-case --literal'
nl='npm link --force'
gc
node
g=git
s
nig='npm install -g'
ni='npm install'
echo
pageres
gcl=clonecd
```

**Comment by sindresorhus** [comment]
Modified it slightly to show more info:

```sh
fc -l 1 | awk '{CMD[$2]++;count++;}END { for (a in CMD)print CMD[a] " " CMD[a]/count*100 "% " a;}' | grep -v "./" | column -c3 -s " " -t | sort -nr | command nl | head -n20 | awk '{gsub(/ +|\t+/," ")}1' | cut -d ' ' -f 5 | while read -r i; do alias "$i" || which "$i" || echo "$i"; done
```

```sh
c=cd
nv=latest-version
nh='npm docs'
/usr/local/bin/xo
nis='npm install --save'
/usr/local/bin/npm
nid='npm install --save-dev'
ags='ag --ignore-case --literal'
nl='npm link --force'
gc () {
	hub checkout "${@:-master}" &> /dev/null || hub checkout "${@:-gh-pages}"
}
/usr/local/bin/node
g=git
s () {
	if [ $# -eq 0 ]
	then
		/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl .
	else
		/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl "$@"
	fi
}
nig='npm install -g'
ni='npm install'
echo: shell built-in command
/usr/local/bin/pageres
gcl=clonecd
```

And `clonecd`:

```sh
clonecd () {
	hub clone --recursive $1 && cd $(basename ${1%.git})
}
```

**Comment by gaboesquivel** [comment]
do you use dash templates?

**Comment by sindresorhus** [comment]
@gaboesquivel Yup, https://dl.dropboxusercontent.com/u/71884/dash-snippets.dash.zip

**Comment by vko-online** [comment]
Don't like webStorm?

**Comment by sindresorhus** [comment]
People have asked what laptop I have now. I still have the MacBook Pro (15-inch, Late 2013). Not because I cannot afford to buy a new one, but rather it's a choice. The current one still works great, although battery life is only 3 hours now. And getting a new one comes with a lot of risk: Touch Bar, crappy keyboard, other flaws. I have to admit that the new 16 inch model is very tempting, but at the same time, I never buy the first model of something. It always has flaws. I'll probably get a new one when the second generation of the 16 inch comes out.
