### ISSUE TITLE
What languages do you speak?

### ISSUE THREAD

**Issue by eush77** [sindresorhus/ama#280]
And what languages, if any,  were / are you learning or plan to learn in the future?

**Comment by sindresorhus** [comment]
JavaScript, English, Norwegian. At some point I want to learn Spanish.

**Comment by styfle** [comment]
@sindresorhus Are you speaking to native Thai people in English, Norwegian, or Thai? Or JavaScript? 😆

**Comment by baumannzone** [comment]
Hey @sindresorhus come to Madrid, if you want to learn spanish 🤓  🤗
