### ISSUE TITLE
What would be the next country for you to live in?

### ISSUE THREAD

**Issue by vdemedes** [sindresorhus/ama#284]

**Comment by sindresorhus** [comment]
I don't know. I really [enjoy](https://github.com/sindresorhus/ama/issues/289) [living in Thailand](https://github.com/sindresorhus/ama/issues/308#issuecomment-158856241). Singapore is also nice, more modern, lots of delicious food, good tech community, but also stricter and housing is crazy expensive. There are also many potential countries I haven't visited yet, so I'll come back to you in a few years when I've tried out more.
