### ISSUE TITLE
Star Trek or Star Wars?

### ISSUE THREAD

**Issue by RobLoach** [sindresorhus/ama#29]
These are the important questions.

![Trek vs Wars](http://i.imgur.com/HY58M7S.jpg)

**Comment by sindresorhus** [comment]
Neither. Stargate for life!

**Comment by Darep** [comment]
> Stargate for life!

![indeed](https://cloud.githubusercontent.com/assets/218910/8463230/6ce39de2-2041-11e5-9d22-71ff8ce3249d.gif)

**Comment by sindresorhus** [comment]
I spend at least 10 minutes a month daydreaming how a new Stargate reboot would look like and hoping it will happen.

**Comment by Darep** [comment]
If RDA could come back as Jack O'Neill, that would be simply the best. So sad that he's an old man now :sob:

**Comment by sindresorhus** [comment]
If Arnold can be a terminator again, anything could happen.

**Comment by Darep** [comment]
That is true! My dreams are alive once again, oh yeah

**Comment by FagnerMartinsBrack** [comment]
Battlestar Galactica 2003 owns all, just saying.
