### ISSUE TITLE
Do you think Firefly should be rebooted?

### ISSUE THREAD

**Issue by elazar** [sindresorhus/ama#291]

**Comment by sindresorhus** [comment]
```
__   _______ ____  _ 
\ \ / / ____/ ___|| |
 \ V /|  _| \___ \| |
  | | | |___ ___) |_|
  |_| |_____|____/(_)
                     
```

It's in my opinion the best scifi TV-show ever made.

![p9rlenlgif](https://cloud.githubusercontent.com/assets/170270/11022860/c94c77c2-869c-11e5-9830-ec232159f00e.gif)

**Comment by elazar** [comment]
It's times like this that make me wish GitHub supported Liking things...

**Comment by ashtonwar** [comment]
But it'd only last for one season - all the main characters became mortal some time between the last episode and Serenity.
