### ISSUE TITLE
If you could choose one place/country to live, what would that be?

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/ama#293]
Except Norway off course?

**Comment by sindresorhus** [comment]
> Except Norway off course?

No exception needed. I would never pick Norway.

**Comment by sindresorhus** [comment]
This will change over time and I intend to try living in many different places. At the moment, I really like [Bangkok](https://en.wikipedia.org/wiki/Bangkok). It has everything I need; heat, good internet, lots of coffee shops, easy to get around, and delicious food everywhere!

**Comment by mertkahyaoglu** [comment]
How much do you spend there for a month?

**Comment by sindresorhus** [comment]
Not exactly sure. Rent was the biggest expense, $560 a month, as I was living very central in a 50 sqm apartment. It get's cheaper further out and smaller. Food is cheap. I also spent a good amount on coffee shops.
