### ISSUE TITLE
How do you learn English? Could you share your learning methods or experience? 

### ISSUE THREAD

**Issue by konekoya** [sindresorhus/ama#296]

**Comment by sindresorhus** [comment]
I learned English in school, but not very well, as I had bad teachers. At least I learned the basic grammar. I learned to read and write English more proficiently through computers and the internet - by reading tech news, discussing online, etc. I also got a lot of my English comprehension from watching American TV-series and movies. One thing I quickly discovered when traveling outside of Norway was how subpar my English speaking skills were. You don't really learn to speak a language without actually speaking it a lot, like every day, and you usually don't do that if it's not the native language where you live. So the best way to learn English for real is to live or travel around people that speak it natively, and not be afraid to try no matter the level you're on.

**Comment by konekoya** [comment]
Thank you for taking your time out your busy day for this one :) It helps me a lot
