### ISSUE TITLE
How do you organize the folders of your Open Source projects? Reply with a picture.

### ISSUE THREAD

**Issue by fauker** [sindresorhus/ama#298]

**Comment by sindresorhus** [comment]
Same as https://github.com/sindresorhus/ama/issues/251. Here's a screenshot:

![screen shot 2015-11-11 at 01 02 13](https://cloud.githubusercontent.com/assets/170270/11070829/02bb471c-8810-11e5-88da-f646e4d3d8f8.png)

**Comment by fauker** [comment]
Thank you. :smile: :+1:

**Comment by rickypaun** [comment]
@sindresorhus How do you manage your projects's folders in Sublime Text? What are your steps to switch to a new project? Do you create `.sublime-projects` files? Do you use the terminal for this? I'm beginner with Sublime.

**Comment by sindresorhus** [comment]
@rickypaun I don't use the Sublime project feature. I just navigate with the terminal and open the active folder or a specific file in Sublime.

In my dotfiles:

```sh
alias subl='/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl'
```

Then I can just run:

```sh
subl .
```

Or a file:

```sh
subl file.js
```

**Comment by sindresorhus** [comment]
My directory structure has changed slightly since I wrote this: https://github.com/sindresorhus/ama/issues/557
