### ISSUE TITLE
What's your favorite spider leg based dish?

### ISSUE THREAD

**Issue by passy** [sindresorhus/ama#3]

**Comment by sindresorhus** [comment]
I'm scared of spiders, but fried insects and margarita is a great party snack.

![img_1747](https://cloud.githubusercontent.com/assets/170270/8454348/f2dfe292-1ffc-11e5-914e-e61cdefa593c.jpg)
![img_1749](https://cloud.githubusercontent.com/assets/170270/8454347/f2df7a1e-1ffc-11e5-9356-0c056fcc03e2.jpg)

-

Btw, fried scorpion sounds delicious, but in reality it's very dry and tasteless.

**Comment by passy** [comment]
Wow!
