### ISSUE TITLE
Why did you create meow?

### ISSUE THREAD

**Issue by oguching** [sindresorhus/ama#307]
https://github.com/sindresorhus/meow

From what I can see it solves kind of the same problem as [commander.js](https://github.com/tj/commander.js) so why did you make meow?

**Comment by sindresorhus** [comment]
You're comparing apples to whales. They might look similar if you haven't read the docs or used them, but when you try them out it will become quite apparent. Meow is just the minimal amount of stuff I do in every single CLI so I don't have to repeat myself. Like showing the version when the user runs `$ foo --version`, handling argument parsing, etc. Commander.js is an opinionated framework for building large command-line apps. It includes a lot of stuff I would never need and limits my creative freedom.
