### ISSUE TITLE
Visa and length of stay in Thailand

### ISSUE THREAD

**Issue by brainstorm** [sindresorhus/ama#308]
<a href="https://github.com/sindresorhus/ama/issues/167">In another issue you briefly mentioned that you are staying somewhere in Bangkok.</a>

As far as I can read from <a href="http://www.thaiembassy.com/thailand/thailand-visa-benefits.php">Thailand visas</a> conditions, the length of stay varies between 30 and 90 days.

Did you manage to stay longer than that? If so, how?

**Comment by sindresorhus** [comment]
I'm staying less than 90 days at a time. The only way to stay longer is to get a different visa which comes with other requirements: investment visa (can stay as long as you have the investment, but requires a pretty large minimum investment), student visa (1 year, but you have to study thai), etc. Thailand recently introduced a [new kind of tourist visa](http://www.bangkokpost.com/archive/new-6-month-visas-begin-nov-13-but-limit-stays/702720) that lasts for 6 months, but you can still only stay 90 days (60 days + 30 extension at the immigration office) at the time. 90 days is a pretty long time, though. There are lots of interesting places to travel to in South East Asia. So take it as an opportunity to do some traveling once in awhile.

One thing that is made harder with this arrangement is getting an apartment. The best apartments come with 1 year minimum lease. You either have to suck it up and pay rent for an apartment you can't use the whole year or find something else.

**Comment by Whoaa512** [comment]
Have you considered turning the apartment into an Airbnb during the time you're not using it?

Would it be worth it to hire someone to manage and run it for you vs. just eating the cost altogether?

**Comment by sindresorhus** [comment]
Sure, that would be a good option. Should be easy to find a someone to run it for you. Probably some companies that offer that service. Some apartments might have restrictions about subletting, though. Personally, I didn't bother to deal with it and instead just found a short-term serviced apartment.
