### ISSUE TITLE
Dude, what's up?

### ISSUE THREAD

**Issue by gpestana** [sindresorhus/ama#309]
Hey, I just came across you AMA and wanted to know what's up?

**Comment by sindresorhus** [comment]
Just hacking on some modules today.

Yesterday, I was celebrating [Loi Krathong](https://en.wikipedia.org/wiki/Loi_Krathong) here in Bangkok, which is a fullmoon festival where decorated candlelit baskets are floated down the river.

![loi-kratong](https://cloud.githubusercontent.com/assets/170270/11415287/c6652082-9433-11e5-8b33-9dded5ca214f.jpg)
