### ISSUE TITLE
Would you consider unblocking me?

### ISSUE THREAD

**Issue by TehShrike** [sindresorhus/ama#310]
Apparently you blocked me on Twitter at some point in the last few months. :-x I don't remember interacting with you directly, so I'm not sure why.

https://twitter.com/TehShrike

I miss reading your tweets.  If you would unblock me I'd appreciate it - even if you mute me right away to make sure you don't see any of my tweets or messages or anything.

I understand it's a potentially rude thing to communicate with somebody that has blocked you, but this repo specifically calls out asking *anything*, so here I am.  If you remember why you did block me, I'd be curious to hear what it was.

If you don't remember, and/or still aren't willing to unblock me, feel free to just close this issue and I won't try to communicate with you through any other way.

**Comment by sindresorhus** [comment]
Done. Don't remember why to be honest. I use the block button generously to filter out noise and negativity. Maybe sometimes too generously. I'll try to use the mute button more in the future ;)
