### ISSUE TITLE
You have almost 3 billion downloads on npm

### ISSUE THREAD

**Issue by lipis** [sindresorhus/ama#314]
Not really a question. Just in case you were wondering.

http://www.npm-stats.com/sindresorhus

<img width="657" alt="screen shot 2015-12-14 at 18 32 08" src="https://cloud.githubusercontent.com/assets/125676/11788477/7d510cbe-a291-11e5-91a8-273e3934b6b5.png">

**Comment by dthree** [comment]
:+1:

**Comment by Knorcedger** [comment]
Insane stuff. Well done!

**Comment by lipis** [comment]
and soon the first person to hit the 100K :star: http://githubstats.lip.is :)

**Comment by icyflame** [comment]
Oh! @sindresorhus ' downloads are almost equivalent to the downloads of the Bootstrap repository. And that repository almost every web dev has downloaded, some time or another. Awesome! :+1:

**Comment by dthree** [comment]
:rocket:

**Comment by sindresorhus** [comment]
![68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f75344163337942656b623272362f67697068792e676966](https://cloud.githubusercontent.com/assets/170270/14208564/4d4f8298-f84a-11e5-8186-0622f2d0054e.gif)
