### ISSUE TITLE
Dog food?

### ISSUE THREAD

**Issue by kentcdodds** [sindresorhus/ama#315]
https://twitter.com/sindresorhus/status/676583170809040896

> I just ate some dog food. AMA.

![v_nkez5w](https://cloud.githubusercontent.com/assets/1500684/11800246/a2debcc6-a28f-11e5-860d-31d90a15a264.png)

**Comment by sindresorhus** [comment]
It's not that bad. Tastes like hard crispbread with a hint of tuna. Canned cat food, however, is the most disgusting thing I've ever tried, and I've eaten things like fried scorpion and [insects](https://github.com/sindresorhus/ama/issues/3).

**Comment by kentcdodds** [comment]
Thanks for getting back to me.

![giphy](https://cloud.githubusercontent.com/assets/1500684/13000415/e127495a-d10e-11e5-93d4-91cc5e89f8dd.gif)
