### ISSUE TITLE
What is your workflow, extensions and etc? 

### ISSUE THREAD

**Issue by karlcoelho** [sindresorhus/ama#317]
[Related to this](https://github.com/arthurvr/ama/issues/38)

**Comment by sindresorhus** [comment]
Answered in: https://github.com/sindresorhus/ama/issues/28 https://github.com/sindresorhus/ama/issues/227 https://github.com/sindresorhus/ama/issues/267 https://github.com/sindresorhus/ama/issues/343 https://github.com/sindresorhus/ama/issues/131
