### ISSUE TITLE
Do you know any tool to analyze CSS and report the minimum supported browser?

### ISSUE THREAD

**Issue by cjpatoilo** [sindresorhus/ama#321]
Hi Sindre!

So, do you know any tool to analyze the CSS and report the minimum support of the browser (Browser Support Version)?

**Comment by sindresorhus** [comment]
Not that I'm aware of, but I haven't been using CSS much the past year. Someone could use https://github.com/Fyrd/caniuse to make a tool like that. You might want to request it in https://github.com/sindresorhus/module-requests ;)

**Comment by egoist** [comment]
There is also a similar tool [doiuse](https://github.com/anandthakker/doiuse).
