### ISSUE TITLE
Developer Advice

### ISSUE THREAD

**Issue by kennetpostigo** [sindresorhus/ama#322]
Hello,

In your opinion as a developer and years of experience what new up and coming library/framework in the Javascript ecosystem do you think is worth investing to time to learn and help contribute to?

ex: Rx, React, Aurelia, Cycle, etc.

**Comment by sindresorhus** [comment]
When it comes to frameworks, I think React + Redux are the most promising and pragmatic right now, but I'm also keeping a close eye to [Deku](http://dekujs.github.io/deku/) and [Cycle.js](http://cycle.js.org). Though to be honest, I'm not as super excited about web frameworks as everyone else seems to be. I'm much more excited about what's happening in the Node.js, Electron, React Native ecosystems.

**Comment by kennetpostigo** [comment]
Thank you for the feedback 👍
