### ISSUE TITLE
Did you have a nice Christmas?

### ISSUE THREAD

**Issue by robbbz** [sindresorhus/ama#323]

**Comment by sindresorhus** [comment]
Yes. 🎄🎉 It was wonderful. Family and lots of good food :)

![img_0140](https://cloud.githubusercontent.com/assets/170270/12043205/0b53d47c-ae83-11e5-98eb-33b04d469cc7.jpg)
![img_1295](https://cloud.githubusercontent.com/assets/170270/12043207/0b560c1a-ae83-11e5-9d7e-c715f34ba565.jpg)
![img_9962](https://cloud.githubusercontent.com/assets/170270/12043208/0b591cd4-ae83-11e5-9f51-d263bd198c3f.jpg)
![img_0033](https://cloud.githubusercontent.com/assets/170270/12043209/0b5949e8-ae83-11e5-9fc4-e01dc493d589.jpg)
![img_0052](https://cloud.githubusercontent.com/assets/170270/12043206/0b555586-ae83-11e5-94a2-3c5c9fd3626d.jpg)

**Comment by ghpabs** [comment]
Love the unicorn slippers! And it looks like a fun/fancy xmas party. :-)
