### ISSUE TITLE
What is your MBTI personality type?

### ISSUE THREAD

**Issue by dylang** [sindresorhus/ama#324]
What's your MBTI personality type?

Here's [a form that's quick](http://www.16personalities.com/free-personality-test) and doesn't require a login, sharing to facebook, or any other personal info. It also has a lot of information about each personality type. http://www.16personalities.com/free-personality-test

*Background: I thought Myers Briggs personality types were as useful as astrological signs until I finally listened to my wife and started reading about mine ([INTP](https://www.reddit.com/r/intp)). I feel so much enlightenment into how I think, work, what I'm good at and what I'm not. I also think it's helping me work better with my co-workers.*

Anyone else reading, share yours too!

![mbti chart](http://img09.deviantart.net/6a26/i/2015/115/8/e/mbti_chart_chibis_by_ri_m-d51reh5.jpg)
[Image source](http://glaceau.deviantart.com/art/MBTI-Chart-chibis-305288969)

**Comment by sindresorhus** [comment]
INTP 🤘

**Comment by dylang** [comment]
<img width="409" alt="screen shot 2015-12-27 at 11 34 33 pm" src="https://cloud.githubusercontent.com/assets/51505/12014048/779c2d4c-acf2-11e5-8fab-4cf025680a06.png">
