### ISSUE TITLE
Contributing to OSS

### ISSUE THREAD

**Issue by rajzshkr** [sindresorhus/ama#326]
Hi Sindre, I am passionate js developer. I like to contribute for open source projects. Can you suggest some of the project actively looking for contributors ?

**Comment by dthree** [comment]
I'm not Sindre, but I am looking for assistance in closing issues on [Vorpal.js](https://github.com/dthree/vorpal), if you're interested. I haven't had much time recently but am trying to get the issues back down to 0!

**Comment by dthree** [comment]
Btw Sindre, you could make a repo [like this one](https://github.com/sindresorhus/module-requests), only for contribution requests. I think that would be cool. i.e. if someone with a large project wants contributors, they can file an issue there. Just an idea.

**Comment by rajzshkr** [comment]
Happy to help you. I didn't find any contribution guidelines. Can you please help?

**Comment by dthree** [comment]
Thanks and sure! Haven't formally made any, so most contributions from others have been point-and-shoot using known GH best practices. I'll put together some guidelines.

**Comment by kentcdodds** [comment]
@rajzshkr, I'm also not @sindresorhus, but you might look at [my answer](https://medium.com/@kentcdodds/what-open-source-project-should-i-contribute-to-7d50ecfe1cb4#.hgqr7o5hp) to that question

**Comment by rajzshkr** [comment]
@kentcdodds  thanks i gave my first PR to bower!!

**Comment by kentcdodds** [comment]
Congratulations! :tada:

**Comment by bhaveshgohel** [comment]
Thanks for the Link! @kentcdodds :)

**Comment by rajzshkr** [comment]
@kentcdodds  thank you!!
