### ISSUE TITLE
Will you come to Bangkok in 2016?

### ISSUE THREAD

**Issue by lvarayut** [sindresorhus/ama#327]
I'm freelance full-stack web developer based in Bangkok. I have been following you for a while and really love all of your open-source projects. I just have read all of your AMA issues and saw that you sometimes stay in Bangkok. It would be really nice to meet you here. Would it be possible to find a great coffee shop to chat and to hack on some cool project together?

**Comment by sindresorhus** [comment]
I'll be in Bangkok from February 1st for about 4 months. Happy to meet up then!* Lets sort out the details when I'm there. Happy holidays. 🎄

-

*That also applies to anyone lurking here :D

**Comment by lvarayut** [comment]
Perfect! Happy holidays and see you soon  :santa:

**Comment by sindresorhus** [comment]
@lukyth We already met up a while ago. Would be happy to meet up with you too.
