### ISSUE TITLE
Would you like to make a logo for conventional-changelog?

### ISSUE THREAD

**Issue by stevemao** [sindresorhus/ama#328]
[conventional-changelog](https://github.com/ajoslin/conventional-changelog) is the tool used by angular (and a few other projects) to generate a changelog. I have a few ideas to do with it. It would be great if there is a logo. 

Of course only if you have time.

Thanks in advance :smile:

**Comment by sindresorhus** [comment]
I enjoy making logos, but I don't have much time for that right now.

**Comment by stevemao** [comment]
All good. Whoever sees this and would like to do it I'd appreciate it :smiley:
