### ISSUE TITLE
Would you do a screencast?

### ISSUE THREAD

**Issue by cherrycoda** [sindresorhus/ama#329]
Would you consider doing a screencast that showed your workflow, from start to finish, when creating a small node module?

**Comment by sindresorhus** [comment]
At some point, yes, but not right now. I have too much on my plate at the moment.

**Comment by bhaveshgohel** [comment]
+1 @sindresorhus : will love to watch that screencast if you do. :smiley:

**Comment by dawsonbotsford** [comment]
+1

**Comment by alisonmonteiro** [comment]
+1

**Comment by stevemao** [comment]
Just for the reference Sindre did it with Paul Irish and Addy Osmani a few years ago.

https://www.youtube.com/watch?v=HijZNR6kc9A

**Comment by sindresorhus** [comment]
Ow gawd, that's the bane of my existence...

**Comment by dthree** [comment]
Haha why? You did fine.

**Comment by sindresorhus** [comment]
My English was really bad back then and I was super nervous since it was live.
