### ISSUE TITLE
Your next computer

### ISSUE THREAD

**Issue by cherrycoda** [sindresorhus/ama#331]
in #28 you describe your Mac as "the best computer [you]'ve ever had". But how would you like your *next* computer to be? Could you give us your preferences on the following attributes:

a) it should be more powerful (faster processor, more RAM)
b) it should be lighter/thinner/smaller
c) it should have longer battery life
d) it should cost less
e it should have upgradable parts
f) it should have built-in 4G
g) it should run a non-proprietary OS
h) ______________

If possible, list your choices in order of preference.

**Comment by sindresorhus** [comment]
a. Yes, but not at the cost of `c`.
b. Yes!
c. Yes!
d. Nope. My computer is an investment in myself. I spend so much time on it.
e. Definite no. That never leads to good design.
f. Would be nice as I travel and often use 4G, but I have 4G on my phone that I can tether, so not super important.
g. I want something that just works. Could be a non-proprietary OS, but I've honestly never tried one that just works.
h. Comfortable big trackpad and backlit keyboard.
j. High-DPI screen. Once you've gone HDPI, you can never go back.

I want to buy the new MacBook Pro 15-inch that is [rumored](http://www.macrumors.com/2015/12/31/what-to-expect-from-apple-in-2016/) to be announced this or next quarter with a new design and the Intel Skylake processor.
