### ISSUE TITLE
What do you think about the new Norwegian Money and Passports?

### ISSUE THREAD

**Issue by ariporad** [sindresorhus/ama#332]
Hi @sindresorhus!

Since you're Norwegian, I thought I may as well ask, what do you think of the new Norwegian Money:
![New Money](http://i.imgur.com/PIGfg3U.jpg)
And Passports:
![Outside](http://cdn.theatlantic.com/assets/media/img/posts/2014/11/Screen_Shot_2014_11_17_at_4.57.40_PM/cb9bcb974.png)
![Inside](http://www.norway.cn/Global/SiteFolders/webbeij/passport-inside.png)

**Comment by sindresorhus** [comment]
It looks so beautiful! ✨Norwegians will soon have the most awesome money and passport in Milky Way :) I can't believe the government actually managed to do something useful.
