### ISSUE TITLE
What do you think about bitcoin?

### ISSUE THREAD

**Issue by pragmaticivan** [sindresorhus/ama#333]

**Comment by sindresorhus** [comment]
I was super-excited about it when I first realized, pretty late, how awesome the tech is. Although, I've always been sceptical about its practical merits. My current feelings are pretty well reflected in the following article ["The resolution of the Bitcoin experiment"](https://medium.com/@octskyward/the-resolution-of-the-bitcoin-experiment-dabb30201f7) and [this tweet](https://twitter.com/sarahjeong/status/687804788696743936).

Today, I'm more excited by [Zcash](https://z.cash), which manages total payment confidentiality using [zero-knowledge proof](https://en.wikipedia.org/wiki/Zero-knowledge_proof).
