### ISSUE TITLE
Subject trend Year

### ISSUE THREAD

**Issue by juanespina** [sindresorhus/ama#336]
What do you think will be most talked about and studied this year, example API, Spec and tools.

**Comment by juanespina** [comment]
cc @sindresorhus

**Comment by sindresorhus** [comment]
Native development with JavaScript and VR. React Native (mobile) and Electron (desktop) are growing like crazy and that will continue throughout 2016. Many large companies will announce and create their apps with these platforms. With the release of Oculus Rift we'll see an influx of VR, even on the web. Many VR related SDKs, modules, services and features will pop up all around us. YouTube and Facebook are already testing VR support. Expect having to endure a lot of churn while we figure out what will and won't work regarding VR, but also lots of innovative experiments around interactivity.

The JavaScript community will hopefully stabilize a bit, especially when it comes to tooling and frameworks. React will continue its crazy growth, but most of the innovation will happen in the ecosystem with Redux and other yet to be made packages and ideas. We'll see more and more companies adopting symbiotic rendering (both server and client), which enables exciting things like ability to render the [initial page on the server](https://developers.google.com/web/fundamentals/performance/critical-rendering-path/) and subsequent pages on the client, or [only render on the client during heavy server load](https://gist.github.com/rgrove/3e612aa366541845161c).

In the tooling world, we'll finally see a Gulp 4 release and long-long awaited Grunt v1 release, but those tools only solve so much and we'll still be stuck with a lot of boilerplate and wanting something better. The big thing this year will be ES2015 modules and [tree-shaking](https://medium.com/@Rich_Harris/tree-shaking-versus-dead-code-elimination-d3765df85c80#.nplks9r69) (it only includes the bits of code your bundle actually needs to run) using [rollup.js](http://rollupjs.org) or [Webpack 2](http://www.2ality.com/2015/12/webpack-tree-shaking.html).

And last, in a highly biased fashion, I think concurrent atomic testing will be huge → [AVA](https://github.com/sindresorhus/ava).
