### ISSUE TITLE
What do you think about Git Flow?

### ISSUE THREAD

**Issue by oscarmcm** [sindresorhus/ama#338]
http://danielkummer.github.io/git-flow-cheatsheet/

**Comment by sindresorhus** [comment]
I've only tried it briefly, so take this with a grain of salt, but it didn't really work for me. For most of my projects, of which are tiny modules, I just work directly on master, and on the few larger ones, I use branches the normal way. So I guess I didn't really see the immediate value of the opinionated git flow.
