### ISSUE TITLE
Who are your programming heroes?

### ISSUE THREAD

**Issue by robbbz** [sindresorhus/ama#34]
You're mine, but what people are you looking up to and why? Maybe because they write good code? Or simply because they're exceptional?

**Comment by prakhar1989** [comment]
Great question!

**Comment by sindresorhus** [comment]
I don't have any heroes. There are people I respect and admire, but in the end we're all just human.

I admire Elon Musk for his infatuation to make mankind a multi planetary species.
I admire Steve Jobs for bringing us Apple and Pixar.
