### ISSUE TITLE
Do you use any particular tool to resolve merge conflicts?

### ISSUE THREAD

**Issue by jmversteeg** [sindresorhus/ama#343]
Stuff like
 - kdiff
 - kaleidoscope

etc.

**Comment by sindresorhus** [comment]
I manually fix simple conflicts in Sublime and [Kaleidoscope](http://www.kaleidoscopeapp.com/) for more difficult ones.

**Comment by stevemao** [comment]
@jmversteeg I use [diff-so-fancy](https://github.com/so-fancy/diff-so-fancy) :)
