### ISSUE TITLE
Have you ever joined any programming contests?

### ISSUE THREAD

**Issue by buefin** [sindresorhus/ama#344]
I'm have been programming for many years and really love it. I'm personally good at programming but not quite good at Mathematic. Recently, I have joined a programming contest, I could solve just half of the problem, I felt very disappointed about the result. In order to be better programmer, I'm not sure if I need to re-read all the mathematic theories or not; Discrete mathematics, Sorting trees, Pigeon hole, and etc. 

I would like to get some advices from you. In your opinion, do you think there are a strong correlation between Programming and Mathematic? Should I re-read all the mathematic theories and join the contests in order to become a great programmer?

Thanks in advance. Any advices from you will be very valuable for me.

**Comment by sindresorhus** [comment]
I have never participated in a programming contest. Not my thing.

Whether you should improve your math knowledge really depends on what kind of programming you want/need to be doing. The kind of programming I do, Node.js and front-end JS, require very little math knowledge, but if you for example want to do scientific programming or work on hard problems at e.g. Google, you obviously need to know your math. That being said, math knowledge never hurts, but there are many more important things to learn to be a great programmer, like how to create performant scalable maintainable systems, code reuse, readable code, usable APIs, debugging & profiling, resolving bugs, writing approachable docs, collaboration with other humans, etc.
