### ISSUE TITLE
How is life?

### ISSUE THREAD

**Issue by brutalcrozt** [sindresorhus/ama#345]
bad or good i will patienly wait and read it :smile: 
But TBH i really want hear the bad one, i want learn something :grinning:

**Comment by sindresorhus** [comment]
Can you be more specific? Not entirely sure what you're asking.

**Comment by brutalcrozt** [comment]
How your life is going now?
just tell me something happen in your life recently dude , it's up to you :smile:

**Comment by sindresorhus** [comment]
Life is good. I'm currently hacking on some open source projects in a coffee shop in Bangkok. Later today I'm having some friends over for a <del>house</del>apartment-warming party on the roof of the apartment building. This weekend I'm going to a farmers market for some delicious food and maybe some partying afterwards.
