### ISSUE TITLE
Most enjoyable frameworks

### ISSUE THREAD

**Issue by IanShoe** [sindresorhus/ama#346]
... not necessarily most productive or most relevant. A different phrasing of the question maybe "framework with most personal awe factor"

client side?
server side?

**Comment by egoist** [comment]
I also want to know if sindre ever tried out the Vue.js 🌝

**Comment by sindresorhus** [comment]
None. [I don't like frameworks.](https://github.com/sindresorhus/ama/issues/10#issuecomment-117766328) However, I've experimented with Ember, Angular, React, Deku, and personally prefer React and Deku. Haven't tried Vue.js, but it looks interesting. 

My advice is to experiment with many different frameworks, but use what you're efficient in. Don't just follow the hype. The product is what matters.
