### ISSUE TITLE
How do you manage ES6 vs. ES5 JavaScript snippets when switching context? 

### ISSUE THREAD

**Issue by gaboesquivel** [sindresorhus/ama#348]
I use atom and turn on and off packages. Do you know a more efficient way do this?

question is also posted in atom's forum: https://discuss.atom.io/t/solutions-for-es6-vs-es5-javascript-snippet-management/24807?u=gaboesquivel

**Comment by sindresorhus** [comment]
I don't use snippets. If something is to hard to write out manually, I just make it a module.

[npm is my snippet database](https://github.com/sindresorhus/ama/issues/10#issuecomment-117766328).

**Comment by gaboesquivel** [comment]
:+1:

**Comment by gion** [comment]
Should've expected an answer like that :)
