### ISSUE TITLE
Did you know your new profile looks like Anakin Skywalker?

### ISSUE THREAD

**Issue by dthree** [sindresorhus/ama#349]
It's the hair, plus the pronounced earbud cord on the right side, but it's the first thing I thought of. :smiley: 

Amazing!

**Comment by sindresorhus** [comment]
Hah, I did not, but thanks :)
I'm ashamed to say, but I had to Google "Anakin Skywalker". I've never watched Star Wars.

**Comment by dthree** [comment]
:smile: 

Well, you have to watch the original 3 - don't do the first three!

**Comment by sindresorhus** [comment]
Yup https://mobile.twitter.com/sindresorhus/status/681931681104838658

**Comment by dthree** [comment]
Haha perfect!
