### ISSUE TITLE
What makes you decide when you add somebody to a repo/org?

### ISSUE THREAD

**Issue by robbbz** [sindresorhus/ama#35]
I guess you have some criteria? :beers:

**Comment by sindresorhus** [comment]
If someone does multiple good pull requests and seems interested in the project I usually add that person. I also have some people I trust that I add to all my repos.

**Comment by robbbz** [comment]
@sindresorhus Doesn't that ever go wrong?

**Comment by sindresorhus** [comment]
It hasn't yet. I'm pretty good at judging people. I also prefer to give people the benefit of the doubt. Someone can always be removed later, but I doubt that will ever be needed.

**Comment by nickedes** [comment]
:+1:
