### ISSUE TITLE
What did you feel like when you received your first pull request?

### ISSUE THREAD

**Issue by icyflame** [sindresorhus/ama#351]
To be specific, not from someone you were actively collaborating with, but just someone on the internet who happened to find out about your project and then sent a PR. 

- when was this?
- which project was it?

(This can probably be found from GitHub search. But so many pull requests, I am just curious to know of that first project was ever special to you, in any way.)

**Comment by sindresorhus** [comment]
<img src="https://cloud.githubusercontent.com/assets/170270/12812449/b384d2b0-cb64-11e5-88a3-621a34962dcf.gif" width="120" align="left">

I was super excited when I recieved my first PR → https://github.com/sindresorhus/notifier-for-github/pull/2

-

[All the early PRs I received.](https://github.com/search?o=asc&q=user%3Asindresorhus+is%3Apr+is%3Amerged&ref=searchresults&s=created&type=Issues&utf8=%E2%9C%93)

**Comment by hkdobrev** [comment]
Related (and interesting) search: [First PRs submitted by @sindresorhus](https://github.com/search?o=asc&q=author%3Asindresorhus+is%3Apr+is%3Amerged&ref=searchresults&s=created&type=Issues&utf8=%E2%9C%93).
