### ISSUE TITLE
Your Node and npm versions

### ISSUE THREAD

**Issue by dawsonbotsford** [sindresorhus/ama#352]
I want to know what version of node and npm you run. 

```shell
node --version && npm --version
```

The current speed of npm 3 is crippling on my system and have turned me away until it is improved. Are you also turned away until it's up to snuff?

**Comment by sindresorhus** [comment]
```
❯ node --version && npm --version
v4.2.4
3.7.2
```

My main Node.js version is v4 to ensure I don't use ES2015 features only available in v5+. I had to upgrade to npm@3 recently, as Babel is unbearably slow without the deduplication that comes with npm@3... I also have all other Node.js versions installed using [n](https://github.com/tj/n) for testing purposes.
