### ISSUE TITLE
Do you hang out with programmer friends often?

### ISSUE THREAD

**Issue by ArtskydJ** [sindresorhus/ama#356]
I have a few friends who are programmers, and I see them a couple times each week.

Do you have (non-internet) friends who also do programming? Do you hang out and hack together?

**Comment by sindresorhus** [comment]
Less than I'd like to, to be honest. Most of my programmer friends live in different countries. While I can easily be sociable when needed, I'm an introvert, so I don't seek social interactions. Might also be, I interact with so many programmers online all day, in real-life, I find it nice being around non-tech people for a change.
