### ISSUE TITLE
How do you explain to others what you do?

### ISSUE THREAD

**Issue by ArtskydJ** [sindresorhus/ama#357]
If a non-programmer asks you what your job is, how do you explain it?

(I know you don't have a job in the normal sense, but if someone asks about it, how do you explain programming to them?)

**Comment by srph** [comment]
I'm curious as well.

**Comment by wfxiaolong** [comment]
I'm a engineer for human further.

**Comment by sindresorhus** [comment]
I say that I make tools for developers. Actually, usually I just say that I make apps, because I do that in addition to open source, and it's easier for people to relate to.
