### ISSUE TITLE
What is your configuration on testing (integration test) REST API that uses DB?

### ISSUE THREAD

**Issue by diorahman** [sindresorhus/ama#359]
Do you mock your DB or just using a "test" DB?

**Comment by sindresorhus** [comment]
I try to mock as little as possible as it can obscure real issues. Instead, I fill the "test" database with some predefined fixture in the test setup function.

**Comment by SamVerschueren** [comment]
I used to mock my DB but noticed that some bugs might slip into the query that are only addressed when ran against a real database instance.

**Comment by diorahman** [comment]
Thanks!
