### ISSUE TITLE
What podcasts are you listening to and why?

### ISSUE THREAD

**Issue by robbbz** [sindresorhus/ama#36]
Or don't you listen to podcasts? Interested if you had any interesting developer specific ones?

**Comment by sindresorhus** [comment]
I've tried a lot of podcasts, but these are the ones I usually listen too:

- [NodeUp](http://nodeup.com/)
- [The Changelog](https://changelog.com/podcast/)
- [JavaScript Jabber](http://devchat.tv/js-jabber/)

**Comment by sindresorhus** [comment]
I would also recommend asking the same question on [@passy's AMA](https://github.com/passy/ama). He listens to a lot more interesting podcasts than I do.
