### ISSUE TITLE
afterEach and beforeEach not running?

### ISSUE THREAD

**Issue by kentcdodds** [sindresorhus/ama#360]
I've reproduced this bug in [this repo](https://github.com/kentcdodds/ava-beforeEach-afterEach-bug). From the README there:

> The `test` directory has a `bug.js` and a `workaround.js`.
> 
> If you run: `npm install` and then `npm t` you'll get:
> 
> ```
> ~/Developer/ava-beforeEach-afterEach-bug (master)
> ⛄  $ npm run test -s
> 
>   ✔ workaround › first log
>   ✔ workaround › second log
>   ✔ bug › first log
>   ✖ bug › second log   
>   t.true(console.log.calledOnce)
>                      |          
>                      false      
>   
> 
>   1 test failed
> 
>   1. second log
>   AssertionError: false === true
>     Test.fn (test/bug.js:16:3)
>     
> 
> ```
> 
> For some reason, it appears that perhaps the cleanup function is not run between the two test runs.

It's using the latest version of AVA. Specifically, I spotted this [here](https://github.com/kentcdodds/configuration-validator/blob/master/src/configValidator/index.test.js). Let me know if you need more info!

**Comment by Rowno** [comment]
Would probably be better to post this in the [AVA issue tracker](https://github.com/sindresorhus/ava/issues).

**Comment by kentcdodds** [comment]
Oh, yikes! lol. My browser must have autocompleted (－‸ლ)

Thanks for speaking up @Rowno! How embarrassing! 😳
