### ISSUE TITLE
When do you mark modules as 1.0.0?

### ISSUE THREAD

**Issue by sotojuan** [sindresorhus/ama#361]
I'm asking mostly for "small" stuff like [this](https://github.com/sindresorhus/onetime). When do you decide to make it 1.0.0 as opposed to 0.x.y? Is it just a matter of you being comfortable with calling the API stable?

**Comment by sindresorhus** [comment]
I make most modules 1.0.0 right away, as they're usually small and focused, and I try hard to make them be done at publish time. The few times I don't, are for larger modules ([AVA](https://github.com/sindresorhus/ava), [XO](https://github.com/sindresorhus/xo)), or when I'm not entirely confident in the API ([bitbar](https://github.com/sindresorhus/bitbar), [execa](https://github.com/sindresorhus/execa)) or implementation ([boxen](https://github.com/sindresorhus/boxen)).

**Comment by sotojuan** [comment]
Thanks!
