### ISSUE TITLE
Laptop back cover

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/ama#362]
Like to see a picture of your laptop back cover. Do you have some stickers or do you prefer not to show you're developer :)?

**Comment by sindresorhus** [comment]
[![image](https://cloud.githubusercontent.com/assets/170270/13171416/5f834f4e-d725-11e5-9e53-2ec65f0904f7.png)](https://www.instagram.com/p/BBBMaFRoUBH/)

**Comment by SamVerschueren** [comment]
:+1: :)

**Comment by Whoaa512** [comment]
Where can I get an AVA sticker like that?

**Comment by alrra** [comment]
> Where can I get an AVA sticker like that?

@Whoaa512 https://www.stickermule.com/user/1070705604/stickers (from: https://github.com/sindresorhus/ava#links)

**Comment by SamVerschueren** [comment]
They're awesome!!

**Comment by sindresorhus** [comment]
It's a bit more noisy these days 😝

![04302BA1-7099-4D41-9930-93AA4853E262](https://user-images.githubusercontent.com/170270/59562325-7e792800-9055-11e9-915b-7f0c5b1158db.jpg)
