### ISSUE TITLE
How do you handle forked repos?

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/ama#363]
0. See repo
1. Fork repo
2. Submit PR
3. PR is accepted
4. ????
5. Non-profit

What is your step 5? How do you not end up with a bunch of useless forks on your profile?

**Comment by sindresorhus** [comment]
I don't really have a good workflow for this. I just leave the forks. Happy to hear suggestions for how to better handle this.

[This `refined-github` feature will make it slightly easier to handle](https://github.com/sindresorhus/refined-github/pull/49).

**Comment by bfred-it** [comment]
Looking a bit further I found this: https://github.com/denis-sokolov/remove-github-forks

> Delete all forks that have no commits that are not in the main repository

It seems to work pretty well!

---

I'd like to use refined-github but I don't like some features. Perhaps if someday they'll be optional.

**Comment by sindresorhus** [comment]
> It seems to work pretty well!

There's also: https://github.com/kevva/github-remove-forks

But I would never trust those unless they had a bunch of tests.

> I'd like to use refined-github but I don't like some features.

Like? Just curious.

**Comment by bfred-it** [comment]
Ah yeah, that's what I saw a while ago but I avoided using it because of this https://github.com/kevva/github-remove-forks/issues/2#issuecomment-113051658 (which denis' version takes care of)

The good part is that it asks you first, so when I ran it I manually checked the 20 repos that it suggested deleting.

---


> Hides :+1: :-1: comments and shows their count in the sidebar **When there's only a few of them they might just be "okay, that works" rather than "I vote for this feature"**
> Hides other users starring/forking your repos from the newsfeed **I don't get many stars so when it's nice to see if people use my code**
> 
> **I don't mind leaving the following as GitHub wants**
> Removes tooltips
> Removes annoying hover effect in the repo file browser
> Removes the comment box toolbar
> Moves the dashboard organization switcher to the right column
