### ISSUE TITLE
hack dev's machine by un-un-publish node module.

### ISSUE THREAD

**Issue by unbug** [sindresorhus/ama#368]
After I read this [kik, left-pad, and npm](http://blog.npmjs.org/post/141577284765/kik-left-pad-and-npm), I feel uneasy.LOST of dev has node install.So hacker can attack developer's machine by un-publish a good module and re-publish with a virus one.What can we do about this?

**Comment by es128** [comment]
Hackers can't unpublish others' modules. But it is true that if an npm publisher decides to unpublish, it is possible for someone else to publish something else under the same module name - different version though. 

This probably isn't the best forum for discussing this topic.

**Comment by unbug** [comment]
@es128 Hacker can just hack from the author of a popular module.That's too easy to take all us down.It's horrible.

**Comment by sindresorhus** [comment]
@es128 Actually they can. They can publish a package with a `postinstall` script that runs npm and unpublishes something. I install this package, and boom...

**Comment by sindresorhus** [comment]
Ideally unpublish should only be possible from the npm web interface with a confirmation email and grace period.

**Comment by unbug** [comment]
@sindresorhus That's what I am saying.NPM index package by unique module name is unsafe.

**Comment by sindresorhus** [comment]
I doubt anything drastic will happen though. npm will implement some small improvements to the process and everyone will forget about this incidence in a month.

**Comment by sindresorhus** [comment]
It's not like we don't know this could happen. The whole system is entirely built on trust, and it has worked exceptionally well until now. It *is* super risky though, I must admit. Kinda scary to think what would happen if I unpublished `chalk` (I WOULD NEVER), or even worse, added a `postinstall` script with `rm -rf /`...

**Comment by unbug** [comment]
@sindresorhus just like the Apple xcodeghost,it's still going with other way

**Comment by unbug** [comment]
@sindresorhus any news from NPM?Do they start to think about those crazy issues?

**Comment by sindresorhus** [comment]
`¯\_(ツ)_/¯` Ask them.

**Comment by unbug** [comment]
@sindresorhus Really,I'm scared, we should be.

**Comment by dthree** [comment]
A simple switch from `^1.0.0` to `1.0.0` in a `package.json` would eliminate any scare of malicious intent. And NPM will figure out the right move on unpublishing. I'm honestly not worried.

**Comment by sindresorhus** [comment]
> A simple switch from ^1.0.0 to 1.0.0 in a package.json would eliminate any scare of malicious intent.

That would only work if the whole dependency tree did it, which is totally unrealistic unless you control all of the nested packages.

> And NPM will figure out the right move on unpublishing.

The issue isn't just unpublishing as commented earlier.

> and wouldn't try to break the trust in such a helpful ecosystem for a personal feud.

Sure, but what if a trusted person gets infected with a virus that does it on her/his behalf?

**Comment by thomaslindstrom** [comment]
I know you've dismissed this in the past – but wouldn't this be the perfect time to swoop in with a shiny, new & decentralized package manager? Pretty much [all the comments over on the blog post about this issue](http://blog.npmjs.org/post/141577284765/kik-left-pad-and-npm#disqus_thread) are opening up to the idea of an npm.js alternative.

**Comment by simov** [comment]
I'm actually happy that this happened with a heavily dependent on module, so that it opened our eyes about the shady practices of swapping module owners around for no good reason. In this case you don't even need your computer to be hacked.

**Comment by unbug** [comment]
@dthree That's the biggest problem, NPM is build on community trust, to make it safe stronger policy is required.

> Just saying. It has indeed been working pretty good as is, but when communities gets bigger, the bad apples tend to come out of their caves.

@sindresorhus That's what we should be scared, NPM is too big to live without it.

@thomaslindstrom It's not easy to "making one yourself".

@simov Hope we learned a lesson from this.

**Comment by unbug** [comment]
The other consider is a module name now can be sold in BLACK market.

**Comment by simov** [comment]
@unbug I personally have a couple of stupid names and namespaces (accounts) registered on NPM that are currently empty. But that's just because naming is so hard and I change my mind over time while working on the project (prior releasing it). Some names will eventually be used, some of them I can release without a problem. But I have invested so much time, energy and money in some of them, that the idea of losing them so easily to some patent troll is beyond me.

**Comment by unbug** [comment]
@simov So it is.BTW if you have problem with naming things,you can try [Codelf](http://unbug.github.io/codelf/).

**Comment by sindresorhus** [comment]
[Official npm response](http://blog.npmjs.org/post/141702881055/package-install-scripts-vulnerability) and [announcement about changes to `npm unpublish`](http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy).

**Comment by bfred-it** [comment]
> > A simple switch from ^1.0.0 to 1.0.0 in a package.json would eliminate any scare of malicious intent.

> That would only work if the whole dependency tree did it, which is totally unrealistic unless you control all of the nested packages.

You can lock the whole dependency tree with [`npm shrinkwrap`](https://docs.npmjs.com/cli/shrinkwrap)

**Comment by sindresorhus** [comment]
@bfred-it AFAIK that doesn't work for git dependencies, so you're still not totally safe.
