### ISSUE TITLE
How often do you change your iPhone and MacBook?

### ISSUE THREAD

**Issue by unluisco** [sindresorhus/ama#369]
every time Apple has new one?

**Comment by sindresorhus** [comment]
History:

- Macbook Pro 17", late 2007
- Macbook Pro 15", late 2013 **(current)**
- iPhone 3GS
- iPhone 4S
- iPhone 5S
- iPhone 6 **(current)** (I swam with my iPhone 5S)

I plan on buying iPhone 7 when it comes out. There are rumors of a new MacBook Pro being launched in June, but I'll probably wait until the second generation, as the first generation has a tendency of having issues and my current device works perfectly.
