### ISSUE TITLE
What hobbies do you have besides programming?

### ISSUE THREAD

**Issue by robbbz** [sindresorhus/ama#37]
Like do you do sports or something like that?

**Comment by sindresorhus** [comment]
The only sport I do is to go to the gym and run. In the winter, I do some skiing.

I love photography. I have a [Nikon D610](https://www.google.no/search?q=nikon+d610&espv=2&biw=1440&bih=801&site=webhp&source=lnms&tbm=isch&sa=X&ei=CkeUVbjMNMubsgGCm5XgAQ&ved=0CAYQ_AUoAQ#imgrc=d_ub1f_TEBMC7M%3A) and an iPhone 6, which captures surprisingly good photos.

https://instagram.com/sindresorhus/
https://500px.com/sindresorhus
