### ISSUE TITLE
Crees que el aprendizaje en linea es el futuro de la educacion ?

### ISSUE THREAD

**Issue by aranajhonny** [sindresorhus/ama#372]
Sitios como Lynda.com , Platzi, Udacity, edx, treehouse  ... entre otros.
Tendrán estas plataformas lo que la universidad no enseña, cuál es su opinión .?

**Comment by sindresorhus** [comment]
I'm sorry. I don't speak Spanish.

**Comment by dthree** [comment]
> Do you think online learning is the future of education ?

**Comment by sotojuan** [comment]
In case you are still interested—he's asking if online learning is the future of education (sites like Udacity, Team Treehouse) and if they teach things universities do not.
