### ISSUE TITLE
Will you help me with my open source project?

### ISSUE THREAD

**Issue by unbug** [sindresorhus/ama#373]
I've noticed you when yeoman released. Really can't believe you've been so far.It's really a big thing to work on open source without a job.
I love make tools to help devs too.I've made MIHTool(mentioned on Google IO13 ), Codelf(naming things search engine for devs) and more on NPM.
I am current working on [DOMSnap](https://github.com/unbug/DOMSnap).
  >HTML5 provides LocalStorage, IndexedDB, and [window.caches](https://googlechrome.github.io/samples/service-worker/window-caches/) to build offline web apps.
But all of [these technologies](http://www.html5rocks.com/en/features/offline), we can't miss local database.
DOMSnap takes full advantage of [offline technologies](http://www.html5rocks.com/en/features/offline).
Storing HTML to local IndexedDB/WebSQL and resumeing when you're offline.
With DOMSnap, web pages can resume to their last state with less request to the server and less template render.
Think offline is a long way out, why not just give DOMSnap a try?

I believe DOMSnap is a valuable offline strategy to web apps, but  due to my real job,it's hard to take it further. Sometime I want quite my job to do those thing, to finished my roadmap for MIHTool, but the real world always stop me.
Will you help me with [DOMSnap - Roadmap](https://github.com/unbug/DOMSnap#roadmap--make-contributions)? Please.

**Comment by sindresorhus** [comment]
I don't even have enough time for my own projects these days, so unfortunately I can't really help you there. If you're looking for more contributors, make it easy to contribute. Have some good contribution guidelines and create some easy issues that people can get started with.

-

Btw, I remember when MIHTool came out. I thought it was really cool and bought it right away.

**Comment by unbug** [comment]
@sindresorhus Thank you anyway :)
