### ISSUE TITLE
How do you release to npm?

### ISSUE THREAD

**Issue by sarbbottam** [sindresorhus/ama#377]
I don't see a `.npmignore` in your repos, however the published module is very concise, for example [xo](https://github.com/sindresorhus/xo).

Do you use any custom release script?

<img width="704" alt="npmignore" src="https://cloud.githubusercontent.com/assets/949380/14237666/ed1be20c-f9db-11e5-8095-3ff2ea43b935.png">

**Comment by sindresorhus** [comment]
I use the [`files`](https://docs.npmjs.com/files/package.json#files) field in package.json to explicitly whitelist the files I want included in the package. I think this is much better than trying to ignore the files you don't want.

As for publish script, see https://github.com/sindresorhus/ama/issues/354.

**Comment by sarbbottam** [comment]
>I think this is much better than trying to ignore the files you don't want

Whitelisting is better in this case, wasn't aware, haven't RTFM 😐
