### ISSUE TITLE
Concerns about email spam?

### ISSUE THREAD

**Issue by sholladay** [sindresorhus/ama#379]
Aren't you worried that openly putting [your e-mail](https://github.com/sindresorhus/xo/blob/9fce4fb1a59abb28a47b2bbbc0ce3d922eb163ab/package.json#L9) in `package.json` will lead to [e-mail spam](https://twitter.com/mathisonian/status/562987276763148288)?

I have avoided doing this, despite wanting it to be easy for people to contact me. I am not convinced that [arms race](https://support.cloudflare.com/hc/en-us/articles/200170016-What-is-Email-Address-Obfuscation-) will ever really end. On the other hand, not ever posting your e-mail doesn't necessarily protect you and once its on one list, it may spread.

Are there any compelling reasons one way or the other beyond what I've mentioned? Are there any awesome tools that make good use of the e-mail field or don't work as well without one?

**Comment by sindresorhus** [comment]
Not really. My email has been public for years, but the Gmail spam filter catches close to everything. As far as I know the `email` field isn't used for anything other than contact info. Your email address ~~can be~~  [most likely have been] exposed many other ways though. From database leaks to dishonest services selling your email. So in the end, the only thing that matters is a good spam filter.
