### ISSUE TITLE
Do you have a girlfriend?

### ISSUE THREAD

**Issue by robbbz** [sindresorhus/ama#38]
Nothing in the readme stated I couldn't ask super personal questions :beers:

**Comment by sindresorhus** [comment]
> Nothing in the readme stated I couldn't ask super personal questions

It does now: https://github.com/sindresorhus/ama/commit/7da3bcf0f06aaf65ba5a58701a806d7762988f92 Definitely welcome ;)

-

Yes. Met her last year when traveling.

**Comment by paulirish** [comment]
> Yes. Met her last year when traveling.

:heart_eyes: :heartbeat: :love_hotel:
