### ISSUE TITLE
How did you make the gif in log-update?

### ISSUE THREAD

**Issue by bucaran** [sindresorhus/ama#382]
Hi @sindresorhus.

I have tried a few tools to create gifs for my own projects, for example licecap. It's free and easy to use.

I noticed the gif in https://github.com/sindresorhus/log-update and was blown away by its tremendously high quality.

What tool did you use to make this?

**Comment by sindresorhus** [comment]
I resized the terminal to fill the screen and bumped up the font size. QuickTime Player → File → New Screen Recording, and recorded the terminal animation. Opened the resulting movie in Photoshop and used the Animation panel to remove all non-unique frames and then sat the frame delay manually for each frame. I did all that to optimize the size of the GIF. Then exported the GIF and ran it through ImageOptim.

Usually I don't go through Photoshop though, but rather record with QuickTime Player and then edit and export with [GIF Brewery](http://gifbrewery.com).

**Comment by bucaran** [comment]
Impressive process. Thank you!

**Comment by lukechilds** [comment]
@sindresorhus If you fancy a CLI alternative to GIF Brewery I've neatened up the shell script I use and put it on GitHub, quality should be on par.

[lukechilds/gifgen](https://github.com/lukechilds/gifgen)

**Comment by sindresorhus** [comment]
@lukechilds It doesn't do cropping, trimming, or quality settings though, which are the main reasons I use GIF Brewery (Totally worth the price btw).

For CLI, I've heard [gifify](https://github.com/vvo/gifify) is pretty good.

**Comment by lukechilds** [comment]
@sindresorhus more settings to come, I only cleaned it up for public the other day ;)

Thanks for the link to `gifify`, it looks pretty cool. Looks like it just uses `ffmpeg`'s default palette though, so you get the typical GIF graphical artefacts that you can see in their demo GIF. `gifgen` creates a custom palette based on the input video to prevent this.

I'll deffo check out GIF Brewery 👍

**Comment by sindresorhus** [comment]
Instead of a huge GIF, check out [`svg-term`](https://github.com/marionebl/svg-term-cli), which renders the terminal to SVG.

**Comment by morajabi** [comment]
@sindresorhus launched [Gifski](https://github.com/sindresorhus/gifski-app) now!
