### ISSUE TITLE
GitHub repo traffic/stats screenshot

### ISSUE THREAD

**Issue by dawsonbotsford** [sindresorhus/ama#388]
Can we see a screenshot of the "referring sites" section on a repo like `trash`?

It would be a screenshot of [https://github.com/sindresorhus/trash/graphs/traffic](https://github.com/sindresorhus/trash/graphs/traffic)

**Comment by sindresorhus** [comment]
<img width="998" alt="screen shot 2016-05-20 at 01 09 58" src="https://cloud.githubusercontent.com/assets/170270/15404423/a03ac96a-1e27-11e6-84c2-046751329b7c.png">
