### ISSUE TITLE
GitHub AMA reader web app feedback?

### ISSUE THREAD

**Issue by akashnimare** [sindresorhus/ama#389]
I love reading AMAs. It's kind of annoying when I have to open each issue in a new tab. So I have made a little app [here](http://akashnimare.in/ReadAMA/). Any suggestions to improve this?
https://github.com/akashnimare/ReadAMA

**Comment by sindresorhus** [comment]
Good idea! :)

Some feedback:

- Should only list closed issues as those are the answered ones.
- Only display the author response, not other comments.
- Needs to render Markdown.
- The styling could use some work. The titles are the bright, making it hard to read. Maybe use Bootstrap or something.
- Drop the list numbers `1:`. It doesn't matter.
- `Github` => `GitHub`
- Don't capitalize the default username in the search input.
- It's currently pretty slow from clicking the title to seeing the comment. The moment the page has loaded, I would start preloading the comments in the background.
- Clicking a new title should close the previous, like an accordion widget.
- The headings need more line-height.
- Would be cool to list all the AMAs from https://github.com/sindresorhus/amas below the search on the front-page.
- When searching the URL should change, so I can copy the URL to get back to that user's AMA. Example: http://akashnimare.in/ReadAMA/sindresorhus

**Comment by akashnimare** [comment]
Oh man that's pretty detailed feedback. Thanks a lot. I'll be adding all those points you mentioned. :)

**Comment by amitmerchant1990** [comment]
Awesome idea!!

**Comment by akashnimare** [comment]
@amitmerchant1990 Thanks. If you want, you can contribute to the project [here](https://github.com/akashnimare/ReadAMA).
