### ISSUE TITLE
How do you balance your relationship with time spent on coding?

### ISSUE THREAD

**Issue by es128** [sindresorhus/ama#39]
well, you asked for it: 7da3bcf0f06aaf65ba5a58701a806d7762988f92

If the answer is yes, I may have some related follow-up questions.

**Comment by es128** [comment]
well turns out this is a dupe of #38, so follow-ups:

How do you balance your relationship with time spent on coding?

**Comment by sindresorhus** [comment]
From experience, the quality of the time spent together is more valuable than the quantity. The important thing is to *be there* when you *do* spend time together. I have coding time, and then I turn that part off completely and spend time doing other things with her.

To be specific. She works and [I don't at the moment](https://github.com/sindresorhus/ama/issues/14), so I've been spending that time in coffee shops coding and then spent time with her when she finishes work. Fitting in a lot of coding time with a relationship and busy life can be hard. You just have to make the [best use of "dead time"](https://github.com/sindresorhus/ama/issues/13#issuecomment-117798691) as possible and IMHO try to always prioritize real-life.
