### ISSUE TITLE
Why is your Hacker News username "mofle"?

### ISSUE THREAD

**Issue by sotojuan** [sindresorhus/ama#391]
It means "muffler" in Spanish, but I don't think that's why.

**Comment by sindresorhus** [comment]
It's just a word I invented when I needed a unique username for my Hotmail in 1998. Back then no one used their real name. Initially it was `mofle89`. I didn't realize it was a spanish word until a few years ago. I don't remember exactly why I chose to use it for Hacker News. Maybe for the freedom of being anonymous. I only use `sindresorhus` these days.
