### ISSUE TITLE
New Node.js Developer Advice

### ISSUE THREAD

**Issue by bcmarinacci** [sindresorhus/ama#392]
Hi,

I am a new Node developer and I wanted to write to thank you for everything that you have contributed to the Node.js community. I have used quite a few of your modules and I’ve learned heaps from reading your code. I was wondering if you have any advice for someone new to Node.js and to the industry in general?

**Comment by jamestalmage** [comment]
You are reading open source code, so you are doing a lot right already. 

My advise would be to contribute as much to open source as you can. Hunt through the GitHub issues of the modules you use for problems you think you might be able to solve, and make a PR. (See https://yourfirstpr.github.io/ for some great advice).

Don't be surprised if your first attempt at a PR is a little rough. It is *very* typical for first time contributors to have their PR's rejected or heavily critiqued. Hopefully, you find a team that is patient and will guide you through improving your code, or at least explain in detail why your approach was rejected. Go in expecting only a learning experience and you won't be disappointed.

I can say, without a doubt, that contributing to open source has made me a far better developer.
