### ISSUE TITLE
How do you host your server-side Node.js apps?

### ISSUE THREAD

**Issue by Rowno** [sindresorhus/ama#394]
Do you use a PaaS provider (e.g: Heroku, Modulus) or do you do it yourself (e.g: Digital Ocean, AWS)?

**Comment by sindresorhus** [comment]
I'm averse to doing too much devops, so Digital Ocean or AWS is not really something I would use unless I really had to. I've mostly been using Heroku for the past years, but not very happy it lately. For future projects I will use [`now`](https://zeit.co/now). [`Apex`](http://apex.run) also looks awesome, but haven't done any projects with it yet.

**Comment by Rowno** [comment]
Nice. Do you know what database service you'd use with Now for data persistence?

**Comment by sindresorhus** [comment]
That really depends on the type of app I'm creating, but [PostgreSQL](https://www.postgresql.org/) works for most use-cases. I would also like to try out [RethinkDB](https://www.rethinkdb.com/), but it would have to be for a suitable project.

**Comment by serapath** [comment]
Do you sometimes use services like https://www.firebase.com/ or https://auth0.com/ ?
Do you know other similar services?
...especially some solutions that are freemium, so hosting free open source tools for others to use does not create maintainance costs...

**Comment by sindresorhus** [comment]
Firebase looks awesome on paper and they have a great API, but I'm a bit scared of the lock-in. Would definitely use Auth0.

**Comment by serapath** [comment]
thx :-)

**Comment by jamestalmage** [comment]
> Firebase looks awesome on paper and they have a great API, but I'm a bit scared of the lock-in

I have used Firebase for a number of personal projects, and it is just awesome. Personally, I wouldn't fear the lock-in. If you reach the point where your monthly bill from Firebase is a concern, well then congratulations - you have got a killer app! You could certainly be strategic about how you structure your App and data-structures so the Firebase database is abstracted away. Really, that's good practice no matter which database you use.

Firebase Auth is really awesome as well, I would use Firebase just for that, even if I didn't need / want the database service.

**Comment by serapath** [comment]
I'm wondering if `ipfs` or `dat` could be used instead of `firebase` :-)
