### ISSUE TITLE
How many Electron based apps are running on your laptop?

### ISSUE THREAD

**Issue by egoist** [sindresorhus/ama#399]
and what are they?  😳

**Comment by sindresorhus** [comment]
5 apps. [Anatine](https://github.com/sindresorhus/anatine), [Caprine](https://github.com/sindresorhus/caprine), [HyperTerm](https://github.com/zeit/hyperterm), [WebTorrent](https://github.com/feross/webtorrent-desktop), [Atom](https://atom.io).
