### ISSUE TITLE
When are you coming to London?

### ISSUE THREAD

**Issue by passy** [sindresorhus/ama#4]
@addyosmani and I are waiiiting! :watch:

**Comment by robbbz** [comment]
Let me know when you're coming to Sweden. Would like to meet you for real life.

**Comment by hemanth** [comment]
Related issue #9  @passy :+1:

**Comment by fahad19** [comment]
when in Amsterdam? :D

**Comment by arthurvr** [comment]
Hey don't forget Belgium too!

**Comment by stephenplusplus** [comment]
Michigan! We can ride bikes and say what we think clouds look like!

**Comment by fnky** [comment]
How about Denmark? :dancers:

**Comment by brunowego** [comment]
Brazil is a good place to visit :metal:

**Comment by addyosmani** [comment]
Srsly. You should drop by soooon :train2:

**Comment by insanehong** [comment]
How about Republic of Korea? :D

**Comment by najela** [comment]
Cameroon is a Wonderfull country to visit.

**Comment by sindresorhus** [comment]
Hah. I want to visit all these places! :)

I was planning to travel to London soon, but my passport is in the mail on the way to an embassy. So I won't be able to travel for a couple of weeks. And after that I'm going to Asia again until Desember. Maybe next year...

**Comment by nicolasbrugneaux** [comment]
That'd be awesome to see you in Berlin!
