### ISSUE TITLE
Why do you think some old programming paradigms are resurfacing so suddenly now? 

### ISSUE THREAD

**Issue by eshansingh** [sindresorhus/ama#400]
Things like FRP, FP, RP, all the other P's... why aren't people satisfied with OOP?

**Comment by sotojuan** [comment]
@eshansingh Just FYI functional programming and reactive programming are older than OOP. FRP was formalized in 1997, so it's not new either.

I think you should be asking "why are a lot of non-OOP paradigms getting popular now?" or something.
