### ISSUE TITLE
What do you make in USD?

### ISSUE THREAD

**Issue by f00Dev** [sindresorhus/ama#402]
Hello Sindre,

What do you make in the industry, and do you feel that your salary commensurate's with your experience?

Thanks!

**Comment by sindresorhus** [comment]
$0. I'm currently [funemployed](https://blog.sindresorhus.com/about-sindre-sorhus-42786d2e191b#.8mh5153mx). Salaries in our industry is generally very good though.

**Comment by f00Dev** [comment]
Hi Sindre,
I have a doubt. So how is it that you earn a living? You must be freelancing and charging some hourly rate?

**Comment by sindresorhus** [comment]
I don't. [I'm still living off savings.](https://github.com/sindresorhus/ama/issues/383)
