### ISSUE TITLE
Why not use Patreon?

### ISSUE THREAD

**Issue by ivanakimov** [sindresorhus/ama#405]
I have no affiliation with [patreon](https://www.patreon.com/), just saw [this guy](https://www.patreon.com/evanyou) and thought of you. Since your life is OSS anyway, why not complement it with some income?

**Comment by stephenplusplus** [comment]
@sindresorhus, you should open one up 🍰 🍴

*Inspired by https://twitter.com/browserling/status/938930493554397184*

**Comment by sindresorhus** [comment]
Thanks for the push, Stephen 🙌

I have finally done it: https://twitter.com/sindresorhus/status/941032894964883457
