### ISSUE TITLE
How do you handle the a$$hat user that think you work for him?  

### ISSUE THREAD

**Issue by mikeerickson** [sindresorhus/ama#409]
Scenario

A a$$hat users company has a "mission critical" application that relies on one of your OSS packages.  Instead of attempting to fix and PR the code, he gets all pissy with you.

My feeling is that this is "misplaced anger" but still takes it out on you and expects you to fix your FREE code immediately.

**Comment by sindresorhus** [comment]
It used to affect me, but not much anymore. I have learned to not let random stranger on the internet affect my emotions. I just ignore anything emotional in issues and look at the issue at hand.
