### ISSUE TITLE
How profitable is it to mainly work on Open Source projects instead of working for a company with fixed income?

### ISSUE THREAD

**Issue by arnoldstoba** [sindresorhus/ama#41]

**Comment by sindresorhus** [comment]
If you mean profitable in the form of money, it's not. I don't earn anything from doing Open Source.

Open Source has however been the most profitable thing I've ever done in terms of learning, both coding and people skills, making cool stuff, and bonding friendships. I would argue that's a lot more important than money. It's not an alternative to a full-time job for most though ([including me](https://github.com/sindresorhus/ama/issues/14)), just an awesome addition.
