### ISSUE TITLE
What is your average monthly bill in Asia?

### ISSUE THREAD

**Issue by jfmengels** [sindresorhus/ama#414]
Linked to the discussion in https://github.com/sindresorhus/ama/issues/383#issuecomment-242185623

You said that money lasts longer in Southeast Asia, but I'm curious as to how much it costs. What would you guess to be your average monthly bill? I'm keeping in mind that you don't buy a lot of stuff.

**Comment by sindresorhus** [comment]
Guesstimate:

- Rent: $500 (The apartment I rent is as central as it could get. You can get something nice for half that if you're willing to travel 15-20 min to the city core of Bangkok. Apartments are also much cheaper outside the city.)
- Food: $600 (I eat out every day because food is so cheap here)
- Transport: $80 (Taxis)
- Fun: $120 (Cinema, partying, etc)

Total: $1300

**Comment by akashnimare** [comment]
@sindresorhus you could live a luxury life in India in around $800 🚀 .

**Comment by AchoArnold** [comment]
@akashnimare Luxury is subjective ;)

**Comment by akashnimare** [comment]
@AchoArnold true that 💯 .

**Comment by sindresorhus** [comment]
@akashnimare I don't care about luxury, but I do love Indian food, so maybe one day.

**Comment by akashnimare** [comment]
@sindresorhus from luxury, I mean a 

> chilling place + great culture + awesome local food

Indian food is 🔥  ❤️ .

**Comment by bharathvaj1995** [comment]
@sindresorhus If you have time, Please visit India.

**Comment by JSterling8** [comment]
I don't get why everyone wants you to visit India. From someone who has lived in Thailand for about a year, and been around India for about a month in 2016, Thailand is *FAR* better. Like it's not even close. In India, 8 people tried to scam me in one day. In Thailand, nobody has *EVER* tried to scam me. India was such a rip off. I went to Goa, New Delhi, Agra, and Srinagar, and somebody tried to rip me off everywhere I went. If you're white, you're screwed. You're just seen as a walking ATM machine. Sad!

**Comment by bharathvaj1995** [comment]
@JSterling8 See India is a diversified country, within Indian states itself there are n number of differences. From the places you have mentioned I see you have visited only few places where they will treat even other tourists as an ATM machine. Even i was screwed during my summer vacation to Goa. If you have visited any Southern cities, you would have not commented like this. The reason why we (techies) want Sindre and others to visit India is to give a presentation or speech to develop the Open source and develop the JS community. That's it. By the way I'm sorry for the inconvenience caused during your trip to India.

**Comment by theodesp** [comment]
Hey, I could argue that cooking from home could save you dollars. I could live with 150 euros per month (190-200$). Maybe you could give it a try.

**Comment by sindresorhus** [comment]
@theodesp True, but I don't even have a kitchen.

**Comment by lukechilds** [comment]
Depending on where you live in Thailand, cooking at home can be more expensive than eating out.

**Comment by sindresorhus** [comment]
Groceries are pretty expensive in Bangkok unless you go to the local food markets.

**Comment by franciscop-invast** [comment]
The first time I was in Chiang Mai, we had a good plate of noodles in a local market for the astonishing price equivalent of $0.80. Most foreigners I've seen like to go _every day_ to the fancy and trendy cafes, which I will never understand :man_shrugging:

**Comment by wendzhue** [comment]
Electricity seems to be quiet expensive in southeast Asia.
