### ISSUE TITLE
What is the tool you use to create awesome logos?

### ISSUE THREAD

**Issue by romuloalves** [sindresorhus/ama#416]
Some friends said me about Pixelmator and others about Affinity Design.

I'm curious, what tool do you use?!

Thanks!

**Comment by sindresorhus** [comment]
Duplicate of https://github.com/sindresorhus/ama/issues/142. In short, [Sketch](https://www.sketchapp.com) and [Illustrator](http://www.adobe.com/products/illustrator.html).
