### ISSUE TITLE
What domains do you own?

### ISSUE THREAD

**Issue by dervondenbergen** [sindresorhus/ama#417]
I just saw this tweet: https://twitter.com/sindresorhus/status/770232614179446784

So I thought, how many Domains do you actually own?
And what are the weirdest/cooles/dumbes ones?

**Comment by sindresorhus** [comment]
Active:

- [sindresorhus.com](https://sindresorhus.com)
- [ava.li](https://ava.li)
- [awesome.re](https://awesome.re)
- [node.cool](https://node.cool)

Not used yet:

- [dull.io](https://dull.io) (Probably dullest domain I own)
- [ponyfill.com](https://ponyfill.com)  [(More info)](http://svdictionary.com/words/ponyfill)
- [devtools.io](https://devtools.io)
- [yobird.com](http://yobird.com)
