### ISSUE TITLE
What are your thoughts on Elm's future?

### ISSUE THREAD

**Issue by justinvdm** [sindresorhus/ama#421]
People seem to be talking quite a bit about [Elm](http://elm-lang.org). Even with its [js interop](http://guide.elm-lang.org/interop/javascript.html) though, it still seems a bit outside of the rich and growing js ecosystem. Considering your knowledge of and contributions to the ecosystem, what are your thoughts on how this would influence how it grows as a lang for web apps?

**Comment by sindresorhus** [comment]
Elm is an interesting language that has gotten a lot of things right. My experience with it is extremely limited. I have only ever tried making a tiny todo example app with it, so take my opinion with a grain of salt. I doubt it will ever become a mainstream front-end language though, but I hope to be proven wrong. WebAssembly could potentially change everything. Personally, I'm hoping to be able to use Swift on the front-end at some point, through WebAssembly.
