### ISSUE TITLE
My colleague debated me because of the one-line function and I need your opinion  

### ISSUE THREAD

**Issue by saadshahd** [sindresorhus/ama#425]
Hey @sindresorhus

My colleague debated me after reviewing this snippet of code and said It's:
- Redundant code
- LOC
- Oversimplification

The snippet I added:

``` javascript
function isValidEmail(email) {
  return emailRegex.test(email);
}

const emailsAreValid = emails.every(isValidEmail);
```

And after the changes he requested:

``` javascript
const emailsAreValid = emails.every(email => emailRegex.test(email));
```

**Comment by ikhattab** [comment]
I believe this is a good practice as illustrated by @mpj in https://youtu.be/BMUiFMZr7vk?t=502

**Comment by sapegin** [comment]
I’d make it even simpler:

```js
const isValidEmail = email => emailRegex.test(email);
const emailsAreValid = emails.every(isValidEmail);
```

**Comment by juliangruber** [comment]
a good argument for not having the logic in a single line is for clean git diffs: if you want to change the implementation of `isValidEmail` to for example do more than just a regex check, you can do that without affecting the implementation of `emailsAreValid` and thus cluttering diffs.

**Comment by v-braun** [comment]
your change make sense if you don't need the `ìsValidEmail`.
the only reason to keep (and use) it wold be -> debugging. you can set breakpoints within and debug each email. but this function is simple enough to check it within the console.

@juliangruber: you're right but would it not be better to extract it into a function when you has the requirement (do more than a regex check)? 
 [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it)!

**Comment by saadshahd** [comment]
@v-braun Then when I'll do extract it. I'll get the cluttering diffs and because I need to prevent them from showing up the YAGNI becomes invalid at this case. What do you think?

**Comment by chentsulin** [comment]
I'd try to keep naming consistence:

rename `emailsAreValid` to `areValidEmails`

```js
const isValidEmail = email => emailRegex.test(email);
const areValidEmails = emails => emails.every(isValidEmail);
```

Also pass emails as argument which make it easier to test.

Eventually, I'd replace `isValidEmail` with 3rd party libs because I don't want to test every email validation case myself.

```js
import isValidEmail from '3rd-party-libs';

const areValidEmails = emails => emails.every(isValidEmail);
```

**Comment by saadshahd** [comment]
@chentsulin It's nicer to take the snippet step further with the one-line function and importing the 3rd part lib is much much nicer.

But I got two questions:

- Why do you prefer the one-line deceleration `() => { code }` or even `function () { code }`  even if it produces cluttering diffs in the case of scaling?

- What do you prefer when naming a variable that contains the result of invoking the `areValidEmails(emails)`  would you name it `emailsAreValid` or something else?

**Comment by v-braun** [comment]
@saadshahd great YAGNI argument! 
Have a look at this tools: http://unix.stackexchange.com/a/11144 maybe that helps.
@chentsulin realy nice idea with the 3rd party lib!

**Comment by sindresorhus** [comment]
@saadshahd Yours is better if `isValidEmail` is reused, otherwise I would have inlined it too. Though, both ways are totally valid, and are indeed easy targets for bikeshedding.

I would personally have done it this way:

```js
const areValidEmails = emails => emails.every(email => emailRegex.test(email));
```

That being said, the only correct way to "validate" emails without actually sending an email is:

```js
const areValidEmails = emails => emails.every(email => email.includes('@'));
```

Emails are super complex and ambiguous. You should never try to validate them with any kind of regex. Send a confirmation email instead. I've given up on using `sindresorhus+identifier@gmail.com` because of all the idiot regex validators failing on it. Did you know that even nested comments are allowed in emails?
