### ISSUE TITLE
What's your workflow for capturing screenshots for your repos?

### ISSUE THREAD

**Issue by charlespeters** [sindresorhus/ama#428]
In a lot of your repos, you have a lot of screenshots, like [pure](https://github.com/sindresorhus/pure) and [hyper-snazzy](https://github.com/sindresorhus/pure). what's your workflow for making screenshots?

**Comment by Youmoo** [comment]
@charlespeters [licecap](http://www.cockos.com/licecap/) is very easy to use.

**Comment by sindresorhus** [comment]
Let's focus on capturing screenshots of command-line output on macOS. That's what I most often do. I use [Hyper](https://hyper.is) with the [hyper-snazzy](https://github.com/sindresorhus/hyper-snazzy) theme and [Pure](https://github.com/sindresorhus/pure) prompt, to get a nice and minimal looking output. I make the terminal window larger than normal, as it's supposed to fill the readme width (888px), and I increase the font size to around 30px, depending on the content. To capture a screenshot of the window, I press <kbd>Cmd</kbd> <kbd>Shift</kbd> <kbd>4</kbd> and then click it. Afterwards, I run the screenshot through [ImageOptim](https://imageoptim.com/mac) to make it smaller. I then put it in the readme with the `<img>` tag, so I can control the width. This is important, as we want the image to be retina (High DPI), so we need to set the width to half the size of the image. For example, `<img src="screenshot.png" width="1100">`, for an image that is 2200px wide.

For capturing GIFs, I have a similar process, but use either [Kap](https://getkap.co) (I recently switched away from LICEcap) or QuickTime Player, depending on how much control I need over the video. I've described my QuickTime workflow in https://github.com/sindresorhus/ama/issues/382#issuecomment-215694358.
