### ISSUE TITLE
Have you tried jsblocks?

### ISSUE THREAD

**Issue by solancer** [sindresorhus/ama#438]
Is it really faster than React?

http://jsblocks.com

**Comment by SamVerschueren** [comment]
I haven't used it but just wanted to chime in here. I never heard of it before so I went to the website and noticed the performance graphs. I even downloaded the zip file to see what's in there. I highly doubt that the chart is even correct. First of all, they used Angular 1 to do the benchmarks. Second of all, they didn't do any of the production optimisation tricks like ahead of time compilation (I think it's called template compilation in React). Benchmarks are easily tricked, I wonder how good it scales and performs in a real world example. Just my 2 cents...

<img width="1431" alt="screen shot 2017-01-18 at 14 07 03" src="https://cloud.githubusercontent.com/assets/1913805/22065206/7d6762a2-dd87-11e6-9527-ad71bfacd33c.png">

**Comment by sindresorhus** [comment]
I haven't tried it and I don't think I will. Frameworks don't excite me, so if I need one, I'll just go with something proven like Vue or React. I'm too doubtful about the performance claims, and it seems we're not alone: https://news.ycombinator.com/item?id=9642548 https://www.producthunt.com/posts/jsblocks
