### ISSUE TITLE
Why don't you add TypeScript type definitions to your modules?

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/ama#439]
Could you please answer this once and for all so I can link the answer to people who are doing a PR and trying to add it. I know your statement but people want to hear it from you if I answer them "add it to DefinitelyTyped".

**Comment by jfmengels** [comment]
Same thing about Flow types :)

**Comment by sindresorhus** [comment]
I use neither TypeScript nor Flow in my small modules as I don't yet see enough value. If I were to accept type definitions, I would have to maintain them. Which I would do badly. I would say bad definitions are worse than none. [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) and [flow-typed](https://github.com/flowtype/flow-typed) are good solutions to this problem.

That being said, I do accept type definitions in larger projects when it makes and someone offers to maintain them. For example, we have both [TypeScript](https://github.com/avajs/ava/blob/master/types/base.d.ts) and [Flow](https://github.com/avajs/ava/blob/master/index.js.flow) type definitions in [AVA](https://ava.li). Also, a while back, I adopted Flow in the [Pageres codebase](https://github.com/sindresorhus/pageres/blob/master/lib/index.js).

**Comment by sindresorhus** [comment]
I initially didn't want TypeScript definitions in my packages as I didn't use TS so I wouldn't be able to maintain the definitions and I felt TS was too immature. These days I'm using TS more and with TS 3 its become a lot more mature, so I have decided to start accepting TypeScript type definitions for my packages.

Please follow this guide when submitting a type definition: https://github.com/sindresorhus/typescript-definition-style-guide

**Comment by NeekSandhu** [comment]
Glad to have you on board 😌
