### ISSUE TITLE
How did you meet your open source friends?

### ISSUE THREAD

**Issue by robbbz** [sindresorhus/ama#44]
I see that you're doing much work together with some small group of people with a really similar mindset, such as @kevva @addyosmani and @arthurvr. You seem to be working together on all the things. How did you get to meet those?

**Comment by addyosmani** [comment]
We basically never leave him alone. He helps with our projects out of a keen sense of pity :)

**Comment by sindresorhus** [comment]
I met them through open source projects, surprise surprise. Most of them through Yeoman and TodoMVC. I've only met @addyosmani and @passy in real life though.

-

[How I met Addy.](https://github.com/sindresorhus/ama/issues/49)
