### ISSUE TITLE
Are you exploring new ways to monetize your OSS work?

### ISSUE THREAD

**Issue by mischah** [sindresorhus/ama#440]
Hej Sindre,

I just stumbled upon the second repo of yours which has a teaser to @wesbos great ES6 course:

> ![image](https://cloud.githubusercontent.com/assets/441011/21244812/95f6e7de-c31f-11e6-8ba2-f9a4a17c3999.png)

Out of curiosity: Are you exploring new ways to monetize your OSS work? Or is it just a friendly way to support something you like?

Cheers, Michael

**Comment by es128** [comment]
It's quite clearly sponsored, even says so in the content.

https://github.com/sindresorhus/awesome-nodejs/commit/4673450593c581f4a9824e68822f1b2f18bec90a#diff-0730bb7c2e8f9ea2438b52e419dd86c9R12

It's also targeted, relevant, and doesn't detract from the primary content.

**Comment by mischah** [comment]
Thanks. Didn’t see the `title` attribute. 🙈

**Comment by wesbos** [comment]
Yep!  I pay 40% of profits to a few OSS authors - it's a nice way for them to make some money from  their hard work

**Comment by mischah** [comment]
Wow. Thanks for the info.

**Comment by sindresorhus** [comment]
> Are you exploring new ways to monetize your OSS work? Or is it just a friendly way to support something you like?

Both

**Comment by nhquiroz** [comment]
Have you tried **[Patreon](https://www.patreon.com/)** or **[Open Collective](https://opencollective.com/)**?

**Comment by sindresorhus** [comment]
@nhquiroz I'm gonna answer that in https://github.com/sindresorhus/ama/issues/405.

**Comment by sindresorhus** [comment]
I'm now on Patreon: https://www.patreon.com/sindresorhus
