### ISSUE TITLE
When were you born? What was your first and most memorable experience that pushed you off the deep end of programming?

### ISSUE THREAD

**Issue by chuckxD** [sindresorhus/ama#441]
I'll go first. Not sure how your date of birth has never been asked or possibly asked just not answered. 

>When were you born? 

```javascript
const __dob = new Date(1983, 7, 11, 4, 20, 42, 69).toLocaleString('en-US');
alert(__dob);
```

>What was your first and most memorable experience that pushed you off the deep end of programming?

AOL progs/warez mischief, exploring and memorizing random alt-codes, and augmenting my AIM IM output in HTML, which eventually led to static web-pages and many other web related projects (E/N) while socializing and trolling various chat interfaces such as ICQ, IRC, and Yahoo Chat. Started pumping out a lot between 15-16 years old.

**Comment by sholladay** [comment]
You can open multiple unrelated issues you know. :p

See https://github.com/sindresorhus/ama/issues/43 for the age question.
