### ISSUE TITLE
How do you manage so many repos?

### ISSUE THREAD

**Issue by LukeSheard** [sindresorhus/ama#443]
You have over 800 repos on Github now, and many published NPM modules. What strategy do you use for managing so many?

**Comment by roccomuso** [comment]
+1

**Comment by revelt** [comment]
I suspect [np](https://www.npmjs.com/package/np) is one of the tools. Is that true?

**Comment by sindresorhus** [comment]
I use `np` to publish, which simplifies that bit. But there is also a lot of manual work. I manually write my release notes (not just dumping the list of commits). I also have a lot of scripts I use to ensure consistency and quality (many written by ChatGPT).
