### ISSUE TITLE
What is Lungo?

### ISSUE THREAD

**Issue by gdborton** [sindresorhus/ama#445]
And when is it coming out?

https://twitter.com/sindresorhus/status/768509012795125760

**Comment by sindresorhus** [comment]
It's a macOS app I've been working on. Planning to release it soon.

Another teaser here: https://twitter.com/sindresorhus/status/836659479210950656

I'll close this issue when the app is out ;)

**Comment by ahmadawais** [comment]
Looking forward!

**Comment by ahmadawais** [comment]
Is it out? You closed the issue!

**Comment by sindresorhus** [comment]
It's out: https://twitter.com/sindresorhus/status/890273353063333890
