### ISSUE TITLE
Do you know of an npm package that implements paged stdout?

### ISSUE THREAD

**Issue by floydpink** [sindresorhus/ama#447]
Do you know of any npm module that can be used to page the output in my node cli app?

I am looking for behavior similar to `git log` that keeps showing one page at a time of its output - <kbd>Space</kbd> to advance, <kbd>B</kbd> to go back and <kbd>Q</kbd> to quit.

**Comment by SamVerschueren** [comment]
Just pipe it to`less`?

**Comment by floydpink** [comment]
Thank you, @SamVerschueren - that is an option that was considered but did not work because regular Windows command prompt does not have `less`.

**Comment by SamVerschueren** [comment]
Didn't all devs switched to bash for Windows yet? Just wondering...

**Comment by sindresorhus** [comment]
Check out [`cash`](https://github.com/dthree/cash) which comes with a `less` command, although I would recommend just getting [Bash for Windows](https://msdn.microsoft.com/en-us/commandline/wsl/about).
