### ISSUE TITLE
Have you ever come to Indonesia ?

### ISSUE THREAD

**Issue by sqfreakz** [sindresorhus/ama#448]
Come here maybe, we have the best food Rendang, you must try it

**Comment by RichardLitt** [comment]
He has! That's where I met him, in Bali. I think he's also been to Java.

**Comment by sqfreakz** [comment]
@RichardLitt oh i see, i am at east java btw.

**Comment by sindresorhus** [comment]
Yes, I traveled in Bali and Jogja about two years ago (April 2015). Bali was especially beautiful! I tried Rendang, and I also had very good Oxtail soup and Nasi goreng in Jogja. I will definitely travel to Indonesia again.

What other places in Indonesia would you recommend?

---

Here are some pics from my travels:

## Bali

![img_5364](https://cloud.githubusercontent.com/assets/170270/22876503/961901ee-f203-11e6-854e-4c1432371bc3.jpg)


![11055548_1378406259151123_1592972421_n](https://cloud.githubusercontent.com/assets/170270/22875870/7974a730-f200-11e6-9d1c-6bf85d94b019.jpg)
⬆️ https://www.instagram.com/p/0ufAwZoUGC/

![10549861_686183391507465_1751567371_n](https://cloud.githubusercontent.com/assets/170270/22875867/78a9fe86-f200-11e6-9013-250524bb4a29.jpg)
⬆️ https://www.instagram.com/p/0pkGs1oULn/

![10561211_383349898532195_983997807_n](https://cloud.githubusercontent.com/assets/170270/22875871/79884592-f200-11e6-96ba-5c2c75686cf5.jpg)
⬆️ https://www.instagram.com/p/1AknAEoUDN/

![11049348_779145045526798_1784961848_n](https://cloud.githubusercontent.com/assets/170270/22875869/7970a0ae-f200-11e6-98f1-9a3bfacd874f.jpg)
⬆️ https://www.instagram.com/p/00DxWwIUL8/

![img_5212](https://cloud.githubusercontent.com/assets/170270/22876713/89219860-f204-11e6-902e-c693bdcb9fa7.jpg)

![img_5283](https://cloud.githubusercontent.com/assets/170270/22876717/9210457a-f204-11e6-928a-049f6a101c76.jpg)


[![screen shot 2017-02-13 at 15 48 09 copy](https://cloud.githubusercontent.com/assets/170270/22876613/22369c18-f204-11e6-95b5-315142124ce7.jpg)](https://www.instagram.com/p/1SbdZHoUJ0/)
*(Click to play)*



## Jogja

![1530811_1557946131145544_1464612831_n](https://cloud.githubusercontent.com/assets/170270/22875866/788d60e6-f200-11e6-984e-c51856aff4bf.jpg)
⬆️ https://www.instagram.com/p/0kUX35oUPO/

![11098745_893524110670443_1587813881_n](https://cloud.githubusercontent.com/assets/170270/22875868/79240bd6-f200-11e6-93b9-048b8d398518.jpg)
⬆️ https://www.instagram.com/p/03IVVMIUOi/

![img_5113 1](https://cloud.githubusercontent.com/assets/170270/22876731/a1363398-f204-11e6-8a53-404e60696fd3.jpg)

![img-20150318-wa0006](https://cloud.githubusercontent.com/assets/170270/22876736/a8db6618-f204-11e6-8d33-17eb4df091ed.jpg)

![img-20150318-wa0005](https://cloud.githubusercontent.com/assets/170270/22876735/a8a964ba-f204-11e6-9a56-fa754ac99564.jpg)


![img_5128](https://cloud.githubusercontent.com/assets/170270/22876732/a146bc7c-f204-11e6-8cba-0d33f1ab617a.jpg)

**Comment by sqfreakz** [comment]
emm, maybe the gili island at Lombok, or Raja Ampat at Papua, those two is the most beautiful place to diving & snorkeling. 

Im dont often traveling, so i dont know what place to recommend. 😄

**Comment by ocombe** [comment]
I loved the gili islands :)
I was in bali in 2014 and it was very nice!
