### ISSUE TITLE
How do you keep yourself updated on technology?

### ISSUE THREAD

**Issue by sarbbottam** [sindresorhus/ama#45]

**Comment by sindresorhus** [comment]
I have a lot of RSS feeds I keep up with daily. I also read Hacker News, though it has really gone downhill the past years... Twitter is probably where I get the most useful updates, from the people I follow.

When it comes to keeping my skills up with the latest technologies, I try to set aside some time once in a while and experiment with those technologies by making something fun. Like with Web Components, I made a component, with React you could make a tiny web app.

People I follow on Twitter: https://twitter.com/sindresorhus/following
RSS feeds I subscribe to: http://opmlviewer.com/Viewer/?https://github.com/sindresorhus/stuff/raw/master/feeds.xml
