### ISSUE TITLE
What terminal do you use?

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/ama#458]
Terminal, plugins, font, ...

**Comment by SeanHub** [comment]
[https://blog.sindresorhus.com/answering-anything-678ce5623798#.t2pu98dtu](https://blog.sindresorhus.com/answering-anything-678ce5623798#.t2pu98dtu)

Scroll down to 'What is your dev environment?'

**Comment by sindresorhus** [comment]
<img width="869" alt="screen shot 2017-03-28 at 20 29 22" src="https://cloud.githubusercontent.com/assets/170270/24407491/42e0dae2-13f5-11e7-9aaa-f49f6fa9425a.png">

I mainly use [iTerm2](https://www.iterm2.com), but also [Hyper](https://hyper.is) (Mostly just for screenshots/gifs). I want to use Hyper exclusively, but it doesn't yet have a good [visor mode](http://apple.stackexchange.com/questions/48796/iterm-as-a-slide-out-terminal-from-the-top-of-the-screen). For the shell I use [ZSH](https://en.wikipedia.org/wiki/Z_shell) with my own terminal prompt [Pure](https://github.com/sindresorhus/pure) and the [Snazzy](https://github.com/sindresorhus/iterm2-snazzy) theme with the Menlo font. I use the [`zsh-syntax-highlighting`](https://github.com/zsh-users/zsh-syntax-highlighting) plugin to have commands highlighted and the [`zsh-autosuggestions`](https://github.com/zsh-users/zsh-autosuggestions) plugin to auto-complete commands.

**Comment by perryprog** [comment]
Sorry for the necro, but
> I want to use Hyper exclusively, but it doesn't yet have a good visor mode.

[This one is OK.](https://www.npmjs.com/package/hyperterm-visor)

However, there is a bit (large bit) of speed difference between Hyper and iTerm2.  In the video below, Hyper is first, followed by iTerm2. I'm pretty sure Hyper is slow because of Electron, and the way it outputs the text, not the actual running of the command.

[Video.](https://www.youtube.com/watch?v=2HjtSMADpgU)

**Comment by Glennmen** [comment]
@sindresorhus Sorry old issue, but I was wondering if you use any zsh plugin manager (zinit for example) or plugin zsh source in `.zshrc`?
Interested in your setup to manage your zsh plugins.

**Comment by sindresorhus** [comment]
@Glennmen No, I never found any that I like. I just install ZSH plugins with Homebrew and `source` everything else.
