### ISSUE TITLE
What do you think will be the top trends of 2017?

### ISSUE THREAD

**Issue by jpls93** [sindresorhus/ama#459]

**Comment by sindresorhus** [comment]
Some quick thoughts: The top trends of 2017 will be Machine Learning, Augmented Reality, and Virtual Reality. Clear signs of this with recent focus by Apple, Google, and Facebook. IoT will finally focus on better security and get some mainstream foothold. We'll see AI mentioned everywhere, but practically most of it will just be marketing talk. Voice assistants, like Amazon Echo and the new Apple HomePod, will be popular, but mostly just for simple things like controlling music. The mass market is still uncomfortable talking to a device. We’ll see more of all-in-one apps like WeChat outside of China. You can see signs of this with Facebook integrating marketplaces and payments. Internet privacy will become important even to normal users as governments continue coming up with privacy intrusive laws. Bitcoin will see growth and stability as large actors start adopting it. We'll see a lot of new cryptocurrencies, but most of them will be [Ponzi schemes](https://simple.wikipedia.org/wiki/Ponzi_scheme). Blockchains will be used in creative non-cryptocurrency ways. There will be some major devastating cyberattacks.

**Comment by garytse89** [comment]
You sir, are a prophet.
