### ISSUE TITLE
Favorite things and other personal questions

### ISSUE THREAD

**Issue by robbbz** [sindresorhus/ama#46]
Let's see if I can really ask you *anything*. What's your phone number? What you do like to eat? Favorite television shows? Color of your underwaer?

:beers:

**Comment by sindresorhus** [comment]
> Let's see if I can really ask you anything.

I'm disappointed this is the craziest you can come up with :p :cocktail: 

> What's your phone number?

+4748414172

> What you do like to eat?

Lasagne, Taco Pie, Pizza, Tom Yum Kung, Green curry.

> Favorite television shows?

My current favorites are House of Cards, Strike Back, Humans.

All time favorites are Stargate Atlantis, Stargate SG1, Arrested Development, Friends.

> Color of your underwear?

Black.

**Comment by sarbbottam** [comment]
>>Tom Yum Kung, Green curry.

Thai cuisine is delicious, where did you taste them first?

**Comment by sindresorhus** [comment]
A local restaurant in Bangkok. Don't think it had a name.

**Comment by fritx** [comment]
Amazing!

**Comment by robbbz** [comment]
> Color of your underwear?
>> Black.

How about today?

**Comment by sindresorhus** [comment]
> How about today?

Superman boxer.

**Comment by nickedes** [comment]
haha LOL :joy:

**Comment by nickedes** [comment]
@sindresorhus How about today? :astonished:

**Comment by noffle** [comment]
Seems like people are really interested in your underthings. Might as well set up an RSS feed.

**Comment by harshasrinivas** [comment]
:joy: haha
