### ISSUE TITLE
What do you think about Colleges?

### ISSUE THREAD

**Issue by ritiek** [sindresorhus/ama#463]
Hi Sindresorhus!

Just wanted to know what you think about colleges and degrees specifically in Computer Science.

As a note, I'm from India and here the society thinks that you need to get into the top colleges to become something worth and I'm really bad at all my subjects: math, chemistry and physics.. I have my exam coming up soon that will decide my college.
I'm really passionate and self-motivated to coding and always hungry to learn more.

Is that enough to make something good out of a person?

Thanks!

**Comment by denysdovhan** [comment]
@Ritiek hi!

I'm 20yo and studying at university in Ukraine (computer science). I was wondering about such things too. To be honest, I feel like I became even more stupid than I was at school. Yeah, we're learning fancy disciplines about computers, but in common (literature, art, physics, etc) I feel like I'm loosing the moment. Anyway, nothing can stop me from spending time on lectures with my laptop, making my own projects or working on remote job for money.

At the same moment, I have a lot of friends which is studying languages or law, for example, and still coding, they make cool things, contribute to nice projects.

> the society thinks that you need to get into the top colleges to become something worth

Actually, the same for Ukraine. Parents always want to give a good basis for their children. Colleges seems like a good starting point for them.

Why am I telling you this? Well, I just want to say that it's not matter where you're studying, what you're doing or where you are. If you love something (programming, in this case) or someone, then nothing can be a wall in front of you.

**Comment by Rowno** [comment]
Degrees also have important uses outside of just learning, like immigration (government bureaucracy) and teaching (you need a degree to teach at universities). I wouldn't be in San Francisco right now without my degree.

**Comment by sindresorhus** [comment]
Also see https://github.com/sindresorhus/ama/issues/525.
