### ISSUE TITLE
Who is helping you?

### ISSUE THREAD

**Issue by stephenplusplus** [sindresorhus/ama#468]
Your OSSing is on another level. Have you found a way to get some community assistance yet? By now, you would think someone else like you would have shown up.

**Comment by sindresorhus** [comment]
<img src="https://user-images.githubusercontent.com/170270/27564621-42c31c5c-5ad9-11e7-989e-51f8f7cc41e7.gif" width="170" align="right">

I get regular help by many awesome humans. I could not manage everything I do without a lot help.

Just mentioning a few: @SamVerschueren @kevva  @Qix- @AlexTes @floatdrop @bfred-it @silverwind @schnittstabil @lukechilds @veniversum @LinusU @marionebl @paulmolluzzo @jfmengels

**Comment by paulmolluzzo** [comment]
Wow!

![](https://media.giphy.com/media/l44QtvEWNvzsCs5Qk/source.gif)

**Comment by Qix-** [comment]
![](https://media4.giphy.com/media/l1IYjLwJjfUek47gA/giphy.gif)

**Comment by bfred-it** [comment]
![img_1383](https://user-images.githubusercontent.com/1402241/27569486-74b53e88-5b2a-11e7-8080-b084031484ba.GIF)

**Comment by lukechilds** [comment]
![](https://media.giphy.com/media/5GoVLqeAOo6PK/giphy.gif)

**Comment by silverwind** [comment]
![](https://user-images.githubusercontent.com/115237/27595075-eaded7be-5b5b-11e7-91fa-daffe1e993ff.gif)

**Comment by AlexTes** [comment]
![](https://media.giphy.com/media/g9582DNuQppxC/giphy.gif)

**Comment by LinusU** [comment]
![](https://media.giphy.com/media/5GoVLqeAOo6PK/giphy.gif)

**Comment by LinusU** [comment]
![](https://media.giphy.com/media/CAxbo8KC2A0y4/giphy.gif)
