### ISSUE TITLE
How are you?

### ISSUE THREAD

**Issue by xecho0049** [sindresorhus/ama#472]

**Comment by xecho0049** [comment]
how are you ?

**Comment by sindresorhus** [comment]
I'm great! Just enjoying the summer in Norway with family and friends. 😎

<img src="https://user-images.githubusercontent.com/170270/27566154-8c128c08-5ae3-11e7-95d3-e349d9f2c9a4.jpg" height="180"> <img src="https://user-images.githubusercontent.com/170270/27566197-d63c2b36-5ae3-11e7-9b6f-ce05a9a3e53b.jpg" height="180"> <img src="https://user-images.githubusercontent.com/170270/27566225-1284c922-5ae4-11e7-9b86-df0803739576.jpg" height="180">
