### ISSUE TITLE
Where do you buy domains?

### ISSUE THREAD

**Issue by sholladay** [sindresorhus/ama#476]
Most of the domain registrars are terrible. ~~I wish [ZEIT](https://zeit.co) let me buy domains through them, since they do [DNS](https://zeit.co/world)~~ (edit: hooray, you can now). Know of any awesome ones? What do you use?

**Comment by hugomd** [comment]
@sholladay You can already buy domains through Zeit — [see here](https://zeit.co/domains).

**Comment by sholladay** [comment]
Ha I just discovered that myself. Very cool. I'll leave this open to see what Sindre says.

**Comment by sindresorhus** [comment]
I've bought most of my domains through Namecheap. It's far from good, but it's the least terrible one I've tried yet. I will definitely use ZEIT for future domains.
