### ISSUE TITLE
Why do you like pink stuffs?

### ISSUE THREAD

**Issue by dikiaap** [sindresorhus/ama#477]
And why so much?

edit: I just google it and already know.

**Comment by sindresorhus** [comment]
I just like the color and I don't care what people think.

Pink being girly is just an ephemeral cultural thing:

> The generally accepted rule is pink for the boys, and blue for the girls. The reason is that pink, being a more decided and stronger color, is more suitable for the boy, while blue, which is more delicate and dainty, is prettier for the girl.
>
> — Earnshaw's Infants' Department in June 1918 (Source https://en.wikipedia.org/wiki/Pink)

> In the 18th century, it was perfectly masculine for a man to wear a pink silk suit with floral embroidery.
>
> — https://www.theatlantic.com/sexes/archive/2013/08/pink-wasnt-always-girly/278535/

**Comment by vko-online** [comment]
well, it's all ok, but don't you think that there somewhere deep, we all equal, that tryin' to be anormal/different is kinda fake thing, just like your pink color, why people keep tryin' to be different while their aren't. might be insulting, but who gives a shi* tho.

**Comment by sindresorhus** [comment]
![xaxav](https://user-images.githubusercontent.com/170270/27520839-571555a0-5a14-11e7-8395-20d016772a1c.gif)

**Comment by TheCodersHangout** [comment]
Today is world pink day!

**Comment by ahmadawais** [comment]
Yeah, I like #Purple 💜 and that's just that.
