### ISSUE TITLE
How do you create cross-platform packages?

### ISSUE THREAD

**Issue by KELiON** [sindresorhus/ama#483]
I've noticed you have several cross-platform packages ([wallpaper](https://github.com/sindresorhus/wallpaper), [shell-env](https://github.com/sindresorhus/shell-env/blob/master/index.js), [default-shell](https://github.com/sindresorhus/default-shell/blob/master/index.js), etc). How do you create and test these packages? Do you have VMs for linux and windows? Do you work on these packages with other people who use linux/windows?

**Comment by sindresorhus** [comment]
I have a Ubuntu and Windows VM. I first develop a package for macOS and write tests, then I open it in the VMs and add cross-platform support, which is made easier by having the tests written.
