### ISSUE TITLE
Would you consider unblocking me?

### ISSUE THREAD

**Issue by empireworld1999** [sindresorhus/ama#485]
You was blocked my [**EmpireWorld**](https://github.com/empireworld/) account.

So i made a new GitHub account for asking you or forgiveness.

I don't know why but i wanted to star and contribute to your repositories but can't and github said:

> You can't perform this action at this time.

I have contacted the GitHub support and they said you have blocked my [**EmpireWorld**](https://github.com/empireworld/) account.

I really love to contribute to your projects, because they are awesome.

Thanks.

**Comment by sindresorhus** [comment]
Sure, unblocked, but please stop the spamming :)
