### ISSUE TITLE
How did you meet Addy Osmani?

### ISSUE THREAD

**Issue by yairodriguez** [sindresorhus/ama#49]

**Comment by arthurvr** [comment]
Duplicate of https://github.com/sindresorhus/ama/issues/44.

**Comment by yairodriguez** [comment]
Nope, my question just focus in Addy.

**Comment by sindresorhus** [comment]
I was a late convert to GitHub and mostly just used it to star popular jQuery plugins and such. One cold November night in 2011 I accidentally stumbled upon a project called [TodoMVC](http://todomvc.com) by @addyosmani. TodoMVC is a project that offers same todo app made using a myriad of different JS frameworks. Back then I mostly did jQuery, so I decided to [submit a todo app made using jQuery](https://github.com/tastejs/todomvc/pull/26). Addy merged my pull request, which was pretty exhilarating. I continued to fix other open issues, and after some time Addy invited me to join the project. I think we realized early that we worked well together. Both bringing different strengths to the table and a strong passion for the web and fixing all the things. Later we worked on many projects together, like [Yeoman](http://yeoman.io/), [Web Starter Kit](https://github.com/google/web-starter-kit/), and more. That's the story of how Addy and I became good friends. I don't think I would be doing Open Source today if it weren't for Addy inviting me to TodoMVC and mentoring me. It sparked my passion for Open Source. I learned so much from managing that project. Thank you Addy.

**Comment by mahnunchik** [comment]
:+1:

**Comment by jaan** [comment]
:+1:

**Comment by beforeadream** [comment]
:+1:

**Comment by ElvisAttro** [comment]
Inspiring !

**Comment by arnellebalane** [comment]
:+1:

**Comment by ggarek** [comment]
:+1:

**Comment by dankerizer** [comment]
:+1:

**Comment by insanehong** [comment]
:+1:

**Comment by sotayamashita** [comment]
:+1:

**Comment by keesun** [comment]
:+1:

**Comment by igauravsehrawat** [comment]
:+1:

**Comment by claudiopro** [comment]
Great story :+1:

**Comment by silviu-burcea** [comment]
@sindresorhus What valuable advices have you received from Addy and are worth for sharing?

**Comment by sindresorhus** [comment]
@silviu-burcea Great question! Can ask it in a new issue?

**Comment by silviu-burcea** [comment]
@sindresorhus sure, #264 is waiting for you :)

**Comment by fauker** [comment]
:+1:
