### ISSUE TITLE
Your favorite condoms?

### ISSUE THREAD

**Issue by wsobe** [sindresorhus/ama#494]

**Comment by chr0non** [comment]
Important question

**Comment by sindresorhus** [comment]
None? 😝 I usually use this blue Durex, because Durex is all I can find in Thailand. I've been thinking about ordering online.


Todo:
- http://www.condomking.eu/einhorn-unicorn
- https://www.mycondom.com/love-light-condom-315

**Comment by wsobe** [comment]
Thx

**Comment by wsobe** [comment]
@sindresorhus so did you try them?
