### ISSUE TITLE
Are going to release new packages as scoped packages by default?

### ISSUE THREAD

**Issue by mischah** [sindresorhus/ama#498]
Just discovered the following install instructions of [is](https://github.com/sindresorhus/is):

```
$ npm install @sindresorhus/is
```

and wondered if the reason was that there was no appropriate name for exactly that module or if you going to namespace new packages by default.

**Comment by sindresorhus** [comment]
No, I prefer unique global names, as they're easier for people to find and remember than generic scoped names. In this case, however, I failed to find a suitable available name, so I went with a scoped package. The API `is.string()` is much nicer than `someName.isString()`.

**Comment by mischah** [comment]
Thanks 😗
