### ISSUE TITLE
Does Open Source bring you new long-term clients?

### ISSUE THREAD

**Issue by paulmillr** [sindresorhus/ama#5]

**Comment by sindresorhus** [comment]
I've had a [full-time job until recently](https://github.com/sindresorhus/ama/issues/14#issuecomment-117747234), so I wouldn't know. Paul, you're probably better apt to answer this question than me?

I am however planning to do some contracting next year, and I think having a visible Open Source presence will be beneficial. Although it should definitely not be the reason you do Open Source.
