### ISSUE TITLE
Do you use skeleton repos?

### ISSUE THREAD

**Issue by jedwards1211** [sindresorhus/ama#503]
One of the ways I've been able to crank out quite a few repos of my own (though mainly for company purposes) is having skeletons for ES2015, React, etc. packages that have all of the dependencies, NPM scripts, and semantic-release configuration I need already set up.

But I can't tell if you're doing anything similar for your packages...do you and if so do you have a link to them?  (If not I can't recommend it more to a prolific developer like you)

**Comment by SamVerschueren** [comment]
#502

**Comment by jedwards1211** [comment]
ah thanks!
