### ISSUE TITLE
Which license should a github page have?

### ISSUE THREAD

**Issue by ricgm** [sindresorhus/ama#504]
I want to make a github page for my account to use it as a blog or showcase future projects. One of this: https://pages.github.com/. I'm not sure which license should the repo username.github.io should have. Maybe the answers is no license at all.

**Comment by sindresorhus** [comment]
I would always recommend adding a license if you want others to be able to reuse some of your work in some form. For code, MIT and BSD are good choices, but for other kinds of content, like a GitHub page, I would go with [Creative Commons](https://creativecommons.org/choose/).

**Comment by ricgm** [comment]
Is it possible to have the content of a site under a Creative Commons license and the code of the site under MIT?

**Comment by sindresorhus** [comment]
Sure, but usually better to keep it simple, and personal sites usually don't have a lot of code.
