### ISSUE TITLE
Getting integrity checksum failure on strip-json-comments

### ISSUE THREAD

**Issue by MrRoyce** [sindresorhus/ama#506]
Hi there, I am running `npm install` on my project and I guess some library is using the strip-json-comments library.

That library is failing the sha1 integrity check with:
`trying strip-json-comments@2.0.1 by hash: sha1-HhX7ysl9Pumb8tc7TGVrCCu6+5E=`
`error sha1-HhX7ysl9Pumb8tc7TGVrCCu6+5E= integrity checksum failed when using sha1: wanted sha1-HhX7ysl9Pumb8tc7TGVrCCu6+5E= but got sha1-PFMZQukIwml8DsNEhYwobHygpgo=. (2270 bytes)`

Any ideas on this?

**Comment by CodeMan99** [comment]
This is an [integrity](https://docs.npmjs.com/files/package-lock.json#integrity) violation due to your package-lock.json. I honestly do not know how to correct the violation (because I do not use package-lock), but I would assume `rm -rf node_modules; npm install` should help?

**Comment by sindresorhus** [comment]
From the readme:

> Bugs & feature requests should be opened on the relevant issue tracker.

This is a npm support question though, and should be asked on https://github.com/npm/npm/issues
