### ISSUE TITLE
What do you miss the most from JavaScript when writing Swift code?

### ISSUE THREAD

**Issue by mlcdf** [sindresorhus/ama#507]
Hi Sindre.

I'm curious. What's the thing (or things) you miss the most from JavaScript (and I mean JavaScript itself, not it's ecosystem) when you write Swift code?

**Comment by sindresorhus** [comment]
The fact that JavaScript is not compiled is a big productivity win when prototyping. Swift does have Swift playgrounds for prototyping, but it's still slower. I also like how easy it is to mock and modify built-in functionality for testing, polyfilling, or experimenting in JS. Swift is painfully lacking a [spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator), so you can't easily use all the arguments from one function in another one or convert an array to function arguments. JavaScript language docs are also much better. Swift itself has ok docs, but the Apple docs for doing things with macOS or iOS are from non-existent to barely usable.

It's the Node.js ecosystem I miss the most though. I wish we had npm for Swift. The threshold for adding dependencies in Swift code is much higher, for compile speed, version conflict, and maintainability reasons.

**Comment by mlcdf** [comment]
Thank you for this answer.

And thank you for all your open source work too. I've read and used a crazy amount of your code for the past 2 years and it made me learn about so many things: JavaScript obviously, but also linting, coding standards, CI, yeoman, ... 

I am very grateful to you!
