### ISSUE TITLE
How do you pronounce your name?

### ISSUE THREAD

**Issue by patik** [sindresorhus/ama#51]

**Comment by sindresorhus** [comment]
[Recorded it](https://github.com/sindresorhus/stuff/blob/c31bba1997c6c081ce2058942fda72367355a875/Sindre%20Sorhus%20pronunciation.m4a?raw=true) for you.

**Comment by stephenplusplus** [comment]
So much fancier than my interpretation. Ugh, stupid American.

**Comment by patik** [comment]
Thanks!
