### ISSUE TITLE
Cash withdrawals in Bangkok?

### ISSUE THREAD

**Issue by mohamedhayibor** [sindresorhus/ama#512]
From your guesstimate, you spend about 50,000 baht a month, do you get all of that from ATMs?

1. How much do you withdraw at once?
2. Do you always pay the 220 baht fee on every withdrawal?
3. What's your overall tragedy to not get bitten by too much fees?
4. What's your experience with counter withdrawals over atm ones?
5. Any final tips on this topic?

Related

* Do you have a Thai debit card, if so which one?

**Comment by wmertens** [comment]
Also, did you try using cryptocurrencies to avoid the exchange fees?

**Comment by sindresorhus** [comment]
I usually withdraw 30,000 baht at the time as that's the maximum I can get from an ATM. I personally wouldn't bother with counter withdrawals or cryptocurrencies. 0.7% fee is not that bad.

If you want to avoid the fees, you could get a Thai bank account and card.

**Comment by bfred-it** [comment]
@sindresorhus that's a lot, which ATM do you use? I can rarely 20000 out (which seems to be my own banks' limit)

**Comment by sindresorhus** [comment]
@bfred-it I too have problems taking out more than 10000 or 20000 with most ATMs, but Krungsri, the yellow one, always works.
