### ISSUE TITLE
Is there a yo generator or node starter template you use for starting your node packages?

### ISSUE THREAD

**Issue by MartinMuzatko** [sindresorhus/ama#522]
Hey there Sindre!

Even though it is very specific to the needs of each project, is there a common project structure you follow and basic tools you always install to get started?

Best,
Martin

**Comment by SamVerschueren** [comment]
Yes, https://github.com/sindresorhus/generator-nm

**Comment by MartinMuzatko** [comment]
Without babel? wow.

**Comment by luftywiranda13** [comment]
@MartinMuzatko you don't always need to use babel

**Comment by MartinMuzatko** [comment]
If I want to use async/await and still want to support node 4, then I have to.

**Comment by sindresorhus** [comment]
I also have a normal boilerplate: https://github.com/sindresorhus/node-module-boilerplate
