### ISSUE TITLE
What color scheme do you use for GitHub labels?

### ISSUE THREAD

**Issue by thasmo** [sindresorhus/ama#534]
I've noticed the label colors used in [`sindresorhus/modern-normalize`](https://github.com/sindresorhus/modern-normalize) and I like them a lot.

What colors do you use?

**Comment by CodeMan99** [comment]
Though not as easy as getting an answer, you can just inspect the element and look at the `background-color` value.

**Comment by sindresorhus** [comment]
What @bfred-it said :)
