### ISSUE TITLE
What is your stand on TV?

### ISSUE THREAD

**Issue by TheAmazingPT** [sindresorhus/ama#536]
Hey @sindresorhus =)

Do you have one and are you using it? If yes, how often?
I think i read that you are binge watching your shows primarly on your MacBook, right?
How is all this media consumption effecting your work output?

**Comment by sindresorhus** [comment]
I used to watch a lot TV (way too much) when I was a teen and early adult. I haven't owned a TV in more than 10 years now. I don't miss it. I watch some movies and shows with my wife on my laptop. Maybe one episode every other day on average. I also sometimes watch some YouTube educational stuff while eating breakfast. I try to keep it to a minimum though, so not to affect my productivity.
