### ISSUE TITLE
Why do you favor npm over Yarn?

### ISSUE THREAD

**Issue by jorgegonzalez** [sindresorhus/ama#540]
I haven’t seen anything in your modules that indicates a use of `yarn`. Why do you prefer to use `npm`?

**Comment by jorgegonzalez** [comment]
Also what do you think of `pnpm`?

**Comment by sindresorhus** [comment]
Yarn simply solves a lot of problems I never had (especially Yarn 2). While Yarn had the upper hand for a while, it forced npm to drastically improve. So a win-win. `pnpm` builds on a good idea, but the last time I tried it, there were too many incompatibilities.
