### ISSUE TITLE
Do you ever use GitHub news feed?

### ISSUE THREAD

**Issue by nikitavoloboev** [sindresorhus/ama#545]
I am curious because given how many repos you have and with GitHub not providing the ability to mute `.. starred your repo` updates, it makes the news feed barely usable if you have a couple of popular GitHub projects.

Do you simply ignore the GitHub feed or it works well for you?

**Comment by salmanulfarzy** [comment]
Answer most likely would be [refined-github](https://github.com/sindresorhus/refined-github) browser extension, It aggressively hides useless news feed items including starring repositories among others.

> Because seeing who starred your repos doesn't provide any practical value. It's just noise.

https://github.com/sindresorhus/refined-github/issues/1222#issuecomment-376810120

**Comment by sindresorhus** [comment]
No, the news feed is mostly useless, in my opinion. I just go directly to notifications.
