### ISSUE TITLE
 If you could give some advice to someone who would like to contribute to open source projects, like you do a lot, what would you say?

### ISSUE THREAD

**Issue by AlexGalhardo** [sindresorhus/ama#549]
I'm a big fan of you work with open source, and you are a great inspiration for millions developers out there.

**Comment by ritiek** [comment]
I can't say for sindresorhus but for me it is the *good feeling* that comes after your PR gets merged and it also helps me make up for my horrible academic performance (or at least that's what I like to think ;)

**Comment by AlexGalhardo** [comment]
We are two then @ritiek , because I am also a horrible scholar student haha, and do some personal projects, and try to help with open source help me to have fun again with programming :D
