### ISSUE TITLE
What's `sindre-playground` all about?

### ISSUE THREAD

**Issue by shreyasminocha** [sindresorhus/ama#552]
https://github.com/sindresorhus/sindre-playground

What're you experimenting with o'er there?

**Comment by SamVerschueren** [comment]
We test releases of [np](https://github.com/sindresorhus/np), or new things features of [refined-github](https://github.com/sindresorhus/refined-github). I have one as well and it's just nice to have a repository where you can dump stuff in and fiddle around. Previously I had to test some things on Travis, then it's perfect to have a playground just for that.
