### ISSUE TITLE
What’s in your bag / backpack?

### ISSUE THREAD

**Issue by FleXoft** [sindresorhus/ama#555]

**Comment by sindresorhus** [comment]
The backpack I use when I work at coffee shops and other places usually contains:

- MacBook Pro 16-inch, 2021
- AirPods Pro 2
- USB-C cable

**Comment by mrwhiterk** [comment]
What possessions do you have now? Do you have any thoughts/experience living as a minimalist?

**Comment by sindresorhus** [comment]
Updated the answer, though not much has changed.

**Comment by mrwhiterk** [comment]
I meant in general as far as clothing, furniture, etc..? Do you tend to stick to a nomadic backpacker lifestyle or do you find yourself accumulating things in SEA?

**Comment by sindresorhus** [comment]
I'm settled in SEA, so I definitely have more stuff than can fit in a backpack, but I also like to live minimal. So at home, it's mostly necessary clothes, computer, phone, chargers.

**Comment by mrwhiterk** [comment]
Awesome thanks!
