### ISSUE TITLE
What is your current home directory structure?

### ISSUE THREAD

**Issue by vikepic** [sindresorhus/ama#557]
Related to #298 : How do you organize your home dir and what is the reasoning behind the structure?

**Comment by sindresorhus** [comment]
```
.
├── Applications
├── Desktop
├── Documents
├── Downloads
├── Movies
├── Music
├── Pictures
├── dev
│   ├── deprecated
│   ├── forks
│   ├── oss
│   │   ├── ava
│   │   ├── chalk
│   │   └── …
│   ├── private
│   ├── todo
│   └── scratchpad.md
```

- **deprecated:** Unmaintained projects are moved here to reduce noise in other directories.
- **forks:** Repos I fork are placed here.
- **oss:** My open source projects.
- **private:** Private projects like my macOS apps.
- **todo:** Projects I started but never finished enough to publish.
- **scratchpad.md:** My brain in written form. It's always the first tab in Sublime Text. Here I write all my random ideas and todos. It's a big mess that just keeps getting longer...
