### ISSUE TITLE
Why do you always turn off package.lock?

### ISSUE THREAD

**Issue by telmen** [sindresorhus/ama#559]
You seem turning off package lock for almost every js projects? Any reason to do that?

**Comment by sindresorhus** [comment]
See https://github.com/sindresorhus/ama/issues/479#issuecomment-310661514

**Comment by spookyUnknownUser** [comment]
How come you don't use one on https://github.com/sindresorhus/refined-github then, wouldn't that count as an app 🤔?

**Comment by sindresorhus** [comment]
Good point. Fixed: https://github.com/sindresorhus/refined-github/commit/4f52e838223d97b781bafaf3fdd395bbdd080bc6
