### ISSUE TITLE
How to find a girlfriend?

### ISSUE THREAD

**Issue by dcpnonstop** [sindresorhus/ama#563]

**Comment by yunshang** [comment]
try boy firend

**Comment by Dante-dan** [comment]
just do it.

**Comment by sindresorhus** [comment]
Do things you usually wouldn't do. Go outside your comfort zone. I met my girlfriend, now wife, at a CouchSurfing meetup while traveling. Normally, I would never go to large social gatherings like that, but I had decided to force myself to try out new things and be more outgoing.

There's also Yahoo Answers 😝 (not serious): https://answers.yahoo.com/search/search_result?p=%22how%20do%20I%20find%20a%20girlfriend%22
