### ISSUE TITLE
Are you a literal unicorn?

### ISSUE THREAD

**Issue by Qix-** [sindresorhus/ama#569]
And how does your wife feel about it?

![](https://media1.giphy.com/media/J5l7dxGqMWOhG/giphy.gif?cid=3640f6095c376ac02f467a345944866b)

**Comment by sindresorhus** [comment]
Yes

[![image](https://user-images.githubusercontent.com/170270/53466483-c2372a00-3a84-11e9-944e-98247798953e.png)](https://blog.sindresorhus.com/about-sindre-sorhus-42786d2e191b)

> And how does your wife feel about it?

She's fine with it other than the occasional horn incident.
