### ISSUE TITLE
Substitutions in Caprine? 

### ISSUE THREAD

**Issue by brushmedia** [sindresorhus/ama#572]
really love the new Caprine release, but miss being able to enable system substitutions (for spelling autocorrect and keyboard shortcodes). any chance that support for substitutions will make it in the next update? thanks!

**Comment by sindresorhus** [comment]
> Guidelines: Bugs & feature requests should be opened on the relevant issue tracker.
> \- https://github.com/sindresorhus/ama#guidelines
