### ISSUE TITLE
What’s your favorite movie?

### ISSUE THREAD

**Issue by mxcl** [sindresorhus/ama#574]
Top three, if you will.

**Comment by sindresorhus** [comment]
I like science fiction movies.

1. [Ex Machina](https://www.imdb.com/title/tt0470752/) - Thought-provoking movie that explores what it means to be human. Deep, suspenseful, and at times claustrophobic. Visual effects are so well done and natural you don't even notice them.
2. [Interstellar](https://www.imdb.com/title/tt0816692/)
3. [Arrival](https://www.imdb.com/title/tt2543164/)
