### ISSUE TITLE
What is your credit card details?

### ISSUE THREAD

**Issue by rousan** [sindresorhus/ama#581]
Maybe, I took ama literally 😬.

**Comment by vsp64** [comment]
![vcard](https://user-images.githubusercontent.com/1668049/57029074-67b77700-6c49-11e9-9fbd-3764642c9e6b.jpg)

**Comment by sindresorhus** [comment]
Here's my VISA card:

![IMG_0457 Redacted](https://user-images.githubusercontent.com/170270/59561666-0b6bb380-904d-11e9-9946-670a8b281f02.jpg)
![IMG_0458 Redacted](https://user-images.githubusercontent.com/170270/59561665-0b6bb380-904d-11e9-8580-d7debc293cb7.jpg)

Please excuse the horrible picture. I was 13.

---

And I will definitely get an Apple Card when it's available in Norway!
