### ISSUE TITLE
How do you create animated SVGs for your READMEs?

### ISSUE THREAD

**Issue by kevinschaich** [sindresorhus/ama#582]
Like this one from the [Ora README](https://github.com/sindresorhus/ora):

![](https://github.com/sindresorhus/ora/raw/master/screenshot.svg?sanitize=true)

Did you do this manually? Or is there a library/app that makes this easy?

Would be so cool to reduce file size via SVG rather than using animated GIFs! 🙂

**Comment by salmanulfarzy** [comment]
Seems like the tool used was [svg-term-cli](https://github.com/marionebl/svg-term-cli) and relevant PR was [sindresorhus/ora#66](https://github.com/sindresorhus/ora/pull/66). Also [history](https://github.com/sindresorhus/ora/commits/master/screenshot.svg) for the screenshot links to related discussions.

**Comment by sindresorhus** [comment]
Yes, `svg-term-cli`. It's great.

Here's an example for how to keep the SVG in sync with a live fixture: https://github.com/sindresorhus/electron-timber/blob/6251298a31d7a3b897adb2b0a9c33d298dab2c2c/package.json#L16
