### ISSUE TITLE
Why does your query-string repo have GitHub Issues disabled?

### ISSUE THREAD

**Issue by callumlocke** [sindresorhus/ama#588]
Not sure if you've disabled Issues for any other projects, but just noticed it's disabled on [query-string](https://github.com/sindresorhus/query-string) and wondered why.

**Comment by sindresorhus** [comment]
I think that's the only repo where I have issues disabled. I disabled issues because I got too many issues that were not related to bugs / features, but rather support questions and how to use it with Webpack, Create React App, IE11, etc, even though that's documented in the readme.
