### ISSUE TITLE
How did you time-lapse contributions

### ISSUE THREAD

**Issue by jletey** [sindresorhus/ama#589]
In your [tweet](https://twitter.com/sindresorhus/status/1092813820706189313), you have a time-lapse of your contributions ... how exactly did you take this? I must know 😄!

**Comment by salmanulfarzy** [comment]
He mentioned those screenshots were taken with [paulhammond/webkit2png](https://github.com/paulhammond/webkit2png) in [another tweet](https://twitter.com/sindresorhus/status/1092815842432040961), Possibly turned into video with `ffmpeg` or `imagemagick`

**Comment by johnletey** [comment]
@salmanulfarzy  thanks for this ... I'm curious to see what command @sindresorhus was running (or if he was scheduling the command somehow)

**Comment by sindresorhus** [comment]
I used `webkit2png` and `ffmpeg`.

Today, I would have used [`capture-website-cli`](https://github.com/sindresorhus/capture-website-cli) instead of `webkit2png`.
