### ISSUE TITLE
Are you attending any (javascript) conferences?

### ISSUE THREAD

**Issue by robbbz** [sindresorhus/ama#6]
Which ones? Thanks and cheers :beers:

**Comment by sindresorhus** [comment]
Probably none this year. I'm in Norway now for the summer and will be busy traveling in Asia in the fall.

Contrary to most people in tech (it seems), I'm not really that into conferences. I much prefer to just meet up with some people, chat, and hack on cool ideas.

**Comment by noffle** [comment]
What are your approaches to meeting folks in the community? Just poking them on Twitter; sending PRs to their repos?

**Comment by sindresorhus** [comment]
When traveling I asked on Twitter if anyone wanted to meet up and checked out local meetup events on http://www.meetup.com

Just ask. Most are happy to meet up. Took me a long time to realize and dare this however.
