### ISSUE TITLE
What is your feeling on the development of Gulp and the fourth release eagerly awaited ?

### ISSUE THREAD

**Issue by zckrs** [sindresorhus/ama#60]

**Comment by sindresorhus** [comment]
I wish it would ship, as it fixes a lot of annoyances with gulp@3, but I don't have any right to complain as I have done nothing to make it happen. Open source is a gift, not a right. It's as good as *we* make it, that includes users, not just the maintainers.

There are many tickets labeled ["Help wanted"](https://github.com/gulpjs/gulp/labels/help%20wanted) on the gulp issue tracker. Go nuts.

// @phated @contra
