### ISSUE TITLE
What to-do apps do you use?

### ISSUE THREAD

**Issue by ryanccn** [sindresorhus/ama#604]
What todo apps do you use? Do you use *any*?

Thanks!

**Comment by sindresorhus** [comment]
I use the built-in Reminders app on macOS and iOS for general todo's. I also have a large text file always open in Sublime Text where I put tood's and other brainstorming notes. And I use the built-in Notes app for project-specific todo's, where I have one note for each project and todo items in the notes. Not the cleanest strategy, but it works for me.

**Comment by ryanccn** [comment]
Thank you 👍

**Comment by luckman212** [comment]
> ... text file always open in Sublime Text where I put todo' and other brainstorming notes

+1 for ST. I do the same thing. I think mostly because it opens so damn fast.
