### ISSUE TITLE
Why is there a license for `arr-flatten` in the crx for refined github?

### ISSUE THREAD

**Issue by spookyuser** [sindresorhus/ama#606]
Random question but I happened to be browsing the crx for refined github and found a file called `content.js.LICENSE.text` containing this:

```
/*!
 * arr-flatten <https://github.com/jonschlinkert/arr-flatten>
 *
 * Copyright (c) 2014-2017, Jon Schlinkert.
 * Released under the MIT License.
 */

```

As far as I can see `arr-flatten` is [never used](https://github.com/sindresorhus/refined-github/search?q=flatten&unscoped_q=flatten) in the project but the license is somehow being copied into the distribution folder 🤔 

Curious if you know where it's used and how it's being copied to the distribution folder?

Thanks!

**Comment by fregante** [comment]
It's a sub-dependency and webpack automatically creates those .LICENSE files from the bundles it generates. 

```
├─┬ dom-chef@3.6.3
│ └── arr-flatten@1.1.0 
```
