### ISSUE TITLE
If you did not use a Mac, what would you use?

### ISSUE THREAD

**Issue by harshkhandeparkar** [sindresorhus/ama#619]
Would be nice if you specify:
1) Which OS you would like (if Linux, specify distro)
2) General specs
3) RGB or not? :stuck_out_tongue_winking_eye:
4) If you were forced to use this, how many days (or hours or minutes) would you survive?

**Comment by sindresorhus** [comment]
1. elementary OS. It's the most macOS-like Linux distro.
2. XPS 15 (fully specced)
3. DCI-P3
4. 0.1337 minutes
