### ISSUE TITLE
Can Discussions replace Ask me anything?

### ISSUE THREAD

**Issue by antleblanc** [sindresorhus/ama#620]
Hi :hand:!

I noticed that you've recently opened repository that enable **Discussions** feature.

see: https://github.com/sindresorhus/swiftui

I'm wondering if current format ("[Ask me anything]") which uses mainly **Issues**, could be converted into a Discussion.

What's your feeling about this?

Feature Discussions:
https://docs.github.com/en/free-pro-team@latest/discussions

:pray: Thank you!

[Ask me anything]: https://github.com/sindresorhus/ama#ask-a-question--read-questions

**Comment by sindresorhus** [comment]
Yeah, it could. We could document that option. I don't plan to move to discussions myself in the near future as it's too much work to manually move individual issues. But for new AMA's, it does make sense.

**Comment by obahareth** [comment]
@antleblanc 
If you'd like a template to use for an AMA with **Discussions** instead of **Issues**, I just updated my (mostly dead) AMA repo to use it:

https://github.com/obahareth/ama
