### ISSUE TITLE
Have you considered a community health files repo (.github) for your funding.yml file?

### ISSUE THREAD

**Issue by dominicegginton** [sindresorhus/ama#621]
A repo with the special name of `.github` can be used for default comunity health files such as the funding config files, pull request and issuse templates along with code of conduct information. This would simplify and save you time when creating new repos as you woulnt have to worry about creating and maintaing there files. If any repo then needed to override these defults that you setup, a comnuty health file created within the repo itself will override the one within the `.github` repo. You can find more about default comunity health files  [here](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-default-community-health-file). And here is a [example](https://github.com/dominicegginton/.github) repo of my own.

Have you considered using this GitHub feature ?

**Comment by sindresorhus** [comment]
Good idea. The last time I checked this feature, it was only available for organizations. I'm glad they added support for individual users too.

Done: https://github.com/sindresorhus/.github
