### ISSUE TITLE
What emoji's do you wish existed?

### ISSUE THREAD

**Issue by meeeesz** [sindresorhus/ama#66]
:unicorns:

**Comment by sindresorhus** [comment]
I only really want a :unicorn: emoji and it seems my wish will become reality: https://twitter.com/sindresorhus/status/611283378395062272

Some other ones that would be useful:

- Dinosaur
- Magical pony
- Twerking
- Neil deGrasse Tyson face
- Sudo sandwich
- Selfie
- Yarn bombing
- Cheez doodle fingers
- YOLO
- Don't disturb, eating dinner
- Unicorn emoji magical modifier (Like the skin tone modifier, but ability to add wings, change color and stuff of the unicorn)

**Comment by jleeothon** [comment]
Let's thank 2017: 🦕🦖

**Comment by jleeothon** [comment]
There's also a selfie emoji 🤳

From Emojipedia: 

> Selfie was approved as part of Unicode 9.0 in 2016 and added to Emoji 3.0 in 2016.
