### ISSUE TITLE
How can we donate to you?

### ISSUE THREAD

**Issue by meeeesz** [sindresorhus/ama#68]
gratipay or something similar?

**Comment by sindresorhus** [comment]
Nah. Donate to a [good cause](https://girlswhocode.com/) instead. I'm fine, and I don't really care about money other than what I need to survive.

**Comment by melvin0008** [comment]
Really cool :+1: +1:

**Comment by arnellebalane** [comment]
:+1:

**Comment by nickedes** [comment]
Nice :+1:
