### ISSUE TITLE
Did you ever try Emacs/Vim?

### ISSUE THREAD

**Issue by meeeesz** [sindresorhus/ama#69]
I wonder if I should check it out a colleague of my likes emacs.

**Comment by sindresorhus** [comment]
I've always been envious of people being efficient in either of those. I did try to use Vim for a couple of weeks once, but I never got over the initial learning bump, got frustrated, and went back to Sublime Text as I had a lot of work to do. Might try again in the future, but right now Sublime Text works for me, and I'd rather spend my time making things.

**Comment by nickedes** [comment]
:+1:

**Comment by jrolfs** [comment]
I've been a Sublime Text user for a long time. I tried Vim for a month or so, got a `.vimrc` dialed and ended up getting frustrated with the plugins and especially the lack of good "find/replace in project." I switched back to Sublime Text and added [Vintageous](https://github.com/guillermooo/Vintageous) and have been extremely pleased with the combo. Might be worth trying out :)
