### ISSUE TITLE
What other languages do you code in?

### ISSUE THREAD

**Issue by robbbz** [sindresorhus/ama#7]

**Comment by sindresorhus** [comment]
I used to do a lot of PHP and Python some years ago, so pretty proficient in those, but the past few years I've mostly only done JavaScript. I'm not a PL nerd, so my desire to make things has been stronger than my desire to experiment with languages. Although I have done a good amount of Objective-C the past year. I've also done a tiny bit of vanilla C, but I'm awful at it.

My goal going forward is to get proficient at Swift and Rust. Those are the languages I find most exciting at the moment. My [moonshot](http://whatis.techtarget.com/definition/moonshot) is to be proficient at Haskell one day.

**Comment by jedireza** [comment]
> I'm not a PL nerd, so my desire to make things has been stronger than my desire to experiment with languages.

Well put. I feel the same way.

**Comment by Qix-** [comment]
If you know Objective C, you basically know C. :D Standard library is pretty simple, too. Only thing you start to miss are collections.
