### ISSUE TITLE
Where do you go if you have support questions?

### ISSUE THREAD

**Issue by meeeesz** [sindresorhus/ama#70]
Like if you can't figure out something where do you go?

**Comment by sindresorhus** [comment]
I used to use StackOverflow a lot. It was great, but its quality has really bottom rocketed in the recent years. IRC is also a good option. Lots of welcoming communities there.

Having a network of mentors and friends is also very beneficial.

Although I try very hard to figure it out myself before asking as I love a good challenge, and it's a great feeling having solved something that initially felt impossible.
