### ISSUE TITLE
Why do you often star your own repos, often retroactively?

### ISSUE THREAD

**Issue by williamboman** [sindresorhus/ama#73]

**Comment by es128** [comment]
I've always interpreted the self-star to mean that a new repo is now ready to be consumed/reviewed.

**Comment by sindresorhus** [comment]
The star button is like this red button you just have to click. It kinda bothers me if it's not "starred". When I create a project I like to snooze them to another day in the future so I can review the code again with fresh eyes. This helps me keep the quality high.
