### ISSUE TITLE
I'm obsessed to find the best theme to code for Sublime Text. What are your favorites themes ?

### ISSUE THREAD

**Issue by juancabrera** [sindresorhus/ama#74]

**Comment by DirtyF** [comment]
See #28

**Comment by sindresorhus** [comment]
I currently use [Oceanic Next](https://github.com/voronianski/oceanic-next-color-scheme), but I'm also a big fan of [Tomorrow Night Eighties](https://github.com/chriskempson/tomorrow-theme).
