### ISSUE TITLE
Selfie

### ISSUE THREAD

**Issue by quertyyyyy** [sindresorhus/ama#75]
So can I ask for a selfie?

**Comment by matiassingers** [comment]
![](http://d.justpo.st/media/images/2013/07/cb5e5b590579a545f25e7465d1e70bba.gif)

**Comment by softmonkeyjapan** [comment]
@matiassingers To bad there is no `like button`. Love it

**Comment by sindresorhus** [comment]
![img_6762](https://cloud.githubusercontent.com/assets/170270/8505867/a9d2a110-21f6-11e5-96f2-e6cf7e997dda.jpg)

**Comment by arthurvr** [comment]
:+1:

**Comment by caoer** [comment]
:+1:
