### ISSUE TITLE
What (if anything) do you listen to while coding?

### ISSUE THREAD

**Issue by Trott** [sindresorhus/ama#82]

**Comment by sindresorhus** [comment]
When coding I usually listen to brain-stimulating music like dubstep, electro, etc, to help my productivity.

My SoundCloud favorites: https://soundcloud.com/sindresorhus/likes

**Comment by brunowego** [comment]
:+1:

**Comment by alexbooker** [comment]
I was enjoying your "likes" until I encountered 3 consecutive version of _I Want To Know What Love Is_ :confused:

**Comment by sindresorhus** [comment]
@alexbooker Sorry, was just too tempting to troll people :p
