### ISSUE TITLE
What are you looking at in your avatar?

### ISSUE THREAD

**Issue by mundizzle** [sindresorhus/ama#85]
in this photo...

![](https://avatars1.githubusercontent.com/u/170270?v=3&s=400)

**Comment by sindresorhus** [comment]
The sky, I think. It was taken by my little sister in my parents garden one rainy summer day some years ago.


Original photo:

![](https://cloud.githubusercontent.com/assets/170270/8502801/c3c2a52a-21b5-11e5-8218-84f129777cd2.jpg)
