### ISSUE TITLE
How much money do you have?

### ISSUE THREAD

**Issue by najela** [sindresorhus/ama#89]
Asking cuz I really can't pay all my bills if I spend as much time as you working on open source stuff?

**Comment by arthurvr** [comment]
Lol. Enough for what I need :wink: Thanks!

**Comment by arthurvr** [comment]
haha :lollipop:

**Comment by harshasrinivas** [comment]
LoL

**Comment by lichunqiang** [comment]
this is a question

**Comment by nickedes** [comment]
Naice! Waiting for his reply :stuck_out_tongue:

**Comment by sindresorhus** [comment]
![screen shot 2015-07-09 at 14 13 50](https://cloud.githubusercontent.com/assets/170270/8594926/2b27756c-2646-11e5-9462-40690d128bb5.png)

I have $15K total in my debit & savings accounts, which can last me for another year if I want, living in Asia.

-

> Asking cuz I really can't pay all my bills if I spend as much time as you working on open source stuff?

I worked just as much on open source when I had a [full-time job](https://github.com/sindresorhus/ama/issues/14). It's all about [focus and prioritizing.](https://github.com/sindresorhus/ama/issues/13#issuecomment-117798691)

**Comment by patcon** [comment]
fwiw similar-ish lifestyle, and this was my budget when living in Nicaragua (in [San Juan del Sur](https://img.grouponcdn.com/deal/Xt3YN2uidi2BzbLHUE34EiAi3HF/Xt-960x576/v1/c700x420.jpg)) two summers ago: http://bit.ly/patcon-budget (money can stretch far!)

**Comment by akashnimare** [comment]
@sindresorhus what about now 😄

**Comment by shreyasminocha** [comment]
... or now?

**Comment by othreecodes** [comment]
or now...?

**Comment by abdulhannanali** [comment]
Everyone interested in how much money Sindre has, please get a life. The original question was fine, since I too wanted to know how he happens to pay his bills and stuff while doing full time open source, but it's not really about how much money he has at any given moment and why are y'all so interested in this. 

Do you want to rob him and get a hefty ransom or something?

**Comment by patcon** [comment]
@abdulhannanali With all due respect, I don't feel your response is warranted, nor in the spirit of this space sindre provides

Plus: I don't know your culture, but the money question might not mean the same thing to others that it means to you

Plus, plus: [The Guardian: Norway, the country where you can see everyone's tax returns](https://www.theguardian.com/money/blog/2016/apr/11/when-it-comes-to-tax-transparency-norway-leads-the-field)

**Comment by abdulhannanali** [comment]
@patcon I apologize, my comment was certainly very aggressive, but I still think why people who comment to check with Sindre for the money want to know this stuff.

If they want to check how much tax Sindre filed, certainly they should go and check his tax returns that would be awesome, but It doesn't feel right to comment one thing again and again and I don't get what you mean by culture.

Sindre did answer how much money he had, and his answer was informative. As I mentioned, I certainly don't object to the original question, but the people who are asking him again for the money he has. But what you should notice is that he hasn't replied again to those who asked him again and that was generating email notifications for me.

**Comment by mustafahafidi** [comment]
How about now?
