### ISSUE TITLE
When would I meet you :-) ?

### ISSUE THREAD

**Issue by hemanth** [sindresorhus/ama#9]
Holi, this time in India :) ?

**Comment by sindresorhus** [comment]
I don't have any concrete plans yet, but I really would like to celebrate Holi in India next year. Where in India is the absolute best place to celebrate it in your opinion?

**Comment by hemanth** [comment]
@sindresorhus Well, anywhere in northern India would be fun. [I'm at the South]

**Comment by sindresorhus** [comment]
Cool. Let's talk when it's closer ;)

**Comment by hemanth** [comment]
Awesome!

**Comment by srijanshetty** [comment]
@sindresorhus : There are no absolute best places to celebrate Holi in India but visiting Goa for Holi would be a good idea.

**Comment by shashankmehta** [comment]
A meetup with @sindresorhus in India would be nice :)

**Comment by shidhincr** [comment]
@hemanth @shashankmehta Time to start a JS-Unicorn event .. :)

**Comment by icyflame** [comment]
@hemanth True! Meet-up in India is a great idea! :+1:

**Comment by shreyasminocha** [comment]
Did this happen?
