### ISSUE TITLE
What are your thoughts about CoffeeScript?

### ISSUE THREAD

**Issue by lborgav** [sindresorhus/ama#90]
What are your thoughts about CoffeeScript or similar languages that compiles into Javascript?

**Comment by sindresorhus** [comment]
I remember thinking CS was pretty cool when it was new, but its syntax has always been a bit too ambiguous for my taste and I knew all the JS traps anyways. These days there's really no reason to use CS over ES2015 (ES6) with [Babel](https://babeljs.io). However, CS should definitely get the credit for making "JS as a transpile target" mainstream. I found [Earl Gray](http://breuleux.github.io/earl-grey/) to be quite interesting, but I doubt I'll ever use it over ES2015.
