### ISSUE TITLE
What are your thoughts about front-end frameworks/libraries?

### ISSUE THREAD

**Issue by lborgav** [sindresorhus/ama#91]
Have you used Backbone, Angular, Ember, React, ... ? Do you have a favourite?

**Comment by zzarcon** [comment]
:+1:

**Comment by razvanz** [comment]
#23

**Comment by sindresorhus** [comment]
Frameworks bore me. Having ran TodoMVC I've seen it all. React is my favorite at the moment, but in the end it doesn't matter much. It's so easy to lose focus on what actually matters - the product.
