### ISSUE TITLE
If there was one thing you could make all GitHub users stop doing, what would it be?

### ISSUE THREAD

**Issue by passy** [sindresorhus/ama#93]
One and only one thing.

**Comment by Flet** [comment]
+1 :trollface:

**Comment by SBoudrias** [comment]
I'm having issue with your ama. I can't get it to install

I'm blocked and my boss is pissed, I demand you fix it!

npm WARN package.json fbgiveaway@0.0.1 No repository field.
npm WARN engine cors@2.4.1: wanted: {"node":">=0.10.0","npm":"^1.4"} (current: {"node":"0.10.32","npm":"2.1.9"})
npm WARN engine koa@0.8.1: wanted: {"node":">= 0.11.9"} (current: {"node":"0.10.32","npm":"2.1.9"})

> ws@0.4.32 install /var/lib/jenkins/jobs/stellar-fbgive/workspace/fbgive/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/var/lib/jenkins/jobs/stellar-fbgive/workspace/fbgive/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/var/lib/jenkins/jobs/stellar-fbgive/workspace/fbgive/node_modules/ws/build'
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.10.32","npm":"2.1.9"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.10.32","npm":"2.1.9"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.10.32","npm":"2.1.9"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.10.32","npm":"2.1.9"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.10.32","npm":"2.1.9"})

> v8flags@1.0.1 install /var/lib/jenkins/jobs/stellar-fbgive/workspace/fbgive/node_modules/stellar-payments/node_modules/gulp/node_modules/v8flags
> node fetch.js

flags for v8 3.14.5.9 cached.

> contextify@0.1.9 install /var/lib/jenkins/jobs/stellar-fbgive/workspace/fbgive/node_modules/juice/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

make: Entering directory `/var/lib/jenkins/jobs/stellar-fbgive/workspace/fbgive/node_modules/juice/node_modules/jsdom/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
  SOLINK_MODULE(target) Release/obj.target/contextify.node
  SOLINK_MODULE(target) Release/obj.target/contextify.node: Finished
  COPY Release/contextify.node
make: Leaving directory `/var/lib/jenkins/jobs/stellar-fbgive/workspace/fbgive/node_modules/juice/node_modules/jsdom/node_modules/contextify/build'

> ws@0.4.31 install /var/lib/jenkins/jobs/stellar-fbgive/workspace/fbgive/node_modules/stellar-lib/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/var/lib/jenkins/jobs/stellar-fbgive/workspace/fbgive/node_modules/stellar-lib/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/var/lib/jenkins/jobs/stellar-fbgive/workspace/fbgive/node_modules/stellar-lib/node_modules/ws/build'
npm ERR! cb() never called!

**Comment by shinnn** [comment]
> `current: {"node":"0.10.32","npm":"2.1.9"}`

More often, `current: {"node":"0.10.32","npm":"1.4.8"}`

**Comment by passy** [comment]
@SBoudrias Hahaha!

**Comment by sindresorhus** [comment]
Pretty much what @SBoudrias illustrates. I wish people would stop just mindlessly opening issues without any thought, investigation, or even a simple Google search. So my wish is for less and higher quality issues. Just to put things int perspective, a big part of my time doing open source is spent on commenting and closing invalid issues. Probably about ~95% of the issues I get are invalid.
